--!strict

local LightingDirectorConfig = {}

LightingDirectorConfig.RecentDecisionLimit = 80
LightingDirectorConfig.RecentSuppressionLimit = 80
LightingDirectorConfig.CooldownLimit = 120
LightingDirectorConfig.DefaultCooldownSeconds = 10
LightingDirectorConfig.MinCooldownSeconds = 3
LightingDirectorConfig.MaxCooldownSeconds = 120
LightingDirectorConfig.MaxObservationPressureDelta = 0.12
LightingDirectorConfig.SelfCheckZoneId = "lighting-self-check"

LightingDirectorConfig.PressureThresholds = {
	Release = -0.2,
	Watchful = 0.2,
	Uneasy = 0.45,
	Oppressive = 0.75,
}

LightingDirectorConfig.Requests = {
	{
		id = "lighting.dim.subtle",
		requestKind = "Dim",
		displayName = "Subtle Dimming",
		intensity = 0.35,
		requiresKnownZone = false,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = true,
		supportsChase = true,
		cooldownSeconds = 8,
		tags = { "subtle", "interior" },
		description = "Approves future mild visibility pressure within World policy.",
	},
	{
		id = "lighting.flicker.brief",
		requestKind = "Flicker",
		displayName = "Brief Flicker",
		intensity = 0.45,
		requiresKnownZone = true,
		requiresFlickerPolicy = true,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = true,
		supportsChase = true,
		cooldownSeconds = 14,
		tags = { "flicker", "pressure" },
		description = "Approves future short flicker when World policy allows flicker.",
	},
	{
		id = "lighting.shadow.pressure",
		requestKind = "ShadowPressure",
		displayName = "Shadow Pressure",
		intensity = 0.6,
		requiresKnownZone = true,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = true,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		supportsChase = true,
		cooldownSeconds = 24,
		tags = { "shadow", "major" },
		description = "Approves future shadow pressure without physical mutation.",
	},
	{
		id = "lighting.visibility.pressure",
		requestKind = "VisibilityPressure",
		displayName = "Visibility Pressure",
		intensity = 0.55,
		requiresKnownZone = true,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = true,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		supportsChase = true,
		cooldownSeconds = 20,
		tags = { "visibility", "major" },
		description = "Approves future visibility pressure without blackout.",
	},
	{
		id = "lighting.safe.protection",
		requestKind = "SafeRoomProtection",
		displayName = "Safe-Room Lighting Protection",
		intensity = 0.1,
		requiresKnownZone = false,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		supportsChase = false,
		cooldownSeconds = 4,
		tags = { "safe", "protection" },
		description = "Approves future protective lighting in safe spaces.",
	},
	{
		id = "lighting.puzzle.protection",
		requestKind = "PuzzleRoomProtection",
		displayName = "Puzzle Lighting Protection",
		intensity = 0.1,
		requiresKnownZone = false,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		supportsChase = false,
		cooldownSeconds = 4,
		tags = { "puzzle", "protection" },
		description = "Approves future readable lighting while puzzle focus is protected.",
	},
	{
		id = "lighting.visibility.chase",
		requestKind = "ChaseSupport",
		displayName = "Chase Visibility Support",
		intensity = 0.5,
		requiresKnownZone = true,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		supportsChase = true,
		cooldownSeconds = 12,
		tags = { "chase", "support" },
		description = "Approves future readable chase visibility support.",
	},
	{
		id = "lighting.release.soft",
		requestKind = "ReleaseLighting",
		displayName = "Release Lighting",
		intensity = 0.2,
		requiresKnownZone = false,
		requiresFlickerPolicy = false,
		requiresBlackoutPolicy = false,
		majorPressure = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		supportsChase = false,
		cooldownSeconds = 6,
		tags = { "release", "safe" },
		description = "Approves future pressure release lighting.",
	},
}

return LightingDirectorConfig
