--!strict

local Types = {}

Types.Mode = "ServerAuthoritativeAssetExecutionAdapterRegistrationWorkflowMetadataRuntime"
Types.RuntimeProviderName = "assetExecutionAdapterRegistrationWorkflow"
Types.SnapshotKind = "assetExecutionAdapterRegistrationWorkflowSnapshot"
Types.RuntimeName = "AssetExecutionAdapterRegistrationWorkflow"
Types.CoordinatorName = "AssetExecutionAdapterRegistrationWorkflowCoordinator"

Types.CoordinatorApiOrder = {
	"initialize",
	"start",
	"shutdown",
	"registerExecutionAdapterRegistrationWorkflow",
	"registerExecutionAdapterRegistrationStage",
	"registerExecutionAdapterRegistrationTransition",
	"registerExecutionAdapterRegistrationDecision",
	"registerExecutionAdapterRegistrationAudit",
	"registerExecutionAdapterRegistrationWorkflowSnapshot",
	"inspect",
	"getSnapshot",
	"validate",
	"runSelfChecks",
}

Types.SignalNames = {
	Initialized = "AssetExecutionAdapterRegistrationWorkflow.Initialized",
	Started = "AssetExecutionAdapterRegistrationWorkflow.Started",
	Shutdown = "AssetExecutionAdapterRegistrationWorkflow.Shutdown",
	ValidationFailed = "AssetExecutionAdapterRegistrationWorkflow.ValidationFailed",
}

Types.SchemaType = {
	ExecutionAdapterRegistrationWorkflow = "ExecutionAdapterRegistrationWorkflow",
	ExecutionAdapterRegistrationStage = "ExecutionAdapterRegistrationStage",
	ExecutionAdapterRegistrationTransition = "ExecutionAdapterRegistrationTransition",
	ExecutionAdapterRegistrationDecision = "ExecutionAdapterRegistrationDecision",
	ExecutionAdapterRegistrationAudit = "ExecutionAdapterRegistrationAudit",
	ExecutionAdapterRegistrationWorkflowSnapshot = "ExecutionAdapterRegistrationWorkflowSnapshot",
}

Types.SchemaFields = {
	ExecutionAdapterRegistrationWorkflow = {
		"workflowId",
		"registryId",
		"workflowName",
		"providerName",
		"snapshotProviderName",
		"workflowKind",
		"workflowStatus",
		"stageIds",
		"transitionIds",
		"decisionIds",
		"auditIds",
		"snapshotIds",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAdapterRegistrationStage = {
		"stageId",
		"workflowId",
		"stageName",
		"stageKind",
		"stageStatus",
		"stageOrder",
		"owner",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAdapterRegistrationTransition = {
		"transitionId",
		"workflowId",
		"fromStageId",
		"toStageId",
		"transitionKind",
		"transitionStatus",
		"decisionIds",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAdapterRegistrationDecision = {
		"decisionId",
		"workflowId",
		"transitionId",
		"decisionKind",
		"decisionStatus",
		"reviewer",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAdapterRegistrationAudit = {
		"auditId",
		"workflowId",
		"stageIds",
		"transitionIds",
		"decisionIds",
		"auditKind",
		"auditStatus",
		"reviewer",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAdapterRegistrationWorkflowSnapshot = {
		"workflowSnapshotId",
		"workflowId",
		"snapshotKind",
		"snapshotStatus",
		"providerName",
		"stageIds",
		"transitionIds",
		"decisionIds",
		"evidence",
		"tags",
		"metadata",
	},
}

Types.SchemaFieldCount = {}
for schemaName, fields in pairs(Types.SchemaFields) do
	Types.SchemaFieldCount[schemaName] = #fields
end

Types.WorkflowKind = {
	AdapterRegistrationWorkflow = true,
	CertificationWorkflow = true,
	BoundaryWorkflow = true,
	CompatibilityWorkflow = true,
}

Types.WorkflowStatus = {
	Declared = true,
	Draft = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.StageKind = {
	Intake = true,
	Validation = true,
	BoundaryReview = true,
	CompatibilityReview = true,
	Certification = true,
	Audit = true,
}

Types.StageStatus = {
	Declared = true,
	Ready = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.TransitionKind = {
	StageProgression = true,
	ValidationGate = true,
	BoundaryGate = true,
	CompatibilityGate = true,
	CertificationGate = true,
}

Types.TransitionStatus = {
	Declared = true,
	Ready = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.DecisionKind = {
	ValidationDecision = true,
	BoundaryDecision = true,
	CompatibilityDecision = true,
	CertificationDecision = true,
	AuditDecision = true,
}

Types.DecisionStatus = {
	Declared = true,
	Satisfied = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AuditKind = {
	WorkflowAudit = true,
	StageAudit = true,
	TransitionAudit = true,
	DecisionAudit = true,
	ProductionAudit = true,
}

Types.AuditStatus = {
	Passed = true,
	Failed = true,
	Warning = true,
	Deferred = true,
	Blocked = true,
}

Types.WorkflowSnapshotStatus = {
	Declared = true,
	Captured = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.ProcessingReadinessKind = {
	Compatibility = true,
	Requirement = true,
	Evidence = true,
	Boundary = true,
	Absence = true,
	Separation = true,
	Certification = true,
}

Types.ProcessingReadinessStatus = {
	Declared = true,
	Ready = true,
	Certified = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.ProcessingInputKind = {
	WorkflowMetadata = true,
	WorkflowSnapshotMetadata = true,
	RegistryMetadata = true,
	GovernanceMetadata = true,
	DocumentationMetadata = true,
	NoLiveInput = true,
	None = true,
}

Types.ProcessingOutputKind = {
	ReadinessEvidence = true,
	NoRuntimeOutput = true,
	NoRegistryWrites = true,
	DiagnosticsMetadata = true,
	SnapshotMetadata = true,
	None = true,
}

Types.ProcessingDependencyKind = {
	WorkflowRuntime = true,
	AdapterRegistry = true,
	AssetExecutionGovernance = true,
	AssetExecutionAuthorization = true,
	AssetExecutionRuntime = true,
	Documentation = true,
	None = true,
}

Types.ProcessingPreconditionKind = {
	WorkflowCertified = true,
	RegistryCertified = true,
	GovernanceCertified = true,
	AuthorizationSeparated = true,
	ExecutionSeparated = true,
	NoLiveProcessing = true,
	None = true,
}

Types.ProcessingPostconditionKind = {
	EvidenceRecorded = true,
	NoStateTransition = true,
	NoRegistryWrites = true,
	NoAdapterChange = true,
	NoExecution = true,
	NoGameplay = true,
	None = true,
}

Types.ProcessingBoundaryKind = {
	Compatibility = true,
	InputOutput = true,
	Dependency = true,
	Validation = true,
	Failure = true,
	Audit = true,
	Lifecycle = true,
	Authority = true,
	Mutation = true,
	Isolation = true,
	Serialization = true,
	Diagnostics = true,
	Snapshot = true,
	RuntimeLimit = true,
	Documentation = true,
	Bootstrap = true,
	Governance = true,
	FutureAbsence = true,
	ExecutionSeparation = true,
	Certification = true,
}

Types.ProcessingReadinessDeclarationFields = {
	"declarationId",
	"declarationKind",
	"readinessStatus",
	"inputKind",
	"outputKind",
	"dependencyKind",
	"preconditionKind",
	"postconditionKind",
	"boundaryKind",
	"evidence",
	"tags",
	"metadata",
}

Types.ProcessingReadinessDeclarationOrder = {
	"workflow.compatibility",
	"workflow.snapshotCompatibility",
	"workflow.providerCompatibility",
	"workflow.coordinatorCompatibility",
	"registry.compatibility",
	"registry.providerCompatibility",
	"input.requirements",
	"output.requirements",
	"dependency.requirements",
	"precondition.requirements",
	"postcondition.requirements",
	"validation.evidence",
	"failure.evidence",
	"audit.requirements",
	"lifecycle.boundary",
	"authority.boundary",
	"mutation.boundary",
	"isolation.requirements",
	"serialization.requirements",
	"diagnostics.requirements",
	"snapshot.requirements",
	"runtimeLimit.requirements",
	"documentation.requirements",
	"bootstrap.compatibility",
	"governance.compatibility",
	"futureProcessor.absence",
	"futureProcessingProvider.absence",
	"futureProcessingCoordinator.absence",
	"futureProcessingModule.absence",
	"futureProcessingCallback.absence",
	"futureProcessingListener.absence",
	"futureProcessingService.absence",
	"futureProcessingManager.absence",
	"futureProcessingWorker.absence",
	"futureProcessingJob.absence",
	"futureProcessingQueue.absence",
	"workflowExecution.separation",
	"stageAdvancement.separation",
	"transitionExecution.separation",
	"decisionExecution.separation",
	"registryWrite.separation",
	"registrationRun.separation",
	"adapterRegistration.separation",
	"adapterActivation.separation",
	"adapterExecution.separation",
	"routingDispatchQueueSchedulerOrchestration.separation",
	"assetOperation.separation",
	"networkingPersistenceObservability.separation",
	"gameplayPresentationSaveChapter.separation",
	"futureCertification.requirements",
}

local function processingReadinessDeclaration(
	declarationId: string,
	declarationKind: string,
	readinessStatus: string,
	inputKind: string,
	outputKind: string,
	dependencyKind: string,
	preconditionKind: string,
	postconditionKind: string,
	boundaryKind: string,
	evidence: { string },
	tags: { string },
	metadata: { [string]: any }
)
	return {
		declarationId = declarationId,
		declarationKind = declarationKind,
		readinessStatus = readinessStatus,
		inputKind = inputKind,
		outputKind = outputKind,
		dependencyKind = dependencyKind,
		preconditionKind = preconditionKind,
		postconditionKind = postconditionKind,
		boundaryKind = boundaryKind,
		evidence = evidence,
		tags = tags,
		metadata = metadata,
	}
end

Types.ProcessingReadinessDeclarations = {
	processingReadinessDeclaration(
		"workflow.compatibility",
		"Compatibility",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Compatibility",
		{ "workflow.schema.compatible" },
		{ "workflow", "compatibility" },
		{ verifies = "workflow schema compatibility only" }
	),
	processingReadinessDeclaration(
		"workflow.snapshotCompatibility",
		"Compatibility",
		"Certified",
		"WorkflowSnapshotMetadata",
		"SnapshotMetadata",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Snapshot",
		{ "workflow.snapshot.compatible" },
		{ "workflowSnapshot", "compatibility" },
		{ verifies = "snapshot metadata compatibility only" }
	),
	processingReadinessDeclaration(
		"workflow.providerCompatibility",
		"Compatibility",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Compatibility",
		{ "workflow.provider.compatible" },
		{ "provider", "compatibility" },
		{ providerName = "assetExecutionAdapterRegistrationWorkflow" }
	),
	processingReadinessDeclaration(
		"workflow.coordinatorCompatibility",
		"Compatibility",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Compatibility",
		{ "workflow.coordinator.compatible" },
		{ "coordinator", "compatibility" },
		{ coordinatorName = "AssetExecutionAdapterRegistrationWorkflowCoordinator" }
	),
	processingReadinessDeclaration(
		"registry.compatibility",
		"Compatibility",
		"Certified",
		"RegistryMetadata",
		"ReadinessEvidence",
		"AdapterRegistry",
		"RegistryCertified",
		"EvidenceRecorded",
		"Compatibility",
		{ "registry.compatible" },
		{ "registry", "compatibility" },
		{ verifies = "adapter registry metadata compatibility only" }
	),
	processingReadinessDeclaration(
		"registry.providerCompatibility",
		"Compatibility",
		"Certified",
		"RegistryMetadata",
		"ReadinessEvidence",
		"AdapterRegistry",
		"RegistryCertified",
		"EvidenceRecorded",
		"Compatibility",
		{ "registry.provider.compatible" },
		{ "registryProvider", "compatibility" },
		{ providerName = "assetExecutionAdapterRegistry" }
	),
	processingReadinessDeclaration(
		"input.requirements",
		"Requirement",
		"Ready",
		"NoLiveInput",
		"ReadinessEvidence",
		"None",
		"NoLiveProcessing",
		"EvidenceRecorded",
		"InputOutput",
		{ "input.requirements.declared" },
		{ "input", "requirements" },
		{ requiresLiveInput = false }
	),
	processingReadinessDeclaration(
		"output.requirements",
		"Requirement",
		"Ready",
		"None",
		"NoRuntimeOutput",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"InputOutput",
		{ "output.requirements.declared" },
		{ "output", "requirements" },
		{ createsRuntimeOutput = false }
	),
	processingReadinessDeclaration(
		"dependency.requirements",
		"Requirement",
		"Ready",
		"GovernanceMetadata",
		"ReadinessEvidence",
		"AssetExecutionGovernance",
		"GovernanceCertified",
		"EvidenceRecorded",
		"Dependency",
		{ "dependency.requirements.declared" },
		{ "dependency", "requirements" },
		{ dependenciesAreMetadataOnly = true }
	),
	processingReadinessDeclaration(
		"precondition.requirements",
		"Requirement",
		"Ready",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Validation",
		{ "precondition.requirements.declared" },
		{ "precondition", "requirements" },
		{ preconditionsAreDeclarative = true }
	),
	processingReadinessDeclaration(
		"postcondition.requirements",
		"Requirement",
		"Ready",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"NoStateTransition",
		"Validation",
		{ "postcondition.requirements.declared" },
		{ "postcondition", "requirements" },
		{ postconditionsAreDeclarative = true }
	),
	processingReadinessDeclaration(
		"validation.evidence",
		"Evidence",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Validation",
		{ "validation.evidence.certified" },
		{ "validation", "evidence" },
		{ validationBeforeMutation = true }
	),
	processingReadinessDeclaration(
		"failure.evidence",
		"Evidence",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"NoStateTransition",
		"Failure",
		{ "failure.evidence.certified" },
		{ "failure", "evidence" },
		{ failedValidationMutates = false }
	),
	processingReadinessDeclaration(
		"audit.requirements",
		"Requirement",
		"Ready",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"Documentation",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Audit",
		{ "audit.requirements.declared" },
		{ "audit", "requirements" },
		{ auditMetadataOnly = true }
	),
	processingReadinessDeclaration(
		"lifecycle.boundary",
		"Boundary",
		"Certified",
		"None",
		"None",
		"WorkflowRuntime",
		"WorkflowCertified",
		"NoExecution",
		"Lifecycle",
		{ "lifecycle.boundary.certified" },
		{ "lifecycle", "boundary" },
		{ noNewLifecycle = true }
	),
	processingReadinessDeclaration(
		"authority.boundary",
		"Boundary",
		"Certified",
		"None",
		"None",
		"WorkflowRuntime",
		"AuthorizationSeparated",
		"NoExecution",
		"Authority",
		{ "authority.boundary.certified" },
		{ "authority", "boundary" },
		{ grantsAuthority = false }
	),
	processingReadinessDeclaration(
		"mutation.boundary",
		"Boundary",
		"Certified",
		"None",
		"NoRegistryWrites",
		"AdapterRegistry",
		"RegistryCertified",
		"NoRegistryWrites",
		"Mutation",
		{ "mutation.boundary.certified" },
		{ "mutation", "boundary" },
		{ writesRegistry = false }
	),
	processingReadinessDeclaration(
		"isolation.requirements",
		"Requirement",
		"Certified",
		"WorkflowMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Isolation",
		{ "isolation.requirements.certified" },
		{ "isolation", "requirements" },
		{ deepCopiesRequired = true }
	),
	processingReadinessDeclaration(
		"serialization.requirements",
		"Requirement",
		"Certified",
		"DocumentationMetadata",
		"ReadinessEvidence",
		"Documentation",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Serialization",
		{ "serialization.requirements.certified" },
		{ "serialization", "requirements" },
		{ safePayloadsOnly = true }
	),
	processingReadinessDeclaration(
		"diagnostics.requirements",
		"Requirement",
		"Certified",
		"DocumentationMetadata",
		"DiagnosticsMetadata",
		"Documentation",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Diagnostics",
		{ "diagnostics.requirements.certified" },
		{ "diagnostics", "requirements" },
		{ healthOnly = true }
	),
	processingReadinessDeclaration(
		"snapshot.requirements",
		"Requirement",
		"Certified",
		"DocumentationMetadata",
		"SnapshotMetadata",
		"Documentation",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Snapshot",
		{ "snapshot.requirements.certified" },
		{ "snapshot", "requirements" },
		{ isolatedCopies = true }
	),
	processingReadinessDeclaration(
		"runtimeLimit.requirements",
		"Requirement",
		"Certified",
		"DocumentationMetadata",
		"ReadinessEvidence",
		"WorkflowRuntime",
		"WorkflowCertified",
		"EvidenceRecorded",
		"RuntimeLimit",
		{ "runtimeLimit.requirements.certified" },
		{ "runtimeLimit", "requirements" },
		{ limitName = "MaxProcessingReadinessDeclarations" }
	),
	processingReadinessDeclaration(
		"documentation.requirements",
		"Requirement",
		"Ready",
		"DocumentationMetadata",
		"ReadinessEvidence",
		"Documentation",
		"WorkflowCertified",
		"EvidenceRecorded",
		"Documentation",
		{ "documentation.requirements.declared" },
		{ "documentation", "requirements" },
		{ docsMirrorRuntime = true }
	),
	processingReadinessDeclaration(
		"bootstrap.compatibility",
		"Compatibility",
		"Certified",
		"GovernanceMetadata",
		"ReadinessEvidence",
		"AssetExecutionGovernance",
		"GovernanceCertified",
		"EvidenceRecorded",
		"Bootstrap",
		{ "bootstrap.compatibility.certified" },
		{ "bootstrap", "compatibility" },
		{ predecessor = "AssetExecutionAdapterRegistryCoordinator" }
	),
	processingReadinessDeclaration(
		"governance.compatibility",
		"Compatibility",
		"Certified",
		"GovernanceMetadata",
		"ReadinessEvidence",
		"AssetExecutionGovernance",
		"GovernanceCertified",
		"EvidenceRecorded",
		"Governance",
		{ "governance.compatibility.certified" },
		{ "governance", "compatibility" },
		{ snapshotProvider = "assetExecutionAdapterRegistrationWorkflow" }
	),
	processingReadinessDeclaration(
		"futureProcessor.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureProcessor.absence.certified" },
		{ "futureProcessor", "absence" },
		{ futureProcessorPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingProvider.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureProvider.absence.certified" },
		{ "futureProvider", "absence" },
		{ futureProviderPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingCoordinator.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureCoordinator.absence.certified" },
		{ "futureCoordinator", "absence" },
		{ futureCoordinatorPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingModule.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureModule.absence.certified" },
		{ "futureModule", "absence" },
		{ futureModulePresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingCallback.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureCallback.absence.certified" },
		{ "futureCallback", "absence" },
		{ futureCallbackPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingListener.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureListener.absence.certified" },
		{ "futureListener", "absence" },
		{ futureListenerPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingService.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureService.absence.certified" },
		{ "futureService", "absence" },
		{ futureServicePresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingManager.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureManager.absence.certified" },
		{ "futureManager", "absence" },
		{ futureManagerPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingWorker.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureWorker.absence.certified" },
		{ "futureWorker", "absence" },
		{ futureWorkerPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingJob.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureJob.absence.certified" },
		{ "futureJob", "absence" },
		{ futureJobPresent = false }
	),
	processingReadinessDeclaration(
		"futureProcessingQueue.absence",
		"Absence",
		"Certified",
		"None",
		"None",
		"None",
		"NoLiveProcessing",
		"NoExecution",
		"FutureAbsence",
		{ "futureQueue.absence.certified" },
		{ "futureQueue", "absence" },
		{ futureQueuePresent = false }
	),
	processingReadinessDeclaration(
		"workflowExecution.separation",
		"Separation",
		"Certified",
		"WorkflowMetadata",
		"NoRuntimeOutput",
		"WorkflowRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "workflowExecution.separation.certified" },
		{ "workflowExecution", "separation" },
		{ workflowRunnerPresent = false }
	),
	processingReadinessDeclaration(
		"stageAdvancement.separation",
		"Separation",
		"Certified",
		"WorkflowMetadata",
		"NoRuntimeOutput",
		"WorkflowRuntime",
		"ExecutionSeparated",
		"NoStateTransition",
		"ExecutionSeparation",
		{ "stageAdvancement.separation.certified" },
		{ "stageAdvancement", "separation" },
		{ stageAdvancerPresent = false }
	),
	processingReadinessDeclaration(
		"transitionExecution.separation",
		"Separation",
		"Certified",
		"WorkflowMetadata",
		"NoRuntimeOutput",
		"WorkflowRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "transitionExecution.separation.certified" },
		{ "transitionExecution", "separation" },
		{ transitionRunnerPresent = false }
	),
	processingReadinessDeclaration(
		"decisionExecution.separation",
		"Separation",
		"Certified",
		"WorkflowMetadata",
		"NoRuntimeOutput",
		"WorkflowRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "decisionExecution.separation.certified" },
		{ "decisionExecution", "separation" },
		{ decisionRunnerPresent = false }
	),
	processingReadinessDeclaration(
		"registryWrite.separation",
		"Separation",
		"Certified",
		"RegistryMetadata",
		"NoRegistryWrites",
		"AdapterRegistry",
		"RegistryCertified",
		"NoRegistryWrites",
		"Mutation",
		{ "registryWrite.separation.certified" },
		{ "registryWrite", "separation" },
		{ registryWriterPresent = false }
	),
	processingReadinessDeclaration(
		"registrationRun.separation",
		"Separation",
		"Certified",
		"WorkflowMetadata",
		"NoRuntimeOutput",
		"WorkflowRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "registrationRun.separation.certified" },
		{ "registrationRun", "separation" },
		{ registrationRunnerPresent = false }
	),
	processingReadinessDeclaration(
		"adapterRegistration.separation",
		"Separation",
		"Certified",
		"RegistryMetadata",
		"NoRegistryWrites",
		"AdapterRegistry",
		"RegistryCertified",
		"NoAdapterChange",
		"ExecutionSeparation",
		{ "adapterRegistration.separation.certified" },
		{ "adapterRegistration", "separation" },
		{ changesAdapters = false }
	),
	processingReadinessDeclaration(
		"adapterActivation.separation",
		"Separation",
		"Certified",
		"RegistryMetadata",
		"NoRuntimeOutput",
		"AssetExecutionAuthorization",
		"AuthorizationSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "adapterActivation.separation.certified" },
		{ "adapterActivation", "separation" },
		{ activatesAdapters = false }
	),
	processingReadinessDeclaration(
		"adapterExecution.separation",
		"Separation",
		"Certified",
		"RegistryMetadata",
		"NoRuntimeOutput",
		"AssetExecutionRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "adapterExecution.separation.certified" },
		{ "adapterExecution", "separation" },
		{ runsAdapters = false }
	),
	processingReadinessDeclaration(
		"routingDispatchQueueSchedulerOrchestration.separation",
		"Separation",
		"Certified",
		"None",
		"NoRuntimeOutput",
		"None",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "routingDispatchQueueSchedulerOrchestration.separation.certified" },
		{ "routingDispatchQueueSchedulerOrchestration", "separation" },
		{ runtimeTrafficPresent = false }
	),
	processingReadinessDeclaration(
		"assetOperation.separation",
		"Separation",
		"Certified",
		"None",
		"NoRuntimeOutput",
		"AssetExecutionRuntime",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "assetOperation.separation.certified" },
		{ "assetOperation", "separation" },
		{ assetOperationsPresent = false }
	),
	processingReadinessDeclaration(
		"networkingPersistenceObservability.separation",
		"Separation",
		"Certified",
		"None",
		"NoRuntimeOutput",
		"None",
		"ExecutionSeparated",
		"NoExecution",
		"ExecutionSeparation",
		{ "networkingPersistenceObservability.separation.certified" },
		{ "networkingPersistenceObservability", "separation" },
		{ liveExternalSideEffects = false }
	),
	processingReadinessDeclaration(
		"gameplayPresentationSaveChapter.separation",
		"Separation",
		"Certified",
		"None",
		"NoRuntimeOutput",
		"None",
		"ExecutionSeparated",
		"NoGameplay",
		"ExecutionSeparation",
		{ "gameplayPresentationSaveChapter.separation.certified" },
		{ "gameplayPresentationSaveChapter", "separation" },
		{ gameplaySurfacesPresent = false }
	),
	processingReadinessDeclaration(
		"futureCertification.requirements",
		"Certification",
		"Ready",
		"GovernanceMetadata",
		"ReadinessEvidence",
		"AssetExecutionGovernance",
		"GovernanceCertified",
		"EvidenceRecorded",
		"Certification",
		{ "futureCertification.requirements.declared" },
		{ "futureCertification", "requirements" },
		{ phase = 107 }
	),
}

Types.PostureKeys = {
	"assetExecutionAdapterRegistrationWorkflowRuntimePosture",
	"assetExecutionAdapterRegistrationWorkflowWorkflowPosture",
	"assetExecutionAdapterRegistrationWorkflowRegistrationPosture",
	"assetExecutionAdapterRegistrationWorkflowTransitionPosture",
	"assetExecutionAdapterRegistrationWorkflowDecisionPosture",
	"assetExecutionAdapterRegistrationWorkflowAuditPosture",
	"assetExecutionAdapterRegistrationWorkflowSnapshotPosture",
	"assetExecutionAdapterRegistrationWorkflowValidationPosture",
	"assetExecutionAdapterRegistrationWorkflowDocumentationPosture",
	"assetExecutionAdapterRegistrationWorkflowBootstrapPosture",
	"assetExecutionAdapterRegistrationWorkflowGovernancePosture",
	"assetExecutionAdapterRegistrationWorkflowCertificationPosture",
	"assetExecutionAdapterRegistrationWorkflowHardeningPosture",
	"assetExecutionAdapterRegistrationWorkflowIdentityPosture",
	"assetExecutionAdapterRegistrationWorkflowOrderingPosture",
	"assetExecutionAdapterRegistrationWorkflowMetadataPosture",
	"assetExecutionAdapterRegistrationWorkflowEvidencePosture",
	"assetExecutionAdapterRegistrationWorkflowTagPosture",
	"assetExecutionAdapterRegistrationWorkflowRuntimeLimitPosture",
	"assetExecutionAdapterRegistrationWorkflowNoImplementationPosture",
	"assetExecutionAdapterRegistrationWorkflowNoActivationPosture",
	"assetExecutionAdapterRegistrationWorkflowNoExecutionPosture",
	"assetExecutionAdapterRegistrationWorkflowNoAuthorizationPosture",
	"assetExecutionAdapterRegistrationWorkflowNoWorkflowExecutionPosture",
	"assetExecutionAdapterRegistrationWorkflowNoOperationPosture",
	"assetExecutionAdapterRegistrationWorkflowNoAuthorityPosture",
	"assetExecutionAdapterRegistrationWorkflowProcessingReadinessPosture",
	"assetExecutionAdapterRegistrationWorkflowProcessingDeclarationPosture",
	"assetExecutionAdapterRegistrationWorkflowProcessorAbsencePosture",
	"assetExecutionAdapterRegistrationWorkflowRegistryWriteSeparationPosture",
	"assetExecutionAdapterRegistrationWorkflowProcessingSeparationPosture",
	"noExecution",
	"noAssetLoading",
	"noGameplay",
	"noPresentation",
	"noSave",
	"noNetworking",
	"noAnalytics",
	"noTelemetry",
}

Types.DocumentationFiles = {
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_RUNTIME.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_VALIDATION.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_SERIALIZATION.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_DIAGNOSTICS.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_SNAPSHOTS.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_SELF_CHECKS.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_AUDIT.md",
	"ASSET_EXECUTION_ADAPTER_REGISTRATION_WORKFLOW_PRODUCTION_REVIEW.md",
}

Types.BootstrapDependencyOrder = {
	"AssetExecutionAdapterRegistryCoordinator",
}

Types.GovernanceSnapshotProviders = {
	"assetExecutionAdapterRegistrationWorkflow",
}

Types.Limits = {
	MaxWorkflows = 32,
	MaxStages = 180,
	MaxTransitions = 220,
	MaxDecisions = 220,
	MaxAudits = 220,
	MaxWorkflowSnapshots = 120,
	MaxValidationFailures = 220,
	MaxSnapshotHistory = 60,
	MaxPayloadDepth = 8,
	MaxPayloadNodes = 520,
	MaxStringLength = 280,
	MaxTags = 32,
	MaxEvidence = 56,
	MaxChildReferences = 220,
	MaxStageOrder = 1000,
	MaxProcessingReadinessDeclarations = 50,
}

return Types
