--!strict

local Types = {}

Types.Mode = "ServerAuthoritativeAssetExecutionMetadataRuntime"
Types.RuntimeProviderName = "assetExecutionRuntime"
Types.SnapshotKind = "assetExecutionRuntimeSnapshot"
Types.RuntimeName = "AssetExecutionRuntime"
Types.CoordinatorName = "AssetExecutionCoordinator"

Types.CoordinatorApiOrder = {
	"initialize",
	"start",
	"shutdown",
	"registerExecutionRuntime",
	"registerExecutionRequest",
	"registerExecutionBoundary",
	"registerExecutionAudit",
	"inspect",
	"getSnapshot",
	"validate",
	"runSelfChecks",
}

Types.SignalNames = {
	Initialized = "AssetExecutionRuntime.Initialized",
	Started = "AssetExecutionRuntime.Started",
	Shutdown = "AssetExecutionRuntime.Shutdown",
	ValidationFailed = "AssetExecutionRuntime.ValidationFailed",
}

Types.SchemaType = {
	ExecutionRuntime = "ExecutionRuntime",
	ExecutionRequest = "ExecutionRequest",
	ExecutionBoundary = "ExecutionBoundary",
	ExecutionAudit = "ExecutionAudit",
}

Types.SchemaFields = {
	ExecutionRuntime = {
		"runtimeId",
		"authorizationId",
		"readinessId",
		"runtimeKind",
		"runtimeStatus",
		"providerName",
		"snapshotProviderName",
		"requestIds",
		"boundaryIds",
		"auditIds",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionRequest = {
		"requestId",
		"runtimeId",
		"requestKind",
		"requestStatus",
		"requestedBy",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionBoundary = {
		"boundaryId",
		"runtimeId",
		"boundaryKind",
		"boundaryStatus",
		"summary",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAudit = {
		"auditId",
		"runtimeId",
		"requestIds",
		"boundaryIds",
		"auditKind",
		"auditStatus",
		"reviewer",
		"evidence",
		"tags",
		"metadata",
	},
}

Types.SchemaFieldCount = {}
for schemaName, fields in pairs(Types.SchemaFields) do
	Types.SchemaFieldCount[schemaName] = #fields
end

Types.IntegrationReadinessDeclarationFields = {
	"integrationId",
	"compatibilityId",
	"integrationDeclarationId",
	"integrationKind",
	"integrationStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"engineGovernanceSnapshotProviderName",
	"documentationReference",
	"authorizationRuntimeName",
	"authorizationProviderName",
	"authorizationSnapshotProviderName",
	"readinessEvidenceKind",
	"executionRuntimeName",
	"executionProviderName",
	"executionSnapshotProviderName",
	"executionCoordinatorName",
	"adapterBoundaryKind",
	"assetOperationBoundaryKind",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.AdapterReadinessDeclarationFields = {
	"readinessId",
	"compatibilityId",
	"adapterReadinessDeclarationId",
	"readinessKind",
	"readinessStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"engineGovernanceSnapshotProviderName",
	"documentationReference",
	"executionRuntimeName",
	"executionProviderName",
	"executionSnapshotProviderName",
	"executionCoordinatorName",
	"futureAdapterRuntimeName",
	"futureAdapterProviderName",
	"futureAdapterSnapshotProviderName",
	"futureAdapterCoordinatorName",
	"adapterKind",
	"adapterAuthorityKind",
	"adapterBoundaryKind",
	"assetOperationBoundaryKind",
	"lifecycleBoundaryKind",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.AdapterContractDeclarationFields = {
	"adapterContractId",
	"compatibilityId",
	"contractDeclarationId",
	"contractKind",
	"contractStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"governanceProviderName",
	"executionRuntimeName",
	"executionProviderName",
	"executionCoordinatorName",
	"adapterRuntimeName",
	"adapterProviderName",
	"adapterCoordinatorName",
	"adapterSnapshotProviderName",
	"adapterContractBoundary",
	"lifecycleBoundary",
	"serializationBoundary",
	"validationBoundary",
	"authorityBoundary",
	"operationBoundary",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.RuntimeKind = {
	MetadataRuntime = true,
	RequestRuntime = true,
	BoundaryRuntime = true,
	AuditRuntime = true,
	FuturePipelineRuntime = true,
}

Types.RuntimeStatus = {
	Declared = true,
	Ready = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.RequestKind = {
	RuntimeMetadataRequest = true,
	ReadinessMetadataRequest = true,
	BoundaryMetadataRequest = true,
	AuditMetadataRequest = true,
	FuturePipelineRequest = true,
}

Types.RequestStatus = {
	Declared = true,
	Validated = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.BoundaryKind = {
	NoAssetLoading = true,
	NoAssetStreaming = true,
	NoAssetSpawning = true,
	NoAssetApplication = true,
	NoAssetPlayback = true,
	NoPresentation = true,
	NoSave = true,
	NoGameplay = true,
	NoNetworking = true,
	NoWorldMutation = true,
	NoPersistence = true,
	NoRouting = true,
	NoDispatch = true,
	NoQueueing = true,
	NoScheduling = true,
	NoOrchestration = true,
}

Types.BoundaryStatus = {
	Declared = true,
	Satisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AuditKind = {
	RuntimeAudit = true,
	RequestAudit = true,
	BoundaryAudit = true,
	ProductionAudit = true,
}

Types.AuditStatus = {
	Passed = true,
	Failed = true,
	Warning = true,
	Deferred = true,
	Blocked = true,
}

Types.IntegrationKind = {
	AuthorizationRuntimeCompatibility = true,
	AuthorizationProviderCompatibility = true,
	AuthorizationSnapshotCompatibility = true,
	ExecutionReadinessCompatibility = true,
	ExecutionRuntimeCompatibility = true,
	ExecutionProviderCompatibility = true,
	ExecutionSnapshotCompatibility = true,
	ExecutionCoordinatorCompatibility = true,
	BootstrapCompatibility = true,
	EngineGovernanceCompatibility = true,
	DocumentationCompatibility = true,
	SchemaCompatibility = true,
	EnumCompatibility = true,
	ReferenceIntegrityCompatibility = true,
	SerializationCompatibility = true,
	DiagnosticsCompatibility = true,
	SnapshotIsolationCompatibility = true,
	RuntimeLimitCompatibility = true,
	SignalBoundaryCompatibility = true,
	CoordinatorBoundaryCompatibility = true,
	LifecycleCompatibility = true,
	FutureAdapterSeparation = true,
	FutureAssetOperationSeparation = true,
	FutureGameplaySeparation = true,
}

Types.IntegrationStatus = {
	Declared = true,
	Compatible = true,
	IntegrationReady = true,
	BoundaryReady = true,
	ObservationOnly = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AdapterBoundaryKind = {
	NoExecutionAdapter = true,
	NoAssetLoaderAdapter = true,
	NoAssetSpawnAdapter = true,
	NoAssetApplicationAdapter = true,
	NoAssetPlaybackAdapter = true,
	NoRoutingAdapter = true,
	NoDispatchAdapter = true,
	NoQueueAdapter = true,
	NoSchedulerAdapter = true,
	NoOrchestrationAdapter = true,
	FutureAdapterSeparate = true,
}

Types.AssetOperationBoundaryKind = {
	NoAssetLoading = true,
	NoAssetPreloading = true,
	NoAssetStreaming = true,
	NoAssetSpawning = true,
	NoAssetCloning = true,
	NoAssetInsertion = true,
	NoAssetApplication = true,
	NoAssetDisplay = true,
	NoAssetPlayback = true,
	NoAnimationPlayback = true,
	NoAudioPlayback = true,
	NoWorldMutation = true,
	NoStorageMutation = true,
	NoNetworkOwnership = true,
	NoPhysicsExecution = true,
	NoGameplayExecution = true,
	FutureAssetOperationsSeparate = true,
	FutureGameplaySeparate = true,
}

Types.AdapterReadinessKind = {
	ExecutionRuntimeCompatibility = true,
	ExecutionProviderCompatibility = true,
	ExecutionSnapshotCompatibility = true,
	ExecutionCoordinatorCompatibility = true,
	AdapterIdentityReadiness = true,
	AdapterProviderReadiness = true,
	AdapterSnapshotReadiness = true,
	AdapterCoordinatorReadiness = true,
	AdapterSchemaReadiness = true,
	AdapterValidationReadiness = true,
	AdapterSerializationReadiness = true,
	AdapterDiagnosticsReadiness = true,
	AdapterSnapshotIsolationReadiness = true,
	AdapterLifecycleReadiness = true,
	AdapterRuntimeLimitReadiness = true,
	BootstrapReadiness = true,
	EngineGovernanceReadiness = true,
	DocumentationReadiness = true,
	ServerAuthorityReadiness = true,
	ClientAuthoritySeparation = true,
	CallbackSeparation = true,
	ListenerSeparation = true,
	ServiceReferenceSeparation = true,
	ModuleReferenceSeparation = true,
	RuntimeHandleSeparation = true,
	AssetHandleSeparation = true,
	RoutingSeparation = true,
	DispatchSeparation = true,
	QueueSeparation = true,
	SchedulerSeparation = true,
	OrchestrationSeparation = true,
	AssetLoadingSeparation = true,
	AssetSpawningSeparation = true,
	AssetApplicationSeparation = true,
	AssetDisplaySeparation = true,
	AssetPlaybackSeparation = true,
	GameplaySeparation = true,
	FutureAdapterRuntimeReadiness = true,
}

Types.AdapterReadinessStatus = {
	Declared = true,
	Compatible = true,
	ReadinessConfirmed = true,
	BoundaryConfirmed = true,
	ObservationOnly = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.FutureAdapterKind = {
	NoAdapterKind = true,
	AssetAcquisitionAdapter = true,
	AssetFormationAdapter = true,
	AssetApplicationAdapter = true,
	AssetPresentationAdapter = true,
	AudioAdapter = true,
	AnimationAdapter = true,
	WorldMutationAdapter = true,
	OperationBoundaryAdapter = true,
	GovernanceAdapter = true,
}

Types.AdapterAuthorityKind = {
	NoAuthority = true,
	MetadataOnly = true,
	ServerAuthoritativeFuture = true,
	NoClientAuthority = true,
	NoDirectExecution = true,
	FutureGovernedAuthorityRequired = true,
	FutureAuthorizationRequired = true,
	FutureRuntimePermitRequired = true,
}

Types.AdapterReadinessBoundaryKind = {
	NoLiveAdapter = true,
	NoAdapterModule = true,
	NoAdapterCallback = true,
	NoAdapterListener = true,
	NoAdapterService = true,
	NoAdapterRegistry = true,
	NoAdapterActivation = true,
	NoAdapterResolution = true,
	NoAdapterDispatch = true,
	NoAdapterQueue = true,
	FutureAdapterSeparate = true,
}

Types.AdapterAssetOperationBoundaryKind = {
	NoAssetLoading = true,
	NoAssetPreloading = true,
	NoAssetStreaming = true,
	NoAssetSpawning = true,
	NoAssetCloning = true,
	NoAssetInsertion = true,
	NoAssetApplication = true,
	NoAssetDisplay = true,
	NoAssetPlayback = true,
	NoAnimationPlayback = true,
	NoAudioPlayback = true,
	NoModelCreation = true,
	NoInterfaceSurface = true,
	NoVisualEffects = true,
	NoWorldMutation = true,
	NoStorageMutation = true,
	NoNetworkOwnership = true,
	NoPhysicsExecution = true,
	NoGameplayExecution = true,
	FutureAssetOperationsSeparate = true,
}

Types.AdapterLifecycleBoundaryKind = {
	NoAdapterInitialization = true,
	NoAdapterStart = true,
	NoAdapterActivation = true,
	NoAdapterExecution = true,
	NoAdapterShutdownOwnership = true,
	NoAdapterRecovery = true,
	FutureLifecycleSeparate = true,
}

Types.AdapterContractKind = {
	RuntimeIdentityContract = true,
	ProviderIdentityContract = true,
	SnapshotIdentityContract = true,
	CoordinatorIdentityContract = true,
	DiagnosticsContract = true,
	BootstrapContract = true,
	GovernanceContract = true,
	DocumentationContract = true,
	SerializationContract = true,
	ValidationContract = true,
	IsolationContract = true,
	LifecycleContract = true,
	AuthorityContract = true,
	OperationBoundaryContract = true,
	NoRegistryContract = true,
	NoActivationContract = true,
	NoImplementationContract = true,
	NoRoutingContract = true,
	NoDispatchContract = true,
	NoQueueContract = true,
	NoSchedulerContract = true,
	NoOrchestrationContract = true,
	NoGameplayContract = true,
	FutureImplementationContract = true,
}

Types.AdapterContractStatus = {
	Declared = true,
	ContractReady = true,
	BoundaryConfirmed = true,
	ObservationOnly = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AdapterContractBoundary = {
	MetadataOnlyContract = true,
	NoAdapterRuntime = true,
	NoAdapterProvider = true,
	NoAdapterRegistry = true,
	NoAdapterImplementation = true,
	NoAdapterActivation = true,
	NoAdapterApi = true,
	FutureAdapterSeparate = true,
}

Types.AdapterContractLifecycleBoundary = {
	NoAdapterInitialize = true,
	NoAdapterStart = true,
	NoAdapterActivate = true,
	NoAdapterExecute = true,
	NoAdapterRecover = true,
	NoAdapterShutdownOwnership = true,
	FutureLifecycleSeparate = true,
}

Types.AdapterContractSerializationBoundary = {
	CopiedMetadataOnly = true,
	NoMutableReferences = true,
	NoRuntimeHandles = true,
	NoAdapterHandles = true,
	NoUnsafePayloads = true,
	DeepCopyOnly = true,
}

Types.AdapterContractValidationBoundary = {
	ExactFields = true,
	ExactOrdering = true,
	ExactEnums = true,
	ExactIdentities = true,
	ExactEvidence = true,
	ExactTags = true,
	ExactMetadata = true,
	ValidationBeforeMutation = true,
}

Types.AdapterContractAuthorityBoundary = {
	NoAuthority = true,
	NoClientAuthority = true,
	NoExecutionPermission = true,
	NoOperationPermission = true,
	FutureGovernedAuthorityRequired = true,
	FutureAuthorizationRequired = true,
}

Types.AdapterContractOperationBoundary = {
	NoAssetLoading = true,
	NoAssetStreaming = true,
	NoAssetSpawning = true,
	NoAssetApplication = true,
	NoAssetPlayback = true,
	NoAssetOperationApi = true,
	NoRouting = true,
	NoDispatch = true,
	NoQueueing = true,
	NoScheduling = true,
	NoOrchestration = true,
	NoGameplay = true,
	NoPresentation = true,
	NoSave = true,
	NoChapter = true,
	FutureOperationSeparate = true,
}

local function orderNameForField(fieldName: string): string
	return string.upper(string.sub(fieldName, 1, 1)) .. string.sub(fieldName, 2) .. "Order"
end

local INTEGRATION_ROWS = {
	{
		"01",
		"authorization.runtime",
		"AuthorizationRuntimeCompatibility",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationRuntimeEvidence",
		"NoExecutionAdapter",
		"NoAssetLoading",
	},
	{
		"02",
		"authorization.provider",
		"AuthorizationProviderCompatibility",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationProviderEvidence",
		"NoAssetLoaderAdapter",
		"NoAssetPreloading",
	},
	{
		"03",
		"authorization.snapshot",
		"AuthorizationSnapshotCompatibility",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"AuthorizationSnapshotEvidence",
		"NoAssetSpawnAdapter",
		"NoAssetStreaming",
	},
	{
		"04",
		"execution.readiness",
		"ExecutionReadinessCompatibility",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
		"AssetExecutionReadinessEvidence",
		"NoAssetApplicationAdapter",
		"NoAssetSpawning",
	},
	{
		"05",
		"execution.runtime",
		"ExecutionRuntimeCompatibility",
		"IntegrationReady",
		"ASSET_EXECUTION_RUNTIME.md",
		"ExecutionRuntimeIdentityEvidence",
		"NoAssetPlaybackAdapter",
		"NoAssetCloning",
	},
	{
		"06",
		"execution.provider",
		"ExecutionProviderCompatibility",
		"IntegrationReady",
		"ASSET_EXECUTION_RUNTIME.md",
		"ExecutionProviderEvidence",
		"NoRoutingAdapter",
		"NoAssetInsertion",
	},
	{
		"07",
		"execution.snapshot",
		"ExecutionSnapshotCompatibility",
		"IntegrationReady",
		"ASSET_EXECUTION_DIAGNOSTICS.md",
		"ExecutionSnapshotEvidence",
		"NoDispatchAdapter",
		"NoAssetApplication",
	},
	{
		"08",
		"execution.coordinator",
		"ExecutionCoordinatorCompatibility",
		"IntegrationReady",
		"ASSET_EXECUTION_RUNTIME.md",
		"ExecutionCoordinatorEvidence",
		"NoQueueAdapter",
		"NoAssetDisplay",
	},
	{
		"09",
		"bootstrap",
		"BootstrapCompatibility",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME.md",
		"BootstrapEvidence",
		"NoSchedulerAdapter",
		"NoAssetPlayback",
	},
	{
		"10",
		"engine.governance",
		"EngineGovernanceCompatibility",
		"Compatible",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"EngineGovernanceEvidence",
		"NoOrchestrationAdapter",
		"NoAnimationPlayback",
	},
	{
		"11",
		"documentation",
		"DocumentationCompatibility",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME_INTEGRATION_READINESS.md",
		"DocumentationEvidence",
		"FutureAdapterSeparate",
		"NoAudioPlayback",
	},
	{
		"12",
		"schema",
		"SchemaCompatibility",
		"Compatible",
		"ASSET_EXECUTION_VALIDATION.md",
		"SchemaEvidence",
		"NoExecutionAdapter",
		"NoWorldMutation",
	},
	{
		"13",
		"enum",
		"EnumCompatibility",
		"Compatible",
		"ASSET_EXECUTION_VALIDATION.md",
		"EnumEvidence",
		"NoAssetLoaderAdapter",
		"NoStorageMutation",
	},
	{
		"14",
		"reference.integrity",
		"ReferenceIntegrityCompatibility",
		"Compatible",
		"ASSET_EXECUTION_AUDIT.md",
		"ReferenceIntegrityEvidence",
		"NoAssetSpawnAdapter",
		"NoNetworkOwnership",
	},
	{
		"15",
		"serialization",
		"SerializationCompatibility",
		"ObservationOnly",
		"ASSET_EXECUTION_SERIALIZATION.md",
		"SerializationEvidence",
		"NoAssetApplicationAdapter",
		"NoPhysicsExecution",
	},
	{
		"16",
		"diagnostics",
		"DiagnosticsCompatibility",
		"ObservationOnly",
		"ASSET_EXECUTION_DIAGNOSTICS.md",
		"DiagnosticsEvidence",
		"NoAssetPlaybackAdapter",
		"NoGameplayExecution",
	},
	{
		"17",
		"snapshot.isolation",
		"SnapshotIsolationCompatibility",
		"ObservationOnly",
		"ASSET_EXECUTION_DIAGNOSTICS.md",
		"SnapshotIsolationEvidence",
		"NoRoutingAdapter",
		"FutureAssetOperationsSeparate",
	},
	{
		"18",
		"runtime.limit",
		"RuntimeLimitCompatibility",
		"ObservationOnly",
		"ASSET_EXECUTION_RUNTIME_LIMITS.md",
		"RuntimeLimitEvidence",
		"NoDispatchAdapter",
		"FutureGameplaySeparate",
	},
	{
		"19",
		"signal.boundary",
		"SignalBoundaryCompatibility",
		"BoundaryReady",
		"ASSET_EXECUTION_SELF_CHECKS.md",
		"SignalBoundaryEvidence",
		"NoQueueAdapter",
		"NoAssetLoading",
	},
	{
		"20",
		"coordinator.boundary",
		"CoordinatorBoundaryCompatibility",
		"BoundaryReady",
		"ASSET_EXECUTION_SELF_CHECKS.md",
		"CoordinatorBoundaryEvidence",
		"NoSchedulerAdapter",
		"NoAssetSpawning",
	},
	{
		"21",
		"lifecycle",
		"LifecycleCompatibility",
		"ObservationOnly",
		"ASSET_EXECUTION_SELF_CHECKS.md",
		"LifecycleEvidence",
		"NoOrchestrationAdapter",
		"NoAssetPlayback",
	},
	{
		"22",
		"future.adapter",
		"FutureAdapterSeparation",
		"BoundaryReady",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"FutureAdapterSeparationEvidence",
		"FutureAdapterSeparate",
		"FutureAssetOperationsSeparate",
	},
	{
		"23",
		"future.asset.operation",
		"FutureAssetOperationSeparation",
		"BoundaryReady",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"FutureAssetOperationSeparationEvidence",
		"FutureAdapterSeparate",
		"FutureAssetOperationsSeparate",
	},
	{
		"24",
		"future.gameplay",
		"FutureGameplaySeparation",
		"BoundaryReady",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"FutureGameplaySeparationEvidence",
		"FutureAdapterSeparate",
		"FutureGameplaySeparate",
	},
}

Types.AssetExecutionIntegrationReadinessDeclarations = {}
Types.IntegrationReadinessDeclarationOrder = {}
for _, fieldName in ipairs(Types.IntegrationReadinessDeclarationFields) do
	if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
		Types.IntegrationReadinessDeclarationOrder[orderNameForField(fieldName)] = {}
	end
end

for _, row in ipairs(INTEGRATION_ROWS) do
	local order = row[1]
	local compatibility = row[2]
	local declaration = {
		integrationId = "asset.execution.integration." .. order .. "." .. compatibility,
		compatibilityId = "asset.execution.compatibility." .. order .. "." .. compatibility,
		integrationDeclarationId = "asset.execution.declaration." .. order .. "." .. compatibility,
		integrationKind = row[3],
		integrationStatus = row[4],
		runtimeName = Types.RuntimeName,
		providerName = Types.RuntimeProviderName,
		snapshotProviderName = Types.RuntimeProviderName,
		coordinatorName = Types.CoordinatorName,
		diagnosticsProviderName = Types.RuntimeProviderName,
		bootstrapDependencyName = "AssetExecutionAuthorizationCoordinator",
		engineGovernanceSnapshotProviderName = Types.RuntimeProviderName,
		documentationReference = row[5],
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		readinessEvidenceKind = row[6],
		executionRuntimeName = Types.RuntimeName,
		executionProviderName = Types.RuntimeProviderName,
		executionSnapshotProviderName = Types.RuntimeProviderName,
		executionCoordinatorName = Types.CoordinatorName,
		adapterBoundaryKind = row[7],
		assetOperationBoundaryKind = row[8],
		required = true,
		evidence = { "asset.execution.integration." .. compatibility .. ".copied" },
		tags = { "asset.execution.integration", "metadata.only" },
		metadata = {
			copied = "true",
			order = order,
			compatibility = compatibility,
			boundary = "metadata.only",
			isolation = "copied",
			futureAdapterAbsent = "true",
			futureAssetOperationsAbsent = "true",
			authoritySeparated = "true",
			executionSeparated = "true",
			gameplaySeparated = "true",
		},
	}
	table.insert(Types.AssetExecutionIntegrationReadinessDeclarations, declaration)
	for _, fieldName in ipairs(Types.IntegrationReadinessDeclarationFields) do
		if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
			table.insert(
				Types.IntegrationReadinessDeclarationOrder[orderNameForField(fieldName)],
				declaration[fieldName]
			)
		end
	end
end

local ADAPTER_READINESS_ROWS = {
	{
		"01",
		"execution.runtime",
		"ExecutionRuntimeCompatibility",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoLiveAdapter",
		"NoAssetLoading",
		"NoAdapterInitialization",
	},
	{
		"02",
		"execution.provider",
		"ExecutionProviderCompatibility",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterModule",
		"NoAssetPreloading",
		"NoAdapterStart",
	},
	{
		"03",
		"execution.snapshot",
		"ExecutionSnapshotCompatibility",
		"Compatible",
		"ASSET_EXECUTION_DIAGNOSTICS.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterCallback",
		"NoAssetStreaming",
		"NoAdapterActivation",
	},
	{
		"04",
		"execution.coordinator",
		"ExecutionCoordinatorCompatibility",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterListener",
		"NoAssetSpawning",
		"NoAdapterExecution",
	},
	{
		"05",
		"identity",
		"AdapterIdentityReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"NoAdapterKind",
		"NoAuthority",
		"NoAdapterService",
		"NoAssetCloning",
		"NoAdapterShutdownOwnership",
	},
	{
		"06",
		"provider",
		"AdapterProviderReadiness",
		"Deferred",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"NoAdapterKind",
		"NoAuthority",
		"NoAdapterRegistry",
		"NoAssetInsertion",
		"NoAdapterRecovery",
	},
	{
		"07",
		"snapshot",
		"AdapterSnapshotReadiness",
		"Deferred",
		"ASSET_EXECUTION_ADAPTER_READINESS_DIAGNOSTICS.md",
		"NoAdapterKind",
		"NoAuthority",
		"NoAdapterActivation",
		"NoAssetApplication",
		"FutureLifecycleSeparate",
	},
	{
		"08",
		"coordinator",
		"AdapterCoordinatorReadiness",
		"Deferred",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"NoAdapterKind",
		"NoAuthority",
		"NoAdapterResolution",
		"NoAssetDisplay",
		"NoAdapterInitialization",
	},
	{
		"09",
		"schema",
		"AdapterSchemaReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_VALIDATION.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterDispatch",
		"NoAssetPlayback",
		"NoAdapterStart",
	},
	{
		"10",
		"validation",
		"AdapterValidationReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_VALIDATION.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterQueue",
		"NoAnimationPlayback",
		"NoAdapterActivation",
	},
	{
		"11",
		"serialization",
		"AdapterSerializationReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_SERIALIZATION.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"FutureAdapterSeparate",
		"NoAudioPlayback",
		"NoAdapterExecution",
	},
	{
		"12",
		"diagnostics",
		"AdapterDiagnosticsReadiness",
		"ObservationOnly",
		"ASSET_EXECUTION_ADAPTER_READINESS_DIAGNOSTICS.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoLiveAdapter",
		"NoModelCreation",
		"NoAdapterShutdownOwnership",
	},
	{
		"13",
		"snapshot.isolation",
		"AdapterSnapshotIsolationReadiness",
		"ObservationOnly",
		"ASSET_EXECUTION_ADAPTER_READINESS_DIAGNOSTICS.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterModule",
		"NoInterfaceSurface",
		"NoAdapterRecovery",
	},
	{
		"14",
		"lifecycle",
		"AdapterLifecycleReadiness",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterCallback",
		"NoVisualEffects",
		"FutureLifecycleSeparate",
	},
	{
		"15",
		"runtime.limit",
		"AdapterRuntimeLimitReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_RUNTIME_LIMITS.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterListener",
		"NoWorldMutation",
		"NoAdapterInitialization",
	},
	{
		"16",
		"bootstrap",
		"BootstrapReadiness",
		"Compatible",
		"ASSET_EXECUTION_RUNTIME.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterService",
		"NoStorageMutation",
		"NoAdapterStart",
	},
	{
		"17",
		"engine.governance",
		"EngineGovernanceReadiness",
		"Compatible",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterRegistry",
		"NoNetworkOwnership",
		"NoAdapterActivation",
	},
	{
		"18",
		"documentation",
		"DocumentationReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"GovernanceAdapter",
		"MetadataOnly",
		"NoAdapterActivation",
		"NoPhysicsExecution",
		"NoAdapterExecution",
	},
	{
		"19",
		"server.authority",
		"ServerAuthorityReadiness",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"ServerAuthoritativeFuture",
		"NoAdapterResolution",
		"NoGameplayExecution",
		"NoAdapterShutdownOwnership",
	},
	{
		"20",
		"client.authority",
		"ClientAuthoritySeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoClientAuthority",
		"NoAdapterDispatch",
		"FutureAssetOperationsSeparate",
		"NoAdapterRecovery",
	},
	{
		"21",
		"callback.separation",
		"CallbackSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterCallback",
		"NoAssetLoading",
		"FutureLifecycleSeparate",
	},
	{
		"22",
		"listener.separation",
		"ListenerSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterListener",
		"NoAssetPreloading",
		"NoAdapterInitialization",
	},
	{
		"23",
		"service.reference",
		"ServiceReferenceSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterService",
		"NoAssetStreaming",
		"NoAdapterStart",
	},
	{
		"24",
		"module.reference",
		"ModuleReferenceSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterModule",
		"NoAssetSpawning",
		"NoAdapterActivation",
	},
	{
		"25",
		"runtime.handle",
		"RuntimeHandleSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"FutureGovernedAuthorityRequired",
		"NoLiveAdapter",
		"NoAssetCloning",
		"NoAdapterExecution",
	},
	{
		"26",
		"asset.handle",
		"AssetHandleSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
		"GovernanceAdapter",
		"FutureAuthorizationRequired",
		"NoAdapterRegistry",
		"NoAssetInsertion",
		"NoAdapterShutdownOwnership",
	},
	{
		"27",
		"routing",
		"RoutingSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterResolution",
		"NoAssetApplication",
		"NoAdapterRecovery",
	},
	{
		"28",
		"dispatch",
		"DispatchSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterDispatch",
		"NoAssetDisplay",
		"FutureLifecycleSeparate",
	},
	{
		"29",
		"queue",
		"QueueSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoAdapterQueue",
		"NoAssetPlayback",
		"NoAdapterInitialization",
	},
	{
		"30",
		"scheduler",
		"SchedulerSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"FutureAdapterSeparate",
		"NoAnimationPlayback",
		"NoAdapterStart",
	},
	{
		"31",
		"orchestration",
		"OrchestrationSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"GovernanceAdapter",
		"NoDirectExecution",
		"NoLiveAdapter",
		"NoAudioPlayback",
		"NoAdapterActivation",
	},
	{
		"32",
		"asset.loading",
		"AssetLoadingSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"AssetAcquisitionAdapter",
		"FutureRuntimePermitRequired",
		"NoAdapterModule",
		"NoAssetLoading",
		"NoAdapterExecution",
	},
	{
		"33",
		"asset.spawning",
		"AssetSpawningSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"AssetFormationAdapter",
		"FutureRuntimePermitRequired",
		"NoAdapterCallback",
		"NoAssetSpawning",
		"NoAdapterShutdownOwnership",
	},
	{
		"34",
		"asset.application",
		"AssetApplicationSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"AssetApplicationAdapter",
		"FutureRuntimePermitRequired",
		"NoAdapterListener",
		"NoAssetApplication",
		"NoAdapterRecovery",
	},
	{
		"35",
		"asset.display",
		"AssetDisplaySeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"AssetPresentationAdapter",
		"FutureRuntimePermitRequired",
		"NoAdapterService",
		"NoAssetDisplay",
		"FutureLifecycleSeparate",
	},
	{
		"36",
		"asset.playback",
		"AssetPlaybackSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"AudioAdapter",
		"FutureRuntimePermitRequired",
		"NoAdapterRegistry",
		"NoAssetPlayback",
		"NoAdapterInitialization",
	},
	{
		"37",
		"gameplay",
		"GameplaySeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
		"OperationBoundaryAdapter",
		"NoDirectExecution",
		"NoAdapterActivation",
		"NoGameplayExecution",
		"NoAdapterStart",
	},
	{
		"38",
		"future.adapter.runtime",
		"FutureAdapterRuntimeReadiness",
		"Deferred",
		"ASSET_EXECUTION_ADAPTER_READINESS.md",
		"NoAdapterKind",
		"FutureGovernedAuthorityRequired",
		"FutureAdapterSeparate",
		"FutureAssetOperationsSeparate",
		"FutureLifecycleSeparate",
	},
}

Types.AssetExecutionAdapterReadinessDeclarations = {}
Types.AdapterReadinessDeclarationOrder = {}
for _, fieldName in ipairs(Types.AdapterReadinessDeclarationFields) do
	if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
		Types.AdapterReadinessDeclarationOrder[orderNameForField(fieldName)] = {}
	end
end

for _, row in ipairs(ADAPTER_READINESS_ROWS) do
	local order = row[1]
	local compatibility = row[2]
	local declaration = {
		readinessId = "asset.execution.adapter.readiness." .. order .. "." .. compatibility,
		compatibilityId = "asset.execution.adapter.compatibility." .. order .. "." .. compatibility,
		adapterReadinessDeclarationId = "asset.execution.adapter.declaration."
			.. order
			.. "."
			.. compatibility,
		readinessKind = row[3],
		readinessStatus = row[4],
		runtimeName = Types.RuntimeName,
		providerName = Types.RuntimeProviderName,
		snapshotProviderName = Types.RuntimeProviderName,
		coordinatorName = Types.CoordinatorName,
		diagnosticsProviderName = Types.RuntimeProviderName,
		bootstrapDependencyName = "AssetExecutionAuthorizationCoordinator",
		engineGovernanceSnapshotProviderName = Types.RuntimeProviderName,
		documentationReference = row[5],
		executionRuntimeName = Types.RuntimeName,
		executionProviderName = Types.RuntimeProviderName,
		executionSnapshotProviderName = Types.RuntimeProviderName,
		executionCoordinatorName = Types.CoordinatorName,
		futureAdapterRuntimeName = "AbsentFutureAdapterRuntime",
		futureAdapterProviderName = "absentFutureAdapterProvider",
		futureAdapterSnapshotProviderName = "absentFutureAdapterSnapshotProvider",
		futureAdapterCoordinatorName = "AbsentFutureAdapterCoordinator",
		adapterKind = row[6],
		adapterAuthorityKind = row[7],
		adapterBoundaryKind = row[8],
		assetOperationBoundaryKind = row[9],
		lifecycleBoundaryKind = row[10],
		required = true,
		evidence = { "asset.execution.adapter.readiness." .. compatibility .. ".copied" },
		tags = { "asset.execution.adapter.readiness", "metadata.only" },
		metadata = {
			copied = "true",
			order = order,
			compatibility = compatibility,
			boundary = "metadata.only",
			isolation = "copied",
			liveAdapterAbsent = "true",
			futureAdapterProviderAbsent = "true",
			futureAdapterSnapshotAbsent = "true",
			futureAssetOperationsAbsent = "true",
			assetOperationPermissionAbsent = "true",
			authoritySeparated = "true",
			clientAuthorityAbsent = "true",
			lifecycleSeparated = "true",
			gameplaySeparated = "true",
		},
	}
	table.insert(Types.AssetExecutionAdapterReadinessDeclarations, declaration)
	for _, fieldName in ipairs(Types.AdapterReadinessDeclarationFields) do
		if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
			table.insert(
				Types.AdapterReadinessDeclarationOrder[orderNameForField(fieldName)],
				declaration[fieldName]
			)
		end
	end
end

local ADAPTER_CONTRACT_ROWS = {
	{
		"01",
		"runtime.identity",
		"RuntimeIdentityContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
		"MetadataOnlyContract",
		"NoAdapterInitialize",
		"CopiedMetadataOnly",
		"ExactIdentities",
		"NoAuthority",
		"NoAssetOperationApi",
	},
	{
		"02",
		"provider.identity",
		"ProviderIdentityContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
		"NoAdapterProvider",
		"NoAdapterStart",
		"NoMutableReferences",
		"ExactIdentities",
		"NoAuthority",
		"NoAssetLoading",
	},
	{
		"03",
		"snapshot.identity",
		"SnapshotIdentityContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_DIAGNOSTICS.md",
		"NoAdapterProvider",
		"NoAdapterActivate",
		"DeepCopyOnly",
		"ExactIdentities",
		"NoAuthority",
		"NoAssetStreaming",
	},
	{
		"04",
		"coordinator.identity",
		"CoordinatorIdentityContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
		"NoAdapterRuntime",
		"NoAdapterExecute",
		"DeepCopyOnly",
		"ExactIdentities",
		"NoAuthority",
		"NoAssetSpawning",
	},
	{
		"05",
		"diagnostics",
		"DiagnosticsContract",
		"ObservationOnly",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_DIAGNOSTICS.md",
		"MetadataOnlyContract",
		"NoAdapterRecover",
		"NoRuntimeHandles",
		"ExactFields",
		"NoAuthority",
		"NoAssetApplication",
	},
	{
		"06",
		"bootstrap",
		"BootstrapContract",
		"ContractReady",
		"ASSET_EXECUTION_RUNTIME.md",
		"MetadataOnlyContract",
		"NoAdapterShutdownOwnership",
		"NoAdapterHandles",
		"ExactOrdering",
		"NoAuthority",
		"NoAssetPlayback",
	},
	{
		"07",
		"governance",
		"GovernanceContract",
		"ContractReady",
		"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
		"MetadataOnlyContract",
		"FutureLifecycleSeparate",
		"CopiedMetadataOnly",
		"ExactIdentities",
		"NoAuthority",
		"NoRouting",
	},
	{
		"08",
		"documentation",
		"DocumentationContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
		"MetadataOnlyContract",
		"NoAdapterInitialize",
		"NoUnsafePayloads",
		"ExactFields",
		"NoAuthority",
		"NoDispatch",
	},
	{
		"09",
		"serialization",
		"SerializationContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_VALIDATION.md",
		"MetadataOnlyContract",
		"NoAdapterStart",
		"NoUnsafePayloads",
		"ExactEvidence",
		"NoAuthority",
		"NoQueueing",
	},
	{
		"10",
		"validation",
		"ValidationContract",
		"ContractReady",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_VALIDATION.md",
		"MetadataOnlyContract",
		"NoAdapterActivate",
		"DeepCopyOnly",
		"ValidationBeforeMutation",
		"NoAuthority",
		"NoScheduling",
	},
	{
		"11",
		"isolation",
		"IsolationContract",
		"ObservationOnly",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_DIAGNOSTICS.md",
		"MetadataOnlyContract",
		"NoAdapterExecute",
		"NoMutableReferences",
		"ExactMetadata",
		"NoAuthority",
		"NoOrchestration",
	},
	{
		"12",
		"lifecycle",
		"LifecycleContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterActivation",
		"FutureLifecycleSeparate",
		"CopiedMetadataOnly",
		"ExactEnums",
		"NoExecutionPermission",
		"NoGameplay",
	},
	{
		"13",
		"authority",
		"AuthorityContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterApi",
		"NoAdapterRecover",
		"NoRuntimeHandles",
		"ExactEnums",
		"NoClientAuthority",
		"NoPresentation",
	},
	{
		"14",
		"operation.boundary",
		"OperationBoundaryContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterImplementation",
		"NoAdapterShutdownOwnership",
		"NoAdapterHandles",
		"ExactEnums",
		"NoOperationPermission",
		"NoSave",
	},
	{
		"15",
		"registry.absence",
		"NoRegistryContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterRegistry",
		"NoAdapterInitialize",
		"NoRuntimeHandles",
		"ExactMetadata",
		"NoExecutionPermission",
		"NoChapter",
	},
	{
		"16",
		"activation.absence",
		"NoActivationContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterActivation",
		"NoAdapterActivate",
		"NoAdapterHandles",
		"ExactTags",
		"NoExecutionPermission",
		"FutureOperationSeparate",
	},
	{
		"17",
		"implementation.absence",
		"NoImplementationContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"NoAdapterImplementation",
		"NoAdapterExecute",
		"NoRuntimeHandles",
		"ExactEvidence",
		"FutureGovernedAuthorityRequired",
		"NoAssetOperationApi",
	},
	{
		"18",
		"routing.absence",
		"NoRoutingContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
		"NoAdapterApi",
		"NoAdapterRecover",
		"DeepCopyOnly",
		"ExactOrdering",
		"NoExecutionPermission",
		"NoRouting",
	},
	{
		"19",
		"dispatch.absence",
		"NoDispatchContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
		"NoAdapterApi",
		"NoAdapterShutdownOwnership",
		"DeepCopyOnly",
		"ExactOrdering",
		"NoExecutionPermission",
		"NoDispatch",
	},
	{
		"20",
		"queue.absence",
		"NoQueueContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
		"NoAdapterApi",
		"NoAdapterInitialize",
		"CopiedMetadataOnly",
		"ExactOrdering",
		"NoExecutionPermission",
		"NoQueueing",
	},
	{
		"21",
		"scheduler.absence",
		"NoSchedulerContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
		"NoAdapterApi",
		"NoAdapterStart",
		"CopiedMetadataOnly",
		"ExactOrdering",
		"NoExecutionPermission",
		"NoScheduling",
	},
	{
		"22",
		"orchestration.absence",
		"NoOrchestrationContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
		"NoAdapterApi",
		"NoAdapterActivate",
		"CopiedMetadataOnly",
		"ExactOrdering",
		"NoExecutionPermission",
		"NoOrchestration",
	},
	{
		"23",
		"gameplay.absence",
		"NoGameplayContract",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
		"FutureAdapterSeparate",
		"NoAdapterExecute",
		"NoUnsafePayloads",
		"ExactMetadata",
		"FutureAuthorizationRequired",
		"NoGameplay",
	},
	{
		"24",
		"future.implementation",
		"FutureImplementationContract",
		"Deferred",
		"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
		"FutureAdapterSeparate",
		"FutureLifecycleSeparate",
		"NoUnsafePayloads",
		"ValidationBeforeMutation",
		"FutureGovernedAuthorityRequired",
		"FutureOperationSeparate",
	},
}

Types.AssetExecutionAdapterContractDeclarations = {}
Types.AdapterContractDeclarationOrder = {}
for _, fieldName in ipairs(Types.AdapterContractDeclarationFields) do
	if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
		Types.AdapterContractDeclarationOrder[orderNameForField(fieldName)] = {}
	end
end

for _, row in ipairs(ADAPTER_CONTRACT_ROWS) do
	local order = row[1]
	local compatibility = row[2]
	local declaration = {
		adapterContractId = "asset.execution.adapter.contract." .. order .. "." .. compatibility,
		compatibilityId = "asset.execution.adapter.contract.compatibility."
			.. order
			.. "."
			.. compatibility,
		contractDeclarationId = "asset.execution.adapter.contract.declaration."
			.. order
			.. "."
			.. compatibility,
		contractKind = row[3],
		contractStatus = row[4],
		runtimeName = Types.RuntimeName,
		providerName = Types.RuntimeProviderName,
		snapshotProviderName = Types.RuntimeProviderName,
		coordinatorName = Types.CoordinatorName,
		diagnosticsProviderName = Types.RuntimeProviderName,
		bootstrapDependencyName = "AssetExecutionAuthorizationCoordinator",
		governanceProviderName = Types.RuntimeProviderName,
		executionRuntimeName = Types.RuntimeName,
		executionProviderName = Types.RuntimeProviderName,
		executionCoordinatorName = Types.CoordinatorName,
		adapterRuntimeName = "AbsentFutureAdapterRuntime",
		adapterProviderName = "absentFutureAdapterProvider",
		adapterCoordinatorName = "AbsentFutureAdapterCoordinator",
		adapterSnapshotProviderName = "absentFutureAdapterSnapshotProvider",
		adapterContractBoundary = row[6],
		lifecycleBoundary = row[7],
		serializationBoundary = row[8],
		validationBoundary = row[9],
		authorityBoundary = row[10],
		operationBoundary = row[11],
		required = true,
		evidence = { "asset.execution.adapter.contract." .. compatibility .. ".copied" },
		tags = { "asset.execution.adapter.contract", "metadata.only" },
		metadata = {
			copied = "true",
			order = order,
			compatibility = compatibility,
			boundary = "metadata.only",
			isolation = "copied",
			contractOnly = "true",
			adapterAbsent = "true",
			adapterRegistrationAbsent = "true",
			adapterActivationAbsent = "true",
			adapterOwnershipAbsent = "true",
			assetOperationsAbsent = "true",
			authoritySeparated = "true",
			gameplaySeparated = "true",
		},
	}
	table.insert(Types.AssetExecutionAdapterContractDeclarations, declaration)
	for _, fieldName in ipairs(Types.AdapterContractDeclarationFields) do
		if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
			table.insert(
				Types.AdapterContractDeclarationOrder[orderNameForField(fieldName)],
				declaration[fieldName]
			)
		end
	end
end

Types.PostureKeys = {
	"assetExecutionRuntimePosture",
	"assetExecutionRequestPosture",
	"assetExecutionBoundaryPosture",
	"assetExecutionAuditPosture",
	"assetExecutionIntegrationReadinessPosture",
	"assetExecutionCompatibilityPosture",
	"assetExecutionIntegrationHardeningPosture",
	"assetExecutionDeclarationExactnessPosture",
	"assetExecutionDeclarationOrderingPosture",
	"assetExecutionCompatibilityIdentityPosture",
	"assetExecutionOrderTablePosture",
	"assetExecutionMetadataExactnessPosture",
	"assetExecutionEvidenceExactnessPosture",
	"assetExecutionTagExactnessPosture",
	"assetExecutionAdapterContaminationPosture",
	"assetExecutionOperationContaminationPosture",
	"assetExecutionIntegrationLimitIsolationPosture",
	"assetExecutionIntegrationDocumentationConsistencyPosture",
	"assetExecutionAdapterReadinessPosture",
	"assetExecutionAdapterCompatibilityPosture",
	"assetExecutionAdapterIdentityPosture",
	"assetExecutionAdapterAuthorityPosture",
	"assetExecutionAdapterBoundaryPosture",
	"assetExecutionAdapterLifecyclePosture",
	"assetExecutionAdapterSerializationPosture",
	"assetExecutionAdapterIsolationPosture",
	"assetExecutionAdapterLimitPosture",
	"assetExecutionAdapterDocumentationPosture",
	"assetExecutionNoLiveAdapterPosture",
	"assetExecutionNoAssetOperationPosture",
	"assetExecutionAdapterHardeningPosture",
	"assetExecutionAdapterIdentityHardeningPosture",
	"assetExecutionAdapterBoundaryHardeningPosture",
	"assetExecutionAdapterDocumentationHardeningPosture",
	"assetExecutionAdapterSerializationHardeningPosture",
	"assetExecutionAdapterValidationHardeningPosture",
	"assetExecutionAdapterIsolationHardeningPosture",
	"assetExecutionAdapterLimitHardeningPosture",
	"assetExecutionAdapterGovernanceHardeningPosture",
	"assetExecutionAdapterBootstrapHardeningPosture",
	"assetExecutionAdapterContractPosture",
	"assetExecutionAdapterContractValidationPosture",
	"assetExecutionAdapterContractIsolationPosture",
	"assetExecutionAdapterContractBoundaryPosture",
	"assetExecutionAdapterContractDocumentationPosture",
	"assetExecutionAdapterContractSerializationPosture",
	"assetExecutionAdapterContractLifecyclePosture",
	"assetExecutionAdapterContractAuthorityPosture",
	"assetExecutionAdapterContractOperationPosture",
	"assetExecutionAdapterContractGovernancePosture",
	"assetExecutionAdapterContractBootstrapPosture",
	"assetExecutionAdapterContractHardeningPosture",
	"assetExecutionAdapterContractValidationHardeningPosture",
	"assetExecutionAdapterContractSerializationHardeningPosture",
	"assetExecutionAdapterContractIsolationHardeningPosture",
	"assetExecutionAdapterContractBoundaryHardeningPosture",
	"assetExecutionAdapterContractDocumentationHardeningPosture",
	"assetExecutionAdapterContractGovernanceHardeningPosture",
	"assetExecutionAdapterContractBootstrapHardeningPosture",
	"assetExecutionAdapterContractIdentityHardeningPosture",
	"assetExecutionAdapterContractLifecycleHardeningPosture",
	"assetExecutionAdapterContractAuthorityHardeningPosture",
	"assetExecutionAdapterContractOperationHardeningPosture",
	"assetExecutionSchemaPosture",
	"assetExecutionEnumPosture",
	"assetExecutionReferencePosture",
	"assetExecutionArrayPosture",
	"assetExecutionLimitPosture",
	"assetExecutionSignalPosture",
	"assetExecutionCoordinatorBoundaryPosture",
	"assetExecutionFutureAdapterSeparationPosture",
	"assetExecutionFutureAssetOperationSeparationPosture",
	"assetExecutionFutureGameplaySeparationPosture",
	"assetExecutionIsolationPosture",
	"assetExecutionValidationPosture",
	"assetExecutionLifecyclePosture",
	"assetExecutionNoAuthorityPosture",
	"noExecution",
	"noAssetLoading",
	"noGameplay",
	"noPresentation",
	"noSave",
	"noNetworking",
	"noAnalytics",
	"noTelemetry",
}

Types.DocumentationFiles = {
	"ASSET_EXECUTION_RUNTIME.md",
	"ASSET_EXECUTION_VALIDATION.md",
	"ASSET_EXECUTION_SERIALIZATION.md",
	"ASSET_EXECUTION_DIAGNOSTICS.md",
	"ASSET_EXECUTION_RUNTIME_LIMITS.md",
	"ASSET_EXECUTION_SELF_CHECKS.md",
	"ASSET_EXECUTION_PRODUCTION_REVIEW.md",
	"ASSET_EXECUTION_AUDIT.md",
	"ASSET_EXECUTION_RUNTIME_INTEGRATION_READINESS.md",
	"ASSET_EXECUTION_ADAPTER_READINESS.md",
	"ASSET_EXECUTION_ADAPTER_READINESS_VALIDATION.md",
	"ASSET_EXECUTION_ADAPTER_READINESS_DIAGNOSTICS.md",
	"ASSET_EXECUTION_ADAPTER_READINESS_SELF_CHECKS.md",
	"ASSET_EXECUTION_ADAPTER_READINESS_PRODUCTION_REVIEW.md",
	"ASSET_EXECUTION_ADAPTER_CONTRACT_READINESS.md",
	"ASSET_EXECUTION_ADAPTER_CONTRACT_VALIDATION.md",
	"ASSET_EXECUTION_ADAPTER_CONTRACT_DIAGNOSTICS.md",
	"ASSET_EXECUTION_ADAPTER_CONTRACT_SELF_CHECKS.md",
	"ASSET_EXECUTION_ADAPTER_CONTRACT_PRODUCTION_REVIEW.md",
	"EXECUTION_RUNTIME.md",
	"EXECUTION_REQUEST_RUNTIME.md",
	"EXECUTION_BOUNDARY_RUNTIME.md",
	"EXECUTION_AUDIT_RUNTIME.md",
}

Types.BootstrapDependencyOrder = {
	"AssetExecutionAuthorizationCoordinator",
}

Types.GovernanceSnapshotProviders = {
	"assetExecutionRuntime",
}

Types.Limits = {
	MaxRuntimes = 160,
	MaxRequests = 480,
	MaxBoundaries = 320,
	MaxAudits = 240,
	MaxValidationFailures = 220,
	MaxSnapshotHistory = 60,
	MaxPayloadDepth = 8,
	MaxPayloadNodes = 520,
	MaxStringLength = 280,
	MaxTags = 32,
	MaxEvidence = 56,
	MaxChildReferences = 220,
	MaxSummaryLength = 180,
}

return Types
