--!strict

local Config = {}

Config.SchemaVersion = "210-recovery.1.0.0"
Config.PhaseName = "Blackwater Descent Production Environment Art and Lighting"
Config.CompletionTier = "Static Production Candidate"

Config.FinishedSpaces = table.freeze({
	"Arrival street",
	"Blackwater approach",
	"Alley",
	"Gate",
	"House facade",
	"Front steps",
	"Threshold",
	"Entry hall",
	"First investigation spaces",
	"Main corridor",
	"Archive",
	"Ward chamber",
	"Basement",
	"Glass Heart chamber",
	"Blackout route",
	"Dawn exterior",
})

Config.Palettes = table.freeze({
	wetStone = Color3.fromRGB(28, 31, 33),
	agedStone = Color3.fromRGB(45, 43, 40),
	sootBrick = Color3.fromRGB(34, 29, 28),
	tarnishedBrass = Color3.fromRGB(118, 87, 44),
	deadWood = Color3.fromRGB(67, 48, 34),
	ledgerPaper = Color3.fromRGB(127, 113, 85),
	wardGlass = Color3.fromRGB(86, 115, 110),
	bloodMemory = Color3.fromRGB(76, 18, 24),
	dawnAsh = Color3.fromRGB(124, 118, 101),
	gaslight = Color3.fromRGB(255, 181, 88),
})

Config.RouteDressings = table.freeze({
	{
		id = "street_wet_ruts",
		space = "Arrival street",
		kind = "groundStory",
		cframe = CFrame.new(-11, 0.58, 70),
		size = Vector3.new(18, 0.08, 2.4),
		palette = "agedStone",
		material = Enum.Material.Mud,
	},
	{
		id = "street_wrong_shadow",
		space = "Arrival street",
		kind = "visualLandmark",
		cframe = CFrame.new(12, 0.62, 82),
		size = Vector3.new(9, 0.06, 5),
		palette = "sootBrick",
		material = Enum.Material.Slate,
	},
	{
		id = "approach_receipt_gutter",
		space = "Blackwater approach",
		kind = "environmentalStory",
		cframe = CFrame.new(-18, 1.15, 34),
		size = Vector3.new(7, 0.12, 1.2),
		palette = "ledgerPaper",
		material = Enum.Material.Wood,
	},
	{
		id = "approach_unlit_window_line",
		space = "Blackwater approach",
		kind = "silhouette",
		cframe = CFrame.new(0, 18, 11.8),
		size = Vector3.new(19, 5, 0.18),
		palette = "sootBrick",
		material = Enum.Material.Slate,
	},
	{
		id = "alley_runoff_channel",
		space = "Alley",
		kind = "navigationRead",
		cframe = CFrame.new(-39, 0.72, 44),
		size = Vector3.new(2, 0.16, 38),
		palette = "wetStone",
		material = Enum.Material.Cobblestone,
	},
	{
		id = "alley_posted_notice",
		space = "Alley",
		kind = "microStory",
		cframe = CFrame.new(-31, 4.2, 36),
		size = Vector3.new(0.14, 3, 4),
		palette = "ledgerPaper",
		material = Enum.Material.Wood,
	},
	{
		id = "gate_black_iron_bars",
		space = "Gate",
		kind = "threshold",
		cframe = CFrame.new(0, 4, 103),
		size = Vector3.new(34, 8, 0.34),
		palette = "sootBrick",
		material = Enum.Material.Metal,
	},
	{
		id = "gate_brass_lock_plate",
		space = "Gate",
		kind = "interactionFocus",
		cframe = CFrame.new(0, 4.4, 102.5),
		size = Vector3.new(3, 2, 0.2),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "facade_blind_center_window",
		space = "House facade",
		kind = "visualLandmark",
		cframe = CFrame.new(0, 17, 8.2),
		size = Vector3.new(5.8, 8, 0.25),
		palette = "bloodMemory",
		material = Enum.Material.Glass,
	},
	{
		id = "facade_rain_blackening",
		space = "House facade",
		kind = "weathering",
		cframe = CFrame.new(-8, 12, 8),
		size = Vector3.new(1.2, 21, 0.18),
		palette = "sootBrick",
		material = Enum.Material.Slate,
	},
	{
		id = "front_steps_boot_scrape",
		space = "Front steps",
		kind = "readableTrace",
		cframe = CFrame.new(-3, 0.7, 21),
		size = Vector3.new(8, 0.08, 1.1),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "threshold_wet_line",
		space = "Threshold",
		kind = "boundaryRead",
		cframe = CFrame.new(0, 0.82, 8),
		size = Vector3.new(26, 0.1, 1),
		palette = "bloodMemory",
		material = Enum.Material.Slate,
	},
	{
		id = "entry_hall_turned_portraits",
		space = "Entry hall",
		kind = "environmentalStory",
		cframe = CFrame.new(-16.8, 7, -7),
		size = Vector3.new(0.18, 5, 12),
		palette = "deadWood",
		material = Enum.Material.Wood,
	},
	{
		id = "entry_hall_court_tile_axis",
		space = "Entry hall",
		kind = "compositionGuide",
		cframe = CFrame.new(0, 0.65, -5),
		size = Vector3.new(4, 0.08, 26),
		palette = "agedStone",
		material = Enum.Material.Marble,
	},
	{
		id = "investigation_vale_board",
		space = "First investigation spaces",
		kind = "microStory",
		cframe = CFrame.new(-31, 5, -66),
		size = Vector3.new(9, 5, 0.25),
		palette = "deadWood",
		material = Enum.Material.Wood,
	},
	{
		id = "investigation_player_names_table",
		space = "First investigation spaces",
		kind = "psychologicalDetail",
		cframe = CFrame.new(29, 2.1, -42),
		size = Vector3.new(9, 1.2, 4),
		palette = "deadWood",
		material = Enum.Material.Wood,
	},
	{
		id = "main_corridor_sagging_runner",
		space = "Main corridor",
		kind = "pathRead",
		cframe = CFrame.new(0, 0.72, -42),
		size = Vector3.new(9, 0.08, 48),
		palette = "bloodMemory",
		material = Enum.Material.Fabric,
	},
	{
		id = "archive_wall_of_dismissals",
		space = "Archive",
		kind = "storyWall",
		cframe = CFrame.new(0, 6, -101.5),
		size = Vector3.new(31, 8, 0.25),
		palette = "ledgerPaper",
		material = Enum.Material.Wood,
	},
	{
		id = "archive_lamp_pool",
		space = "Archive",
		kind = "lightingAnchor",
		cframe = CFrame.new(-9, 4, -86),
		size = Vector3.new(2, 6, 2),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "ward_floor_inlay",
		space = "Ward chamber",
		kind = "puzzleRead",
		cframe = CFrame.new(0, 0.7, -72),
		size = Vector3.new(22, 0.1, 22),
		palette = "wardGlass",
		material = Enum.Material.Glass,
	},
	{
		id = "ward_counterweight_stack",
		space = "Ward chamber",
		kind = "mechanicalStory",
		cframe = CFrame.new(14, 3, -73),
		size = Vector3.new(3, 5, 3),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "basement_rib_braces",
		space = "Basement",
		kind = "architecture",
		cframe = CFrame.new(-9, -1, -104),
		size = Vector3.new(1.2, 9, 24),
		palette = "deadWood",
		material = Enum.Material.Wood,
	},
	{
		id = "basement_blackwater_pool",
		space = "Basement",
		kind = "hazardRead",
		cframe = CFrame.new(8, -6.38, -101),
		size = Vector3.new(10, 0.08, 8),
		palette = "sootBrick",
		material = Enum.Material.Water,
	},
	{
		id = "glass_heart_basin",
		space = "Glass Heart chamber",
		kind = "climaxFocus",
		cframe = CFrame.new(0, -1.2, -138),
		size = Vector3.new(13, 1.4, 13),
		palette = "wardGlass",
		material = Enum.Material.Glass,
	},
	{
		id = "glass_heart_witness_rings",
		space = "Glass Heart chamber",
		kind = "compositionGuide",
		cframe = CFrame.new(0, -0.1, -138),
		size = Vector3.new(24, 0.08, 24),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "blackout_route_scraped_wall",
		space = "Blackout route",
		kind = "returnTransformation",
		cframe = CFrame.new(25, 5, 106),
		size = Vector3.new(0.22, 8, 20),
		palette = "bloodMemory",
		material = Enum.Material.Slate,
	},
	{
		id = "blackout_route_fallen_lamp",
		space = "Blackout route",
		kind = "hazardRead",
		cframe = CFrame.new(-14, 1.1, 105),
		size = Vector3.new(8, 0.45, 0.45),
		palette = "tarnishedBrass",
		material = Enum.Material.Metal,
	},
	{
		id = "dawn_exterior_wrong_receipt",
		space = "Dawn exterior",
		kind = "endingImage",
		cframe = CFrame.new(0, 1.2, 124),
		size = Vector3.new(3.5, 0.1, 2.2),
		palette = "ledgerPaper",
		material = Enum.Material.Wood,
	},
	{
		id = "dawn_exterior_color_line",
		space = "Dawn exterior",
		kind = "releaseLighting",
		cframe = CFrame.new(0, 0.67, 118),
		size = Vector3.new(52, 0.08, 4),
		palette = "dawnAsh",
		material = Enum.Material.Slate,
	},
})

Config.LightAnchors = table.freeze({
	{
		id = "archive_pool",
		position = Vector3.new(-9, 8, -86),
		range = 18,
		brightness = 1.1,
		color = "gaslight",
	},
	{
		id = "ward_glass_reflection",
		position = Vector3.new(0, 5, -72),
		range = 16,
		brightness = 0.65,
		color = "wardGlass",
	},
	{
		id = "heart_low_glow",
		position = Vector3.new(0, 3, -138),
		range = 20,
		brightness = 0.95,
		color = "bloodMemory",
	},
	{
		id = "dawn_line",
		position = Vector3.new(0, 6, 122),
		range = 28,
		brightness = 1.2,
		color = "dawnAsh",
	},
})

Config.EvidenceState = table.freeze({
	beforeAfterScreenshots = false,
	studioRouteExecuted = false,
	lightingProfilesCaptured = false,
	lowQualityGraphicsCompared = false,
	performanceCaptured = false,
	proxyRemovalComplete = false,
	finalAssetReviewComplete = false,
})

return table.freeze(Config)
