--!strict

local Config = {}

Config.SchemaVersion = "206.0.0"
Config.AudioIdentity = "The Street That Listens"
Config.AssetEvidenceState = "assetUploadBlocked"
Config.CertificationState = "productionCandidate"

Config.SurfaceLibrary = table.freeze({
	wet_cobblestone = {
		material = "Cobblestone",
		baseVolume = 0.64,
		pitchWindow = 0.035,
		overlay = "rain_slick",
	},
	dry_stone = {
		material = "Slate",
		baseVolume = 0.52,
		pitchWindow = 0.025,
		overlay = "dust_edge",
	},
	mud = { material = "Mud", baseVolume = 0.46, pitchWindow = 0.03, overlay = "suction" },
	gravel = {
		material = "Pebble",
		baseVolume = 0.58,
		pitchWindow = 0.04,
		overlay = "loose_scatter",
	},
	wood_floor = {
		material = "WoodPlanks",
		baseVolume = 0.5,
		pitchWindow = 0.028,
		overlay = "old_board",
	},
	damaged_wood = {
		material = "Wood",
		baseVolume = 0.56,
		pitchWindow = 0.032,
		overlay = "split_creak",
	},
	carpet = {
		material = "Fabric",
		baseVolume = 0.25,
		pitchWindow = 0.018,
		overlay = "thread_drag",
	},
	tile = { material = "Marble", baseVolume = 0.48, pitchWindow = 0.022, overlay = "hard_edge" },
	metal_stair = {
		material = "Metal",
		baseVolume = 0.62,
		pitchWindow = 0.024,
		overlay = "iron_ring",
	},
	shallow_puddle = {
		material = "Water",
		baseVolume = 0.53,
		pitchWindow = 0.03,
		overlay = "small_splash",
	},
	dust_debris = {
		material = "Ground",
		baseVolume = 0.42,
		pitchWindow = 0.035,
		overlay = "dry_shift",
	},
})

Config.MovementStates = table.freeze({
	slow_walk = { cadence = 0.88, volumeScale = 0.68, suspicionScale = 0.55 },
	walk = { cadence = 1, volumeScale = 1, suspicionScale = 1 },
	sprint = { cadence = 1.48, volumeScale = 1.28, suspicionScale = 1.65 },
	crouch = { cadence = 0.62, volumeScale = 0.38, suspicionScale = 0.35 },
	stop = { cadence = 0.2, volumeScale = 0.42, suspicionScale = 0.45 },
	turn = { cadence = 0.28, volumeScale = 0.36, suspicionScale = 0.4 },
	jump = { cadence = 0.5, volumeScale = 0.7, suspicionScale = 0.9 },
	land = { cadence = 0.45, volumeScale = 1.16, suspicionScale = 1.3 },
	stumble = { cadence = 0.7, volumeScale = 1.12, suspicionScale = 1.24 },
	stair_ascent = { cadence = 0.92, volumeScale = 1.05, suspicionScale = 1.12 },
	stair_descent = { cadence = 1.02, volumeScale = 1.12, suspicionScale = 1.2 },
	injured = { cadence = 0.54, volumeScale = 0.92, suspicionScale = 1.05 },
})

Config.ObjectFoley = table.freeze({
	lantern = {
		layer = "glass_oil_chain",
		priority = 75,
		caption = "[Lantern glass ticks against its frame.]",
	},
	coat = { layer = "wet_wool", priority = 42, caption = "[Wet cloth moves heavily.]" },
	brass_seal = {
		layer = "small_brass_weight",
		priority = 62,
		caption = "[The brass seal knocks softly.]",
	},
	keys = { layer = "period_key_ring", priority = 68, caption = "[Keys shift nearby.]" },
	glass_heart = {
		layer = "glass_pressure_harmonic",
		priority = 90,
		caption = "[The Glass Heart answers the room.]",
	},
	paper = { layer = "case_file_paper", priority = 58, caption = "[Old paper moves in damp air.]" },
	breath = { layer = "restrained_breath", priority = 74, caption = "[Breathing tightens.]" },
	hiding = {
		layer = "wardrobe_contact",
		priority = 72,
		caption = "[The hiding place settles around you.]",
	},
	door = { layer = "latch_wood_hinge", priority = 76, caption = "[A door strains in its frame.]" },
	ward = {
		layer = "ward_mechanism_harmonic",
		priority = 82,
		caption = "[The ward mechanism turns.]",
	},
})

Config.AcousticZones = table.freeze({
	exterior_street = {
		reverb = "open_wet_stone",
		wet = 0.18,
		decay = 0.9,
		absorbHigh = 0.18,
		lowReinforcement = 0.12,
		maxEmitters = 18,
	},
	covered_entrance = {
		reverb = "stone_threshold",
		wet = 0.28,
		decay = 1.1,
		absorbHigh = 0.24,
		lowReinforcement = 0.2,
		maxEmitters = 14,
	},
	foyer = {
		reverb = "tall_hall",
		wet = 0.36,
		decay = 1.7,
		absorbHigh = 0.34,
		lowReinforcement = 0.26,
		maxEmitters = 16,
	},
	drawing_room = {
		reverb = "furnished_room",
		wet = 0.24,
		decay = 1.05,
		absorbHigh = 0.46,
		lowReinforcement = 0.18,
		maxEmitters = 12,
	},
	gallery = {
		reverb = "upper_void",
		wet = 0.42,
		decay = 1.9,
		absorbHigh = 0.28,
		lowReinforcement = 0.32,
		maxEmitters = 14,
	},
	service_corridor = {
		reverb = "narrow_service",
		wet = 0.31,
		decay = 1.35,
		absorbHigh = 0.38,
		lowReinforcement = 0.24,
		maxEmitters = 12,
	},
	kitchen = {
		reverb = "cold_tile",
		wet = 0.29,
		decay = 1.2,
		absorbHigh = 0.2,
		lowReinforcement = 0.22,
		maxEmitters = 12,
	},
	cellar = {
		reverb = "brick_water",
		wet = 0.54,
		decay = 2.25,
		absorbHigh = 0.56,
		lowReinforcement = 0.46,
		maxEmitters = 10,
	},
	crypt = {
		reverb = "buried_stone",
		wet = 0.58,
		decay = 2.6,
		absorbHigh = 0.62,
		lowReinforcement = 0.5,
		maxEmitters = 10,
	},
	ward_chambers = {
		reverb = "mechanical_chamber",
		wet = 0.4,
		decay = 1.75,
		absorbHigh = 0.3,
		lowReinforcement = 0.34,
		maxEmitters = 12,
	},
	archive = {
		reverb = "paper_absorbed_hall",
		wet = 0.2,
		decay = 1.15,
		absorbHigh = 0.5,
		lowReinforcement = 0.16,
		maxEmitters = 12,
	},
	ritual_chamber = {
		reverb = "glass_subterranean",
		wet = 0.52,
		decay = 2.4,
		absorbHigh = 0.42,
		lowReinforcement = 0.52,
		maxEmitters = 14,
	},
	reliquary = {
		reverb = "small_glass_case",
		wet = 0.38,
		decay = 1.6,
		absorbHigh = 0.36,
		lowReinforcement = 0.34,
		maxEmitters = 8,
	},
	blackout_house = {
		reverb = "pressure_null",
		wet = 0.5,
		decay = 2.1,
		absorbHigh = 0.72,
		lowReinforcement = 0.58,
		maxEmitters = 10,
	},
	dawn_street = {
		reverb = "open_damp_morning",
		wet = 0.14,
		decay = 0.75,
		absorbHigh = 0.12,
		lowReinforcement = 0.08,
		maxEmitters = 18,
	},
})

Config.MixSnapshots = table.freeze({
	ordinary_london = {
		dialogue = 95,
		captions = 98,
		monster = 40,
		foley = 68,
		interactions = 75,
		environment = 72,
		ambience = 78,
		music = 18,
		ui = 60,
	},
	house_noticed_player = {
		dialogue = 95,
		captions = 98,
		monster = 54,
		foley = 72,
		interactions = 78,
		environment = 82,
		ambience = 58,
		music = 24,
		ui = 60,
	},
	investigation = {
		dialogue = 96,
		captions = 98,
		monster = 45,
		foley = 62,
		interactions = 82,
		environment = 60,
		ambience = 48,
		music = 18,
		ui = 64,
	},
	puzzle_concentration = {
		dialogue = 96,
		captions = 98,
		monster = 50,
		foley = 58,
		interactions = 90,
		environment = 52,
		ambience = 38,
		music = 12,
		ui = 66,
	},
	suspicion = {
		dialogue = 96,
		captions = 98,
		monster = 82,
		foley = 76,
		interactions = 78,
		environment = 68,
		ambience = 42,
		music = 30,
		ui = 58,
	},
	bailiff_nearby = {
		dialogue = 96,
		captions = 98,
		monster = 94,
		foley = 82,
		interactions = 76,
		environment = 56,
		ambience = 28,
		music = 12,
		ui = 54,
	},
	active_hunt = {
		dialogue = 97,
		captions = 99,
		monster = 96,
		foley = 90,
		interactions = 82,
		environment = 62,
		ambience = 22,
		music = 40,
		ui = 68,
	},
	hiding = {
		dialogue = 98,
		captions = 99,
		monster = 98,
		foley = 70,
		interactions = 72,
		environment = 38,
		ambience = 16,
		music = 6,
		ui = 48,
	},
	search_aftermath = {
		dialogue = 96,
		captions = 98,
		monster = 74,
		foley = 62,
		interactions = 72,
		environment = 54,
		ambience = 32,
		music = 10,
		ui = 56,
	},
	archive_reveal = {
		dialogue = 98,
		captions = 99,
		monster = 62,
		foley = 56,
		interactions = 88,
		environment = 78,
		ambience = 36,
		music = 34,
		ui = 64,
	},
	glass_heart_possession = {
		dialogue = 98,
		captions = 99,
		monster = 86,
		foley = 74,
		interactions = 92,
		environment = 84,
		ambience = 18,
		music = 46,
		ui = 70,
	},
	blackout = {
		dialogue = 99,
		captions = 99,
		monster = 96,
		foley = 90,
		interactions = 90,
		environment = 88,
		ambience = 8,
		music = 20,
		ui = 72,
	},
	escape = {
		dialogue = 98,
		captions = 99,
		monster = 92,
		foley = 94,
		interactions = 88,
		environment = 84,
		ambience = 34,
		music = 52,
		ui = 76,
	},
	dawn = {
		dialogue = 98,
		captions = 99,
		monster = 20,
		foley = 52,
		interactions = 68,
		environment = 70,
		ambience = 80,
		music = 34,
		ui = 58,
	},
	ending = {
		dialogue = 99,
		captions = 99,
		monster = 18,
		foley = 42,
		interactions = 62,
		environment = 60,
		ambience = 62,
		music = 48,
		ui = 64,
	},
})

Config.VoiceLimits = table.freeze({
	ambience = 4,
	environment = 10,
	footsteps = 8,
	monster = 6,
	interactions = 6,
	ui = 3,
	music = 6,
	dialogue = 4,
	captions = 4,
})

Config.MusicStems = table.freeze({
	air_texture = {
		family = "texture",
		assetStatus = "assetUploadBlocked",
		enters = { "ordinary_london", "house_noticed_player" },
	},
	low_strings = {
		family = "harmonic_tension",
		assetStatus = "assetUploadBlocked",
		enters = { "suspicion", "bailiff_nearby" },
	},
	period_instrument = {
		family = "period_identity",
		assetStatus = "assetUploadBlocked",
		enters = { "investigation", "archive_reveal" },
	},
	harmonic_tension = {
		family = "pressure",
		assetStatus = "assetUploadBlocked",
		enters = { "puzzle_concentration", "glass_heart_possession" },
	},
	pulse = {
		family = "threat",
		assetStatus = "assetUploadBlocked",
		enters = { "active_hunt", "blackout" },
	},
	percussion = { family = "escape", assetStatus = "assetUploadBlocked", enters = { "escape" } },
	glass_heart_motif = {
		family = "relic",
		assetStatus = "assetUploadBlocked",
		enters = { "glass_heart_possession", "ending" },
	},
	bailiff_motif = {
		family = "monster",
		assetStatus = "assetUploadBlocked",
		enters = { "bailiff_nearby", "active_hunt" },
	},
	vale_motif = {
		family = "narrative",
		assetStatus = "assetUploadBlocked",
		enters = { "archive_reveal", "dawn" },
	},
	dawn_resolution = {
		family = "resolution",
		assetStatus = "assetUploadBlocked",
		enters = { "dawn", "ending" },
	},
})

Config.SilenceStates = table.freeze({
	house_reveal_pause = {
		reduction = 0.72,
		preserve = { "captions", "dialogue", "critical_foley" },
	},
	wrong_bell_aftermath = { reduction = 0.82, preserve = { "captions", "ward_feedback" } },
	gate_threshold = { reduction = 0.64, preserve = { "interaction_confirmation", "captions" } },
	bailiff_listening = { reduction = 0.88, preserve = { "monster", "captions", "player_breath" } },
	hiding_close_pass = { reduction = 0.92, preserve = { "monster", "captions", "breath" } },
	glass_heart_removal = { reduction = 0.86, preserve = { "glass_heart", "captions" } },
	pre_escape_breath = { reduction = 0.7, preserve = { "monster", "objective", "captions" } },
	dawn_transition = { reduction = 0.54, preserve = { "dawn_ambience", "ending", "captions" } },
})

Config.BailiffAudioStates = table.freeze({
	Dormant = {
		caption = "[Something heavy sleeps deeper in the house.]",
		mix = "ordinary_london",
		telegraph = false,
	},
	Foreshadow = {
		caption = "[A chain settles above the rain.]",
		mix = "house_noticed_player",
		telegraph = false,
	},
	Patrol = { caption = "[Heavy steps cross another room.]", mix = "suspicion", telegraph = false },
	Stalk = {
		caption = "[The steps slow when you slow.]",
		mix = "bailiff_nearby",
		telegraph = true,
	},
	Observe = {
		caption = "[Keys stop somewhere out of sight.]",
		mix = "bailiff_nearby",
		telegraph = true,
	},
	Investigate = {
		caption = "[The Bailiff tests the floorboards nearby.]",
		mix = "suspicion",
		telegraph = true,
	},
	Suspicious = {
		caption = "[The Bailiff has heard enough.]",
		mix = "bailiff_nearby",
		telegraph = true,
	},
	Hunt = { caption = "[The Bailiff breaks into pursuit.]", mix = "active_hunt", telegraph = true },
	Search = {
		caption = "[The Bailiff searches where the noise ended.]",
		mix = "search_aftermath",
		telegraph = true,
	},
	Ambush = { caption = "[The room waits with him in it.]", mix = "hiding", telegraph = true },
	DoorPressure = {
		caption = "[A hand rests against the door.]",
		mix = "bailiff_nearby",
		telegraph = true,
	},
	Attack = { caption = "[The Bailiff raises the chain.]", mix = "active_hunt", telegraph = true },
	Miss = {
		caption = "[The chain strikes wood and drags back.]",
		mix = "search_aftermath",
		telegraph = true,
	},
	Recover = {
		caption = "[The Bailiff gathers himself.]",
		mix = "search_aftermath",
		telegraph = false,
	},
	Retreat = {
		caption = "[The steps leave, but not far.]",
		mix = "search_aftermath",
		telegraph = false,
	},
	Climax = { caption = "[The house moves with the Bailiff.]", mix = "blackout", telegraph = true },
	Disabled = { caption = "[The chain falls silent.]", mix = "dawn", telegraph = false },
})

Config.WardAudioLanguage = table.freeze({
	ward_west = {
		symbol = "lamp",
		material = "brass",
		interval = "minor_third",
		caption = "[The western ward answers in brass.]",
	},
	ward_east = {
		symbol = "seal",
		material = "iron",
		interval = "perfect_fourth",
		caption = "[The eastern ward turns with a hollow click.]",
	},
	ward_crypt = {
		symbol = "river",
		material = "stone",
		interval = "tritone_resolved",
		caption = "[The buried ward grinds under the floor.]",
	},
})

return table.freeze(Config)
