--!strict

local Manifest = {}

Manifest.SchemaVersion = "205.0.0"
Manifest.AudioIdentity = "The Street That Listens"
Manifest.LicenseVerificationDate = "2026-08-31"
Manifest.Status = table.freeze({
	Candidate = "candidate",
	LicenseVerified = "licenseVerified",
	Downloaded = "downloaded",
	Edited = "edited",
	UserApproved = "userApproved",
	UploadedToRoblox = "uploadedToRoblox",
	ExperiencePermissionGranted = "experiencePermissionGranted",
	StudioAuditionPassed = "studioAuditionPassed",
	FinalApproved = "finalApproved",
	Rejected = "rejected",
	ReplacementRequired = "replacementRequired",
})

Manifest.Candidates = table.freeze({
	{
		internalId = "A1_primary_rain_bed",
		title = "Rain in small city",
		creator = "AudioPapkin",
		sourceUrl = "https://pixabay.com/sound-effects/search/rain%20on%20pavement/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "continuous exterior rain foundation with subtle filtering and unnaturally reduced highs near Blackwater House",
		loopBehavior = "continuous exterior loop only after approval",
		spatialBehavior = "wide exterior bed with occlusion/filter automation",
		caption = "Rain falls across wet stone.",
		accessibilityEquivalent = "pressure vignette and rain-filter indicator",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A2_wet_pavement_steps",
		title = "Walking On Wet Pavement",
		creator = "TommyLynn",
		sourceUrl = "https://pixabay.com/sound-effects/search/rain%20on%20pavement/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "sliceRequired",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "individual wet-stone step variations for walk, sprint, stop, turn, and impossible continuation",
		loopBehavior = "never loop as a full recording",
		spatialBehavior = "player-local foley plus authored impossible-footstep relocation",
		caption = "Wet footsteps continue where they should not.",
		accessibilityEquivalent = "brief directional case-file pulse and pressure text",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A3_period_carriage",
		title = "Horse-Drawn Carriage in Old Town",
		creator = "Alex_Jauk",
		sourceUrl = "https://pixabay.com/sound-effects/search/horse%20carriage/",
		alternativeTitle = "Horses Pavement Then Cobblestone",
		alternativeSourceUrl = "https://pixabay.com/sound-effects/search/cobblestone/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "distant left-to-right Victorian carriage pass and later impossible source-less pass",
		loopBehavior = "one-shot world event",
		spatialBehavior = "travels beyond playable street behind occluding buildings",
		caption = "A carriage passes, but nothing crosses the street.",
		accessibilityEquivalent = "street shadow marker and rain-filter change",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A4_lantern_physicality",
		title = "Oil Lantern Rattle",
		creator = "Unknown Pixabay uploader pending verification",
		sourceUrl = "https://pixabay.com/sound-effects/search/lantern/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "lantern pickup, equipment motion, sudden stop, and one impossible still rattle",
		loopBehavior = "short randomized one-shots",
		spatialBehavior = "player-attached physical detail",
		caption = "The lantern rattles without movement.",
		accessibilityEquivalent = "lantern icon tremor and subtitle",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A5_distant_wrong_bell",
		title = "Old Church Bells (Creepy, Horror, Church Bells)",
		creator = "XomXomski",
		sourceUrl = "https://pixabay.com/sound-effects/search/creepy%20crow/",
		license = "Pixabay Content License candidate; reject if processed or cliche",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "audition only; preferred design is natural distant bell plus delayed thirteenth strike",
		loopBehavior = "one-shot hour motif",
		spatialBehavior = "distant city bell, final strike inside Blackwater House",
		caption = "The bell strikes once too many.",
		accessibilityEquivalent = "subtle ward glyph flash on the thirteenth strike",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A6_distant_dog",
		title = "FIELD - Late Evening Ambience with Distant Dog Barking Recording",
		creator = "Fronbondi_Skegs",
		sourceUrl = "https://pixabay.com/sound-effects/search/suburban%20ambience/",
		alternativeTitle = "Dog Barking In Distant",
		alternativeCreator = "dbsound",
		alternativeSourceUrl = "https://pixabay.com/sound-effects/search/distant-barking/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "life beyond the street that stops when Blackwater notices the party and returns at dawn",
		loopBehavior = "rare distant one-shots or sparse bed only",
		spatialBehavior = "several streets away, never near the player",
		caption = "A distant dog falls silent.",
		accessibilityEquivalent = "living-world status shift in captions",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A7_house_structural_strain",
		title = "Creaking Wood",
		creator = "VoiceBosch",
		sourceUrl = "https://pixabay.com/sound-effects/search/creaking/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "long upper-house strain and breathing-architecture motif ingredient",
		loopBehavior = "rare wind-linked structural one-shot",
		spatialBehavior = "upper facade and gallery-localized",
		caption = "The upper house strains like breath.",
		accessibilityEquivalent = "house silhouette pressure pulse",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A8_heavy_iron_gate",
		title = "Gate-Heavy-OpenClose-WAV",
		creator = "Unknown Pixabay uploader pending verification",
		sourceUrl = "https://pixabay.com/sound-effects/search/gates/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "layerRequired",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "hinge strain, latch release, heavy movement, impact, chain response, threshold moment",
		loopBehavior = "one-shot boundary interaction",
		spatialBehavior = "front gate localized with short street echo",
		caption = "The iron gate opens with too much weight.",
		accessibilityEquivalent = "threshold vignette and objective pulse",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A9_pressure_tone",
		title = "Low Rumble New.2",
		creator = "Unknown Pixabay uploader pending verification",
		sourceUrl = "https://pixabay.com/sound-effects/search/low-rumble/",
		alternativeTitle = "60 Hz low frequency roomtone",
		alternativeSourceUrl = "https://pixabay.com/sound-effects/search/tono%20bajo/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "mobileHarmonicRequired",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "almost-inaudible Blackwater pressure tied to approach, facing, and Glass Heart state",
		loopBehavior = "very low controlled bed only after approval",
		spatialBehavior = "house-proximity pressure, not music",
		caption = "A low pressure settles in the walls.",
		accessibilityEquivalent = "subtle UI pressure meter and color-grade shift",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
	{
		internalId = "A10_restrained_raven",
		title = "Raven solo Call (Horror and Night)",
		creator = "TanwerAman",
		sourceUrl = "https://pixabay.com/sound-effects/search/creepy%20crow/",
		license = "Pixabay Content License candidate; uploader rights and Roblox use still require verification",
		downloadStatus = "notStarted",
		editingStatus = "notStarted",
		robloxUploadStatus = "assetUploadBlocked",
		robloxAssetId = "",
		experiencePermissionStatus = "notStarted",
		intendedGameplayUse = "single restrained call during house reveal and possible later callback",
		loopBehavior = "never loop",
		spatialBehavior = "distant roofline one-shot",
		caption = "A single bird calls from the roofline.",
		accessibilityEquivalent = "brief roofline visual attention cue",
		approvalStatus = "candidate",
		replacementStatus = "replacementRequired",
	},
})

Manifest.ForbiddenSources = table.freeze({
	"Red Dead Redemption",
	"Red Dead Redemption 2",
	"Rockstar Games",
	"Silent Hill",
	"Resident Evil",
	"Alien: Isolation",
	"movies",
	"Spotify",
	"YouTube soundtrack uploads",
	"TikTok",
	"other commercial games",
})

return table.freeze(Manifest)
