--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Asset Governance Certification Runtime Foundation",
		ownerLayer = "AssetGovernanceCertification",
		status = "Foundation",
		responsibilities = {
			"certify governance metadata",
			"verify governance readiness",
			"verify dependency completeness",
			"verify provider consistency",
			"verify runtime ordering",
			"verify integration readiness metadata",
			"expose certification diagnostics",
			"expose certification snapshots",
			"run deterministic self-checks",
			"validate certification metadata before mutation",
		},
		doesNotOwn = {
			"asset loading",
			"asset preloading",
			"asset streaming",
			"asset spawning",
			"asset application",
			"asset playback",
			"execution permission",
			"repair",
			"mutation",
			"orchestration",
			"scheduling",
			"client authority",
			"networking",
			"persistence",
			"gameplay",
			"Presentation",
			"Save",
			"Chapter content",
			"maps",
			"rooms",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
			"Asset Manifest Runtime Foundation",
			"Asset Usage Plan Runtime Foundation",
			"Asset Readiness Review Runtime Foundation",
			"Asset Approval Ledger Runtime Foundation",
			"Asset Execution Permit Runtime Foundation",
			"Asset Runtime Gate Runtime Foundation",
			"Asset Execution Boundary Review Runtime Foundation",
			"Asset Execution Design Contract Runtime Foundation",
			"Asset Execution Implementation Readiness Runtime Foundation",
			"Asset Execution Implementation Contract Runtime Foundation",
			"Asset Governance Integration Runtime Foundation",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"certification metadata only",
			"certification records do not authorize execution",
			"future execution certification must be separate and governed",
		},
		clientPresentation = {
			allowed = false,
			description = "Asset Governance Certification Runtime creates no remotes, client presentation, client authority, UI, or execution controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "AssetGovernanceCertificationCoordinator.inspect" },
		snapshotProviders = { "assetGovernanceCertificationRuntime" },
		cleanupBehavior = {
			"shutdown clears certifications, requirements, results, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Asset Governance Certification schemas only",
			"clients cannot define certification truth or gain execution authority through this runtime",
			"duplicate ids reject before mutation",
			"unsafe payloads reject before state changes",
		},
		failureModes = {
			"malformed certification, requirement, result, and audit records reject",
			"unsupported certification, requirement, result, and audit enum values reject",
			"missing certification references reject",
			"forbidden loading, execution, storage, remote, client, service, analytics, telemetry, Chapter, map, room, dialogue, cutscene, callback, listener, module reference, orchestration, scheduling, and execution adapter markers reject",
			"serialization rejects Roblox Instances, instance-shaped tables, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		documentation = {
			"ASSET_GOVERNANCE_CERTIFICATION_RUNTIME.md",
			"ASSET_GOVERNANCE_CERTIFICATION_VALIDATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_SERIALIZATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DIAGNOSTICS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_SELF_CHECKS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_RUNTIME_LIMITS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_AUDIT.md",
			"ASSET_GOVERNANCE_CERTIFICATION_PRODUCTION_REVIEW.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_READINESS.md",
			"GOVERNANCE_CERTIFICATION_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_REQUIREMENT_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_RESULT_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_AUDIT_RUNTIME.md",
		},
		tags = {
			"asset-governance-certification",
			"server",
			"foundation",
			"certification",
			"read-only",
			"schema-only",
			"metadata-only",
			"no-execution-permission",
			"no-asset-loading",
			"no-client-authority",
			"no-remotes",
		},
	},
	{
		systemName = "Asset Governance Certification Integration Runtime Foundation",
		ownerLayer = "AssetGovernanceCertificationIntegration",
		status = "Foundation",
		responsibilities = {
			"coordinate copied certification metadata",
			"coordinate copied dependency metadata",
			"coordinate copied readiness metadata",
			"coordinate copied provider metadata",
			"coordinate copied Bootstrap metadata",
			"coordinate copied documentation metadata",
			"coordinate copied compatibility metadata",
			"validate certification integration metadata before mutation",
			"expose certification integration diagnostics",
			"expose certification integration snapshots",
			"run deterministic self-checks",
			"prove future integration readiness with copied compatibility metadata",
			"production-harden exact integration readiness declarations",
		},
		doesNotOwn = {
			"asset loading",
			"asset preloading",
			"asset streaming",
			"asset spawning",
			"asset application",
			"asset playback",
			"execution permission",
			"authorization",
			"repair",
			"mutation",
			"live runtime inspection",
			"orchestration",
			"scheduling",
			"client authority",
			"networking",
			"persistence",
			"gameplay",
			"Presentation",
			"Save",
			"Chapter content",
			"maps",
			"rooms",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
			"Asset Manifest Runtime Foundation",
			"Asset Usage Plan Runtime Foundation",
			"Asset Readiness Review Runtime Foundation",
			"Asset Approval Ledger Runtime Foundation",
			"Asset Execution Permit Runtime Foundation",
			"Asset Runtime Gate Runtime Foundation",
			"Asset Execution Boundary Review Runtime Foundation",
			"Asset Execution Design Contract Runtime Foundation",
			"Asset Execution Implementation Readiness Runtime Foundation",
			"Asset Execution Implementation Contract Runtime Foundation",
			"Asset Governance Integration Runtime Foundation",
			"Asset Governance Certification Runtime Foundation",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"certification integration metadata only",
			"copied metadata coordination does not authorize execution",
			"future live inspection must be separate and governed",
		},
		clientPresentation = {
			allowed = false,
			description = "Asset Governance Certification Integration Runtime creates no remotes, client presentation, client authority, UI, or execution controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "AssetGovernanceCertificationIntegrationCoordinator.inspect" },
		snapshotProviders = { "assetGovernanceCertificationIntegrationRuntime" },
		cleanupBehavior = {
			"shutdown clears integrations, chains, reviews, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Asset Governance Certification Integration schemas only",
			"clients cannot define certification coordination truth or gain execution authority through this runtime",
			"duplicate ids reject before mutation",
			"unsafe payloads reject before state changes",
		},
		failureModes = {
			"malformed integration, chain, review, and audit records reject",
			"unsupported integration, chain, review, and audit enum values reject",
			"invalid provider, dependency, runtime, coordinator, Bootstrap, documentation, and readiness metadata reject",
			"forbidden loading, execution, storage, remote, client, service, analytics, telemetry, Chapter, map, room, dialogue, cutscene, callback, listener, module reference, orchestration, scheduling, live inspection, and repair markers reject",
			"serialization rejects Roblox Instances, instance-shaped tables, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		documentation = {
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_RUNTIME.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_VALIDATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_SERIALIZATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_DIAGNOSTICS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_SELF_CHECKS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_RUNTIME_LIMITS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_AUDIT.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INTEGRATION_PRODUCTION_REVIEW.md",
			"GOVERNANCE_CERTIFICATION_INTEGRATION_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_INTEGRATION_CHAIN_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_INTEGRATION_REVIEW_RUNTIME.md",
			"GOVERNANCE_CERTIFICATION_INTEGRATION_AUDIT_RUNTIME.md",
		},
		tags = {
			"asset-governance-certification-integration",
			"server",
			"foundation",
			"certification-integration",
			"read-only",
			"schema-only",
			"metadata-only",
			"no-live-inspection",
			"no-execution-permission",
			"no-asset-loading",
			"no-client-authority",
			"no-remotes",
		},
	},
	{
		systemName = "Asset Governance Certification Live Inspection Runtime Foundation",
		ownerLayer = "AssetGovernanceCertificationInspection",
		status = "Foundation",
		responsibilities = {
			"observe copied runtime health metadata",
			"compare copied certification evidence",
			"report inspection findings",
			"expose copied decision-readiness evidence for future governed decision systems",
			"harden decision-readiness declaration exactness without adding decision authority",
			"validate inspection metadata before mutation",
			"expose inspection diagnostics",
			"expose inspection snapshots",
			"run deterministic self-checks",
		},
		doesNotOwn = {
			"repair",
			"decision-making",
			"authorization",
			"execution",
			"orchestration",
			"scheduling",
			"mutation",
			"live subsystem state",
			"mutable runtime references",
			"asset loading",
			"asset preloading",
			"asset streaming",
			"asset spawning",
			"asset application",
			"asset playback",
			"client authority",
			"networking",
			"persistence",
			"gameplay",
			"Presentation",
			"Save",
			"Chapter content",
			"maps",
			"rooms",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
			"Asset Manifest Runtime Foundation",
			"Asset Usage Plan Runtime Foundation",
			"Asset Readiness Review Runtime Foundation",
			"Asset Approval Ledger Runtime Foundation",
			"Asset Execution Permit Runtime Foundation",
			"Asset Runtime Gate Runtime Foundation",
			"Asset Execution Boundary Review Runtime Foundation",
			"Asset Execution Design Contract Runtime Foundation",
			"Asset Execution Implementation Readiness Runtime Foundation",
			"Asset Execution Implementation Contract Runtime Foundation",
			"Asset Governance Integration Runtime Foundation",
			"Asset Governance Certification Runtime Foundation",
			"Asset Governance Certification Integration Runtime Foundation",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"inspection metadata only",
			"decision-readiness evidence does not decide",
			"copied health comparison does not authorize execution",
			"findings are reports and never repair orders",
		},
		clientPresentation = {
			allowed = false,
			description = "Asset Governance Certification Live Inspection Runtime creates no remotes, client presentation, client authority, UI, or execution controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "AssetGovernanceCertificationInspectionCoordinator.inspect" },
		snapshotProviders = { "assetGovernanceCertificationInspectionRuntime" },
		cleanupBehavior = {
			"shutdown clears inspections, observations, findings, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Asset Governance Certification Inspection schemas only",
			"clients cannot define inspection truth or gain execution authority through this runtime",
			"duplicate ids reject before mutation",
			"unsafe payloads reject before state changes",
			"copied diagnostics and snapshots remain isolated from mutable runtime state",
		},
		failureModes = {
			"malformed inspection, observation, finding, and audit records reject",
			"unsupported inspection, observation, finding, finding severity, finding status, audit, and health enum values reject",
			"invalid runtime, provider, and snapshot provider metadata rejects",
			"invalid integration readiness metadata rejects",
			"invalid decision readiness metadata rejects",
			"exact integration readiness declaration mismatches reject",
			"exact decision readiness declaration mismatches reject",
			"duplicate integration compatibility declarations reject",
			"duplicate decision readiness, compatibility, and declaration ids reject",
			"duplicate decision documentation, Bootstrap, and Governance compatibility metadata reject",
			"missing inspection, observation, and finding references reject",
			"forbidden loading, execution, storage, remote, client, service, analytics, telemetry, Chapter, map, room, dialogue, cutscene, callback, listener, module reference, orchestration, scheduling, authorization, mutation, and repair markers reject",
			"serialization rejects Roblox Instances, instance-shaped tables, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		documentation = {
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_DECISION_READINESS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_INTEGRATION_READINESS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_RUNTIME.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_VALIDATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_SERIALIZATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_DIAGNOSTICS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_SELF_CHECKS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_RUNTIME_LIMITS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_AUDIT.md",
			"ASSET_GOVERNANCE_CERTIFICATION_INSPECTION_PRODUCTION_REVIEW.md",
			"GOVERNANCE_INSPECTION_RUNTIME.md",
			"GOVERNANCE_INSPECTION_OBSERVATION_RUNTIME.md",
			"GOVERNANCE_INSPECTION_FINDING_RUNTIME.md",
			"GOVERNANCE_INSPECTION_AUDIT_RUNTIME.md",
		},
		tags = {
			"asset-governance-certification-inspection",
			"server",
			"foundation",
			"live-inspection",
			"read-only",
			"metadata-only",
			"health-only",
			"no-repair",
			"no-authorization",
			"no-execution",
			"no-orchestration",
			"no-scheduling",
			"no-client-authority",
			"no-remotes",
		},
	},
	{
		systemName = "Asset Governance Certification Decision Runtime Foundation",
		ownerLayer = "AssetGovernanceCertificationDecision",
		status = "Foundation",
		responsibilities = {
			"evaluate copied governance metadata",
			"produce deterministic decision metadata",
			"track decision requirements",
			"track decision evaluations",
			"track decision audits",
			"expose copied integration-readiness metadata",
			"harden exact integration-readiness ordering evidence",
			"own copied future governed execution-readiness declarations",
			"validate execution-readiness compatibility metadata",
			"validate exact execution-readiness declaration order",
			"expose execution-readiness diagnostics posture",
			"expose isolated execution-readiness snapshots",
			"harden Future Governed Execution Readiness as evidence only",
			"prove separation between readiness evidence and authority",
			"preserve separation between readiness, governance, authorization, and execution",
			"validate decision metadata before mutation",
			"expose decision diagnostics",
			"expose decision snapshots",
			"run deterministic self-checks",
		},
		doesNotOwn = {
			"asset loading",
			"asset preloading",
			"asset streaming",
			"asset spawning",
			"asset application",
			"asset playback",
			"UI",
			"VFX",
			"remotes",
			"client authority",
			"DataStore",
			"HTTP",
			"MessagingService",
			"analytics",
			"telemetry",
			"Workspace mutation",
			"storage mutation",
			"gameplay execution",
			"Presentation execution",
			"Save execution",
			"Chapter content",
			"maps",
			"rooms",
			"dialogue",
			"cutscenes",
			"authorization",
			"approval authority",
			"rejection authority",
			"repair",
			"execution authorization",
			"execution approval",
			"operational rejection",
			"execution permission",
			"execution tokens",
			"authority tokens",
			"execution routing",
			"runtime dispatch",
			"message buses",
			"event routing",
			"scheduler queues",
			"execution queues",
			"repair queues",
			"orchestration",
			"scheduling",
			"live subsystem state",
			"mutable runtime references",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
			"Asset Manifest Runtime Foundation",
			"Asset Usage Plan Runtime Foundation",
			"Asset Readiness Review Runtime Foundation",
			"Asset Approval Ledger Runtime Foundation",
			"Asset Execution Permit Runtime Foundation",
			"Asset Runtime Gate Runtime Foundation",
			"Asset Execution Boundary Review Runtime Foundation",
			"Asset Execution Design Contract Runtime Foundation",
			"Asset Execution Implementation Readiness Runtime Foundation",
			"Asset Execution Implementation Contract Runtime Foundation",
			"Asset Governance Integration Runtime Foundation",
			"Asset Governance Certification Runtime Foundation",
			"Asset Governance Certification Integration Runtime Foundation",
			"Asset Governance Certification Live Inspection Runtime Foundation",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"decision metadata only",
			"evaluations are not commands",
			"decision records do not authorize execution",
			"decision records do not repair or schedule runtime work",
			"integration-readiness declarations are compatibility evidence only",
			"execution-readiness declarations are prerequisite evidence only",
			"ExecutionReady status is not authorization",
		},
		clientPresentation = {
			allowed = false,
			description = "Asset Governance Certification Decision Runtime creates no remotes, client presentation, client authority, UI, execution controls, authorization controls, repair controls, orchestration controls, or scheduling controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "AssetGovernanceCertificationDecisionCoordinator.inspect" },
		snapshotProviders = { "assetGovernanceCertificationDecisionRuntime" },
		cleanupBehavior = {
			"shutdown clears decisions, requirements, evaluations, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Asset Governance Certification Decision schemas only",
			"clients cannot define decision metadata truth or gain execution authority through this runtime",
			"duplicate ids reject before mutation",
			"unsafe payloads reject before state changes",
			"copied diagnostics and snapshots remain isolated from mutable runtime state",
		},
		failureModes = {
			"malformed decision, requirement, evaluation, and audit records reject",
			"unsupported decision, requirement, evaluation, and audit enum values reject",
			"invalid runtime, provider, and snapshot provider metadata rejects",
			"duplicate global ids reject before mutation",
			"missing decision, requirement, evaluation, and audit references reject",
			"invalid integration readiness declarations reject",
			"invalid integration readiness ordering rejects",
			"duplicate integration ids, compatibility ids, runtime ids, provider ids, and snapshot ids reject",
			"duplicate integration coordinator ids, diagnostics provider ids, Bootstrap ids, Governance ids, and documentation references reject",
			"unsafe integration readiness evidence, tags, and metadata reject",
			"invalid execution-readiness declarations reject",
			"execution-readiness declaration drift rejects",
			"execution-readiness ordering drift rejects",
			"execution-readiness provider drift rejects",
			"execution-readiness snapshot drift rejects",
			"execution-readiness coordinator drift rejects",
			"execution-readiness diagnostics drift rejects",
			"execution-readiness Bootstrap drift rejects",
			"execution-readiness Governance drift rejects",
			"execution-readiness documentation drift rejects",
			"execution-readiness Decision Runtime drift rejects",
			"duplicate execution-readiness ids, compatibility ids, declaration ids, runtime ids, provider ids, snapshot ids, coordinator ids, diagnostics provider ids, Bootstrap ids, Governance ids, and documentation references reject",
			"partial and extra execution-readiness declarations reject",
			"authority-surface contamination rejects",
			"unsafe execution-readiness evidence, tags, and metadata reject",
			"forbidden loading, execution, storage, remote, client, service, analytics, telemetry, Chapter, map, room, dialogue, cutscene, callback, listener, module reference, decision engine, authorization, approval handler, rejection handler, orchestration, scheduling, mutation, and repair markers reject",
			"serialization rejects Roblox Instances, instance-shaped tables, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		documentation = {
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_RUNTIME.md",
			"GOVERNANCE_DECISION_RUNTIME.md",
			"GOVERNANCE_DECISION_REQUIREMENT_RUNTIME.md",
			"GOVERNANCE_DECISION_EVALUATION_RUNTIME.md",
			"GOVERNANCE_DECISION_AUDIT_RUNTIME.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_VALIDATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_SERIALIZATION.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_DIAGNOSTICS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_SELF_CHECKS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_RUNTIME_LIMITS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_PRODUCTION_REVIEW.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_INTEGRATION_READINESS.md",
			"ASSET_GOVERNANCE_CERTIFICATION_DECISION_EXECUTION_READINESS.md",
		},
		tags = {
			"asset-governance-certification-decision",
			"server",
			"foundation",
			"decision-metadata",
			"integration-ready",
			"execution-readiness",
			"read-only",
			"schema-only",
			"metadata-only",
			"health-only",
			"no-authorization",
			"no-approval-authority",
			"no-rejection-authority",
			"no-repair",
			"no-execution",
			"no-orchestration",
			"no-scheduling",
			"no-mutation",
			"no-client-authority",
			"no-remotes",
		},
	},
}

return contracts
