--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Chapter 0 Home Vertical Slice",
		ownerLayer = "ChapterContent",
		status = "Production",
		responsibilities = {
			"Chapter 0 Home entry point",
			"bounded Home environment ownership",
			"player start state",
			"Home interaction progression",
			"server-approved atmospheric feedback plans",
			"deterministic environmental reaction state",
			"exact environmental reaction attribute schema",
			"deterministic atmospheric progression ownership",
			"canonical atmospheric progression stage and transition definitions",
			"exact atmospheric progression stage schema",
			"exact atmospheric progression transition schema",
			"exact atmospheric progression reference bindings",
			"deterministic atmospheric progression sequencing",
			"bounded per-player atmospheric progression state",
			"idempotent atmospheric progression transition handling",
			"canonical Chapter 0 Home observation fact schema",
			"exact Chapter 0 Home observation contract version",
			"exact Chapter 0 Home observation source runtime identity",
			"exact Chapter 0 Home server authority marker",
			"canonical observation source-reference bindings",
			"server-authoritative observation fact emission",
			"bounded per-player observation integration history",
			"deterministic observation sequence",
			"deterministic observation fact deduplication",
			"duplicate observation publication prevention",
			"optional observation non-blocking guarantees",
			"read-only Observation Runtime integration boundary",
			"Phase 118 Studio-only certification review entry point",
			"structured certification evidence for Chapter 0 observation integration",
			"exact Phase 118 certification evidence schema ownership",
			"exact Phase 118 certification decision ownership",
			"Studio-only explicit-gate certification execution",
			"certification concurrency and recursive-run rejection",
			"certification result validation hardening",
			"Phase 120 certification evidence artifact ownership",
			"truthful authoritative Studio execution availability reporting",
			"exact source attribution preflight for certification evidence",
			"failed or blocked certification evidence preservation",
			"truthful certification decision boundaries",
			"Phase 121 local Studio evidence capture command ownership",
			"deterministic certification evidence JSON and Markdown transport",
			"stable certification wrapper exit-code reporting",
			"Phase 122 Studio automation bridge ownership",
			"Studio installation discovery and version identifier reporting",
			"supported Studio execution method classification",
			"bridge status forwarding into certification evidence transport",
			"Phase 123 structured capture method detection",
			"structured capture transport envelope validation",
			"invalid, partial, and corrupt capture rejection",
			"Phase 124 Studio MCP activation prerequisite evaluation",
			"MCP activation refusal before unsupported runner invocation",
			"activation diagnostics forwarding into evidence transport",
			"Phase 125 documented Studio MCP runner command binding detection",
			"connected Studio MCP session availability classification",
			"unsupported runner binding refusal before runner invocation",
			"Phase 129 Studio MCP integration contract ownership",
			"Studio MCP protocol version, handshake, capability, envelope, serialization, diagnostics, and compatibility validation",
			"Phase 130 Studio MCP capability negotiation authority ownership",
			"Studio MCP capability advertisement, dependency, conflict, negotiated profile, diagnostics, and audit validation",
			"Phase 131 Studio MCP execution readiness authority ownership",
			"Studio MCP prerequisite aggregation, readiness decision, readiness profile, diagnostics, and audit validation",
			"Phase 132 Studio MCP execution planning authority ownership",
			"Studio MCP execution graph, checkpoint, plan, diagnostics, and audit validation",
			"Phase 133 Studio MCP execution orchestrator ownership",
			"Studio MCP orchestration graph, execution context, retry, cancellation, diagnostics, and audit validation",
			"Phase 134 Studio MCP execution request authority ownership",
			"Studio MCP execution request lifecycle, schema, intent, diagnostics, and audit validation",
			"Phase 135 Studio MCP execution dispatch authority ownership",
			"Studio MCP execution dispatch lifecycle, eligibility, schema, diagnostics, and audit validation",
			"Phase 136 Studio MCP external execution boundary authority ownership",
			"Studio MCP external handoff package, external-consumer contract, ownership-transfer, diagnostics, and audit validation",
			"deterministic Chapter 0 reset",
			"Chapter 0 diagnostics and snapshots",
		},
		doesNotOwn = {
			"new remotes",
			"client-owned gameplay truth",
			"DataStore writes",
			"analytics",
			"telemetry",
			"Monster AI",
			"Chapter 1 content",
			"final apartment art",
			"final audio",
			"final dialogue voiceover",
			"cutscenes",
			"certification gameplay authority",
			"certification networking ownership",
			"certification persistence ownership",
			"certification client authority",
			"certification Observation Runtime authority",
			"certification source of gameplay truth",
			"alternate certification decision engine",
			"non-interactive Roblox Studio execution API invention",
			"manual runtime-result editing workflow",
			"launch-only Studio CLI treated as certification evidence",
			"Studio automation bridge certification authority",
			"structured capture result synthesis",
			"Studio MCP command presence treated as certification evidence",
			"MCP activation without repository opt-in",
			"undocumented MCP runner command invocation",
			"runner command synthesis",
			"connected Studio MCP session fabrication",
			"connected Studio MCP session inference from installation, MCP command names, or repository configuration",
			"Studio MCP runner lifecycle ownership outside the Runner Authority",
			"runner execution request treated as Studio execution evidence",
			"Runner Authority contract version drift",
			"Runner Authority diagnostics drift",
			"Runner Authority audit mutation",
			"Studio MCP protocol behavior outside the Integration Contract",
			"Studio MCP capability inference from installation, command presence, or configuration",
			"Studio MCP networking transport implementation",
			"Studio MCP runtime evidence generation",
			"Studio MCP capability negotiation outside the Capability Negotiation Authority",
			"Studio MCP optional capability promotion to mandatory behavior",
			"implicit Studio MCP conflict resolution",
			"mutable Studio MCP negotiated capability profiles",
			"Studio MCP execution readiness decisions outside the Execution Readiness Authority",
			"Studio MCP execution invocation from readiness evaluation",
			"Studio MCP readiness inferred from partial upstream authority state",
			"mutable Studio MCP readiness profiles",
			"Studio MCP execution planning outside the Execution Planning Authority",
			"Studio MCP execution invocation from execution planning",
			"Studio MCP runtime evidence generation from execution planning",
			"mutable Studio MCP execution plans, graphs, or checkpoints",
			"Studio MCP execution orchestration outside the Execution Orchestrator",
			"Studio MCP execution invocation from execution orchestration",
			"Studio MCP runtime evidence generation from execution orchestration",
			"mutable Studio MCP orchestration graphs, contexts, retry policies, or cancellation policies",
			"Studio MCP execution requests outside the Execution Request Authority",
			"Studio MCP execution invocation from execution request publication",
			"Studio MCP runtime evidence generation from execution request publication",
			"mutable Studio MCP execution requests",
			"Studio MCP execution dispatch outside the Execution Dispatch Authority",
			"Studio MCP execution invocation from dispatch publication",
			"Studio MCP runtime evidence generation from dispatch publication",
			"mutable Studio MCP execution dispatch artifacts",
			"Studio MCP external handoff publication outside the External Execution Boundary Authority",
			"Studio execution from the External Execution Boundary Authority",
			"Runner invocation from the External Execution Boundary Authority",
			"transport creation from the External Execution Boundary Authority",
			"MCP communication from the External Execution Boundary Authority",
			"Studio MCP runtime evidence generation from boundary publication",
			"Studio MCP certification decisions from boundary publication",
			"mutable Studio MCP external boundary packages",
			"fabricated Studio MCP external consumer identities",
			"fabricated Studio MCP ownership transfer",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Player Runtime",
			"Interaction Runtime",
			"Objective Runtime",
			"Narrative Runtime",
			"Presentation Runtime",
			"World Intelligence",
		},
		observationsEmitted = {
			{
				id = "Interaction.Begin",
				when = "existing PlayerExperience interaction loop accepts a Chapter 0 interaction",
				required = true,
			},
			{
				id = "Interaction.Complete",
				when = "existing PlayerExperience interaction loop completes a Chapter 0 interaction",
				required = true,
			},
			{
				id = "Interaction.ReadNote",
				when = "player reads the Chapter 0 Home note",
				required = true,
			},
			{
				id = "Interaction.ToggleSwitch",
				when = "player toggles the Chapter 0 Home lamp",
				required = true,
			},
			{
				id = "Interaction.CollectibleFound",
				when = "player collects Marmalade's ribbon",
				required = true,
			},
			{
				id = "Chapter0Home.AtmosphericFeedbackRecorded",
				when = "server records a Chapter 0 atmospheric feedback plan",
				required = true,
			},
			{
				id = "Chapter0Home.EnvironmentalReactionApplied",
				when = "server applies a deterministic Chapter 0 environmental reaction",
				required = true,
			},
			{
				id = "Chapter0Home.AtmosphericProgressionAdvanced",
				when = "server advances deterministic Chapter 0 atmospheric progression",
				required = true,
			},
			{
				id = "Chapter0Home.ObservationFactPublished",
				when = "server publishes a validated Chapter 0 observation fact",
				required = true,
			},
		},
		directorApprovalsRequired = {},
		executionPermissions = {
			{
				action = "create and reset Workspace.Chapter0Home owned test environment",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "send bounded server-approved atmospheric feedback through Player Experience",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "apply deterministic environmental reaction attributes inside Workspace.Chapter0Home",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "project scalar environmental reaction metadata to owned instance attributes",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "advance deterministic per-player atmospheric progression state",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish validated Chapter 0 observation facts through Observation.Submitted",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "run Studio-gated certification review when explicit Phase 118 test gate is present",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate isolated Phase 118 certification evidence without gameplay mutation",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "record bounded Phase 120 certification evidence availability without gameplay mutation",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "write local ignored certification evidence transport artifacts without gameplay mutation",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "classify Studio automation bridge availability without invoking unsupported execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate structured capture transport envelope without duplicating certification logic",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "evaluate Studio MCP activation prerequisites without invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "detect documented Studio MCP runner command binding without invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate connected Studio MCP session identity without invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "classify future Studio MCP runner lifecycle requests without invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate hardened Studio MCP Runner Authority contract without invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate Studio MCP integration contract compatibility without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate Studio MCP capability negotiation without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "validate Studio MCP execution readiness without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish Studio MCP execution plans without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish Studio MCP execution orchestration without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish Studio MCP execution requests without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish Studio MCP execution dispatch artifacts without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish Studio MCP external execution boundary handoff packages without implementing transport or invoking unsupported runner execution",
				requiresApproval = false,
				approval = nil,
			},
			{
				action = "publish descriptive Studio MCP external-consumer contracts without discovering or connecting to an external consumer",
				requiresApproval = false,
				approval = nil,
			},
		},
		clientPresentation = {
			allowed = true,
			description = "Clients may render server-approved prompts and feedback from the existing Player Experience remotes.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "Chapter0HomeCoordinator.inspect" },
		snapshotProviders = { "chapter0Home" },
		cleanupBehavior = {
			"destroy Workspace.Chapter0Home on shutdown",
			"disconnect Chapter 0 interaction listeners",
			"clear per-player Chapter 0 progress",
			"clear per-player atmospheric feedback history",
			"clear per-player environmental reaction history",
			"clear per-player atmospheric progression state",
			"clear per-player observation integration history",
			"clear temporary Phase 118 certification gate and active-run marker",
			"clear only owned Phase 118 certification Workspace attributes",
			"preserve unowned Workspace content with the same name",
		},
		multiplayerGuarantees = {
			"progress is server-owned per player",
			"client requests are validated by existing Player Experience remotes",
			"Chapter 0 reset is deterministic and scoped to its owned folder",
			"per-player progress and history growth are bounded",
			"atmospheric feedback history is server-owned per player",
			"environmental reaction history is server-owned per player",
			"environmental reaction attribute names are deterministic review surfaces",
			"atmospheric progression state is server-owned per player",
			"optional atmospheric progression modifiers are non-blocking",
			"failed atmospheric progression validation cannot mutate state",
			"out-of-order atmospheric progression transitions cannot advance state",
			"diagnostics and snapshots expose isolated progression evidence only",
			"observation facts publish only after server-approved Chapter 0 state",
			"observation integration history is bounded and per-player isolated",
			"Observation Runtime cannot mutate Chapter0Home state",
			"failed observation validation cannot mutate state",
			"repeated observation emission is idempotent",
			"Phase 118 certification runner has no gameplay or networking authority",
			"Phase 118 Production Certification cannot be claimed without actual Studio execution",
			"Phase 118 certification decisions use a single contract function",
			"Phase 118 certification evidence rejects schema and suite-order drift",
			"Phase 118 certification active marker rejects concurrent and recursive runs",
			"Phase 120 certification evidence does not certify without Studio execution",
			"Phase 120 certification scope remains exact and non-overclaiming",
			"Phase 121 capture command cannot certify without authoritative Studio structured evidence",
			"Phase 121 evidence transport preserves exact source attribution",
			"Phase 122 bridge cannot certify without authoritative Studio structured evidence",
			"Phase 122 bridge preserves Phase 121 evidence format and exit codes",
			"Phase 123 structured capture cannot certify without authoritative Studio structured evidence",
			"Phase 123 capture forwarding preserves source attribution",
			"Phase 124 activation cannot invoke runner unless all prerequisites pass",
			"Phase 124 activation cannot certify from MCP command presence alone",
			"Phase 125 binding cannot invoke runner without connected documented MCP command",
			"Phase 125 binding cannot certify from configured command names alone",
			"Phase 126 session authority cannot infer connection from Studio installation, MCP command names, or repository configuration",
			"Phase 126 session validation preserves executionBlocked when no connected session identity is visible",
			"Phase 127 Runner Authority owns runner lifecycle orchestration only",
			"Phase 127 Runner Authority cannot transition to Ready unless every upstream authority is actually ready",
			"Phase 128 Runner Authority contract version, diagnostics, lifecycle, timeout, retry, cancellation, and audit schemas are frozen",
			"Phase 128 Runner Authority preserves runnerInvoked false and structuredResultCaptured false while upstream authorities are blocked",
			"Phase 129 Studio MCP Integration Contract owns protocol definition only",
			"Phase 129 Studio MCP Integration Contract cannot infer capabilities from Studio installation, MCP command names, or repository configuration",
			"Phase 129 Studio MCP Integration Contract preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 130 Capability Negotiation Authority owns dynamic capability negotiation only",
			"Phase 130 Capability Negotiation Authority cannot modify the Phase 129 protocol definition",
			"Phase 130 Capability Negotiation Authority preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 131 Execution Readiness Authority owns readiness decisions only",
			"Phase 131 Execution Readiness Authority cannot execute Studio or invoke the runner",
			"Phase 131 Execution Readiness Authority preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 132 Execution Planning Authority owns execution planning only",
			"Phase 132 Execution Planning Authority cannot execute Studio or invoke the runner",
			"Phase 132 Execution Planning Authority preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 133 Execution Orchestrator owns orchestration only",
			"Phase 133 Execution Orchestrator cannot execute Studio or invoke the runner",
			"Phase 133 Execution Orchestrator preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 134 Execution Request Authority owns request publication only",
			"Phase 134 Execution Request Authority cannot execute Studio or invoke the runner",
			"Phase 134 Execution Request Authority preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 135 Execution Dispatch Authority owns dispatch preparation only",
			"Phase 135 Execution Dispatch Authority cannot execute Studio or invoke the runner",
			"Phase 135 Execution Dispatch Authority preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 136 External Execution Boundary owns repository/external ownership boundary metadata only",
			"Phase 136 External Execution Boundary cannot execute Studio, invoke the runner, create transport, or communicate with MCP",
			"Phase 136 External Execution Boundary preserves executionBlocked, runnerInvoked false, and structuredResultCaptured false",
			"Phase 136 External Execution Boundary cannot fabricate external consumer identity or ownership transfer",
			"Phase 137 External Consumer Contract Authority owns external consumer contract schema, compatibility policy, evolution policy, diagnostics, and audit only",
			"Phase 137 External Consumer Contract Authority may publish immutable repository-owned future consumer contract definitions",
			"Phase 137 External Consumer Contract Authority cannot discover consumers, connect to consumers, create credentials, create transport, execute Studio, invoke the runner, synthesize acknowledgements, synthesize structured results, synthesize runtime evidence, transfer ownership, or decide certification",
			"Phase 137 External Consumer Contract Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, boundaryEligibility Blocked, and ownershipTransferState RepositoryOwned",
			"Phase 138 External Consumer Manifest Authority owns repository-managed consumer manifest identity, versioning, catalog, compatibility matrix, diagnostics, audit, publication, and evolution policy only",
			"Phase 138 External Consumer Manifest Authority may publish immutable repository-recognized future consumer manifest metadata",
			"Phase 138 External Consumer Manifest Authority cannot discover consumers, connect to consumers, create transport, execute Studio, invoke the runner, synthesize acknowledgements, synthesize structured results, synthesize runtime evidence, transfer ownership, or decide certification",
			"Phase 138 External Consumer Manifest Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, ContractOnly consumer availability, and DefinitionCompatible compatibility",
			"Phase 139 Consumer Compatibility Authority owns deterministic candidate-profile evaluation, component evaluation, compatibility result publication, diagnostics, and audit only",
			"Phase 139 Consumer Compatibility Authority consumes Phase 137 policy and Phase 138 manifest declarations read-only",
			"Phase 139 Consumer Compatibility Authority cannot define compatibility policy, mutate manifests, discover consumers, connect to consumers, authenticate, create transport, communicate with MCP, execute Studio, invoke the runner, synthesize acknowledgements, synthesize structured results, synthesize runtime evidence, transfer ownership, or decide certification",
			"Phase 139 Consumer Compatibility Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, boundaryEligibility Blocked, ownershipTransferState RepositoryOwned, and no connected consumer claim",
			"Phase 140 External Execution Envelope Authority owns immutable external execution envelope aggregation, snapshot publication, correlation validation, envelope eligibility, diagnostics, and audit only",
			"Phase 140 External Execution Envelope Authority consumes upstream execution, boundary, contract, manifest, and compatibility artifacts read-only",
			"Phase 140 External Execution Envelope Authority cannot mutate upstream artifacts, transmit envelopes, discover consumers, connect to consumers, authenticate, create transport, communicate with MCP, execute Studio, invoke the runner, synthesize acknowledgements, synthesize structured results, synthesize runtime evidence, transfer ownership, or decide certification",
			"Phase 140 External Execution Envelope Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, boundaryEligibility Blocked, ownershipTransferState RepositoryOwned, CandidateDeclared consumer availability, and DefinitionCompleteButUnavailable envelope eligibility",
			"Phase 141 External Envelope Transport Contract Authority owns immutable transport contract identity, delivery contract, acknowledgement contract, retry contract, transport capability contract, transport error contract, diagnostics, audit, and publication only",
			"Phase 141 External Envelope Transport Contract Authority consumes the Phase 140 execution envelope read-only",
			"Phase 141 External Envelope Transport Contract Authority cannot implement HTTP, TCP, UDP, WebSockets, sockets, MCP communication, authentication, endpoint discovery, transport execution, Studio execution, Runner invocation, envelope transmission, acknowledgement reception, runtime evidence, or certification",
			"Phase 141 External Envelope Transport Contract Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, TransportContractPublished, TransportUnavailable, and no transport implementation",
			"Phase 142 External Envelope Transport Capability Authority owns immutable capability identity, supported upstream version declarations, capability classification, diagnostics, audit, and publication only",
			"Phase 142 External Envelope Transport Capability Authority consumes the Phase 141 transport contract and Phase 140 execution envelope read-only",
			"Phase 142 External Envelope Transport Capability Authority cannot implement networking, HTTP, TCP, UDP, sockets, MCP communication, authentication, endpoint discovery, transport implementation, transmission, Studio execution, Runner invocation, runtime evidence, or certification",
			"Phase 142 External Envelope Transport Capability Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, CapabilityProfilePublished, and DefinitionOnly capability classification",
			"Phase 143 External Transport Compatibility Authority owns declaration-level transport compatibility evaluation, correlation snapshots, component results, overall compatibility, transport availability classification, execution eligibility classification, diagnostics, audit, and immutable publication only",
			"Phase 143 External Transport Compatibility Authority consumes Phase 141 transport contracts and Phase 142 capability profiles read-only without mutating upstream ownership",
			"Phase 143 External Transport Compatibility Authority cannot mutate transport contracts, mutate capability profiles, verify implementations, fabricate transport availability, discover endpoints, use networking, authenticate, handle credentials, create transport, transmit envelopes, receive acknowledgements, communicate with MCP, execute Studio, invoke the Runner, synthesize structured results, generate runtime evidence, decide certification, mutate gameplay, persist data, emit analytics, or emit telemetry",
			"Phase 143 External Transport Compatibility Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, TransportCompatibilityPublished, CompatibleDefinition, TransportUnavailable, and DefinitionCompatibleButUnavailable",
			"Phase 144 External Transport Implementation Contract Authority owns implementation contract identity, lifecycle contract, checkpoint contract, failure contract, implementation boundary contract, readiness classification, diagnostics, audit, and immutable publication only",
			"Phase 144 External Transport Implementation Contract Authority consumes Phases 140 through 143 read-only without mutating upstream ownership",
			"Phase 144 External Transport Implementation Contract Authority cannot mutate upstream authorities, discover real implementations, dynamically load implementation code, execute processes, use networking, discover endpoints, authenticate, handle credentials, create transport, transmit envelopes, receive acknowledgements, communicate with MCP, execute Studio, invoke the Runner, synthesize structured results, generate runtime evidence, decide certification, mutate gameplay, persist data, emit analytics, or emit telemetry",
			"Phase 144 External Transport Implementation Contract Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, ImplementationContractPublished, DefinitionOnly, CompatibleDefinition, TransportUnavailable, and DefinitionCompatibleButUnavailable",
			"Phase 145 External Transport Implementation Readiness Authority owns readiness evaluation identity, implementation contract correlation, prerequisite readiness, lifecycle readiness, checkpoint readiness, failure-contract readiness, boundary readiness, overall implementation readiness, future validation eligibility, diagnostics, audit, and immutable publication only",
			"Phase 145 External Transport Implementation Readiness Authority consumes Phases 140 through 144 read-only without mutating upstream ownership",
			"Phase 145 External Transport Implementation Readiness Authority cannot mutate upstream authorities, discover implementations, inspect implementations, dynamically load implementation code, execute processes, use networking, discover endpoints, authenticate, authorize, handle credentials, create transport, transmit envelopes, receive acknowledgements, communicate with MCP, execute Studio, invoke the Runner, synthesize structured results, generate runtime evidence, decide certification, mutate gameplay, persist data, emit analytics, or emit telemetry",
			"Phase 145 External Transport Implementation Readiness Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, ImplementationReadinessPublished, StructurallyReadyDefinition, DefinitionEligibleForFutureValidation, ImplementationContractPublished, DefinitionOnly, CompatibleDefinition, TransportUnavailable, and DefinitionCompatibleButUnavailable",
			"Phase 146 External Transport Implementation Validation Authority owns validation evaluation identity, readiness evaluation correlation, validation checkpoint definitions, validation prerequisite definitions, validation boundary definitions, validation classification, diagnostics, audit, and immutable publication only",
			"Phase 146 External Transport Implementation Validation Authority consumes Phase 145 readiness read-only without mutating upstream ownership",
			"Phase 146 External Transport Implementation Validation Authority cannot mutate upstream authorities, discover implementations, inspect implementations, load implementation code, execute transport, use networking, discover endpoints, authenticate, handle credentials, create transport, transmit envelopes, receive acknowledgements, communicate with MCP, execute Studio, invoke the Runner, generate runtime evidence, decide certification, mutate gameplay, persist data, emit analytics, or emit telemetry",
			"Phase 146 External Transport Implementation Validation Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, ImplementationValidationPublished, DefinitionOnly, and DefinitionEligibleForVerification",
			"Phase 147 External Transport Implementation Verification Authority owns verification evaluation identity, validation evaluation correlation, verification checkpoint definitions, verification prerequisite definitions, verification boundary definitions, verification classification, diagnostics, audit, and immutable publication only",
			"Phase 147 External Transport Implementation Verification Authority consumes Phase 146 validation definitions read-only without mutating upstream ownership",
			"Phase 147 External Transport Implementation Verification Authority cannot mutate upstream authorities, discover implementations, inspect implementations, load implementation code, execute transport, use networking, discover endpoints, authenticate, handle credentials, create transport, transmit envelopes, receive acknowledgements, communicate with MCP, execute Studio, invoke the Runner, generate runtime evidence, decide certification, mutate gameplay, persist data, emit analytics, or emit telemetry",
			"Phase 147 External Transport Implementation Verification Authority preserves executionBlocked, runnerInvoked false, structuredResultCaptured false, transportCreated false, envelopeTransmitted false, acknowledgementReceived false, ImplementationVerificationPublished, DefinitionOnly, and DefinitionEligibleForExecutionPlanning",
		},
		failureModes = {
			"invalid Chapter 0 definitions refuse startup",
			"unknown interaction references reject during validation",
			"unknown feedback interaction references reject during validation",
			"unsafe feedback metadata rejects before mutation",
			"unknown environmental reaction references reject during validation",
			"invalid environmental reaction targets reject during validation",
			"unsafe environmental reaction metadata rejects before mutation",
			"environmental reaction definition and metadata limits reject before mutation",
			"invalid atmospheric progression definitions reject before mutation",
			"unknown atmospheric progression references reject before mutation",
			"exact atmospheric progression schema drift rejects before mutation",
			"unknown atmospheric progression transitions reject before mutation",
			"out-of-order atmospheric progression transitions reject before mutation",
			"optional interactions cannot become mandatory atmospheric progression gates",
			"invalid observation definitions reject before mutation or publication",
			"duplicate observation facts reject before mutation or publication",
			"observation facts with unknown references reject before mutation or publication",
			"malformed certification evidence rejects before Production Certification",
			"runtime-unavailable certification evidence cannot pass",
			"blocked Studio evidence capture preserves Production Candidate status",
			"invalid source attribution blocks Production Certification",
			"unsupported Studio automation reports executionBlocked",
			"runtime-unavailable capture reports runtimeUnavailable",
			"capture wrapper source mismatch reports sourceAttributionInvalid",
			"launch-only Studio support reports executionBlocked",
			"unsupported bridge request reports sourceAttributionInvalid or validation failure",
			"missing configured capture method reports executionBlocked",
			"invalid structured capture reports validationFailed",
			"missing MCP activation opt-in reports executionBlocked",
			"missing structured runner command binding reports executionBlocked",
			"missing connected Studio MCP session reports executionBlocked",
			"missing documented runner command reports executionBlocked",
			"unsupported connected Studio MCP session identity reports executionBlocked",
			"invalid connected Studio MCP session protocol reports executionBlocked",
			"blocked Runner Authority request reports executionBlocked",
			"expired Runner Authority request reports timedOut without invoking Studio",
			"unsupported Runner Authority contract version rejects before orchestration",
			"illegal Runner Authority transition rejects before orchestration",
			"Runner Authority audit drift rejects before orchestration",
			"unsupported Studio MCP protocol version rejects before communication",
			"unsupported Studio MCP contract version rejects before communication",
			"missing Studio MCP required capability reports executionBlocked",
			"invalid Studio MCP handshake transition rejects before communication",
			"invalid Studio MCP envelope schema rejects before communication",
			"invalid Studio MCP serialization rejects before communication",
			"invalid Studio MCP source attribution reports executionBlocked",
			"invalid Studio MCP capability advertisement rejects before negotiation completes",
			"missing mandatory Studio MCP capability rejects before negotiation completes",
			"deprecated Studio MCP capability rejects before negotiation completes",
			"missing Studio MCP capability dependency rejects before negotiation completes",
			"circular Studio MCP capability dependency rejects before negotiation completes",
			"declared Studio MCP capability conflict rejects before negotiation completes",
			"mutable Studio MCP negotiated profile rejects before publication",
			"missing Studio MCP readiness authority reports MissingAuthority",
			"blocked Studio MCP readiness prerequisite reports ExecutionBlocked",
			"invalid Studio MCP readiness profile rejects before readiness publication",
			"unsupported Studio MCP readiness blocking reason rejects before readiness publication",
			"duplicate Studio MCP readiness audit identity rejects before readiness publication",
			"missing Studio MCP planning authority reports MissingAuthority",
			"invalid Studio MCP execution graph rejects before plan publication",
			"duplicate Studio MCP planning identifiers reject before plan publication",
			"mutable Studio MCP execution plan rejects before plan publication",
			"duplicate Studio MCP planning audit identity rejects before plan publication",
			"missing Studio MCP orchestration authority reports MissingExecutionPlan",
			"invalid Studio MCP orchestration graph rejects before orchestration publication",
			"invalid Studio MCP execution context rejects before orchestration publication",
			"invalid Studio MCP retry policy rejects before orchestration publication",
			"invalid Studio MCP cancellation policy rejects before orchestration publication",
			"duplicate Studio MCP orchestration audit identity rejects before orchestration publication",
			"missing Studio MCP request authority reports InvalidInput",
			"invalid Studio MCP execution request schema rejects before request publication",
			"duplicate Studio MCP request identifiers reject before request publication",
			"invalid Studio MCP execution intent rejects before request publication",
			"duplicate Studio MCP request audit identity rejects before request publication",
			"missing Studio MCP dispatch authority reports MissingExecutionRequest",
			"invalid Studio MCP execution dispatch schema rejects before dispatch publication",
			"duplicate Studio MCP dispatch identifiers reject before dispatch publication",
			"invalid Studio MCP dispatch eligibility rejects before dispatch publication",
			"duplicate Studio MCP dispatch audit identity rejects before dispatch publication",
			"missing Studio MCP external boundary dispatch reports MissingDispatch",
			"invalid Studio MCP external boundary package schema rejects before boundary publication",
			"duplicate Studio MCP boundary correlation identifiers reject before boundary publication",
			"invalid Studio MCP boundary eligibility or ownership pairing rejects before boundary publication",
			"invalid Studio MCP external consumer contract rejects before boundary publication",
			"duplicate Studio MCP boundary audit identity rejects before boundary publication",
			"missing Studio MCP external boundary contract reports MissingBoundaryContract",
			"invalid Studio MCP external consumer authority contract schema rejects before publication",
			"invalid Studio MCP external consumer acknowledgement, structured-result, runtime-evidence, correlation, failure, or compatibility-policy schema rejects before publication",
			"invalid Studio MCP external consumer contract lifecycle transition rejects before publication",
			"unsupported Studio MCP external consumer type rejects before publication",
			"duplicate Studio MCP external consumer contract audit identity rejects before publication",
			"mutable Studio MCP external consumer contract rejects before publication",
			"missing Studio MCP external consumer contract reports MissingConsumerContract",
			"invalid Studio MCP external consumer manifest schema rejects before publication",
			"invalid Studio MCP external consumer catalog rejects before publication",
			"invalid Studio MCP external consumer compatibility matrix rejects before publication",
			"duplicate Studio MCP external consumer manifest identifiers reject before publication",
			"duplicate Studio MCP external consumer manifest audit identity rejects before publication",
			"mutable Studio MCP external consumer manifest rejects before publication",
			"missing Studio MCP consumer compatibility candidate profile reports MissingCandidateProfile",
			"invalid Studio MCP consumer compatibility candidate schema rejects before evaluation",
			"invalid Studio MCP consumer compatibility component schema rejects before publication",
			"unrecognized Studio MCP consumer manifest evaluates as incompatible without claiming discovery",
			"retired Studio MCP consumer manifest entry evaluates as incompatible",
			"duplicate Studio MCP consumer compatibility audit identity rejects before publication",
			"mutable Studio MCP consumer compatibility evaluation rejects before publication",
			"missing Studio MCP external execution envelope compatibility evaluation reports MissingCompatibilityEvaluation",
			"invalid Studio MCP external execution envelope upstream artifacts reject before publication",
			"invalid Studio MCP external execution envelope correlation rejects before publication",
			"invalid Studio MCP external execution envelope snapshot schema rejects before publication",
			"future Studio MCP external transport readiness claims reject in Phase 140",
			"duplicate Studio MCP external execution envelope audit identity rejects before publication",
			"mutable Studio MCP external execution envelope rejects before publication",
			"missing Studio MCP external envelope transport contract envelope reports MissingExecutionEnvelope",
			"invalid Studio MCP external envelope transport contract schema rejects before publication",
			"invalid Studio MCP external envelope delivery, acknowledgement, retry, error, or capability contract rejects before publication",
			"duplicate Studio MCP external envelope transport contract identity rejects before publication",
			"mutable Studio MCP external envelope transport contract rejects before publication",
			"Studio MCP external envelope transport contract publication reports TransportUnavailable without transport execution",
			"missing Studio MCP external envelope transport capability contract reports MissingTransportContract",
			"invalid Studio MCP external envelope transport capability schema rejects before publication",
			"invalid Studio MCP external envelope transport capability version declaration rejects before publication",
			"ImplementationVerified Studio MCP external envelope transport capability classification rejects in Phase 142",
			"duplicate Studio MCP external envelope transport capability identity rejects before publication",
			"mutable Studio MCP external envelope transport capability rejects before publication",
			"missing Studio MCP external transport compatibility transport contract reports MissingTransportContract",
			"missing Studio MCP external transport compatibility capability profile reports MissingCapabilityProfile",
			"invalid Studio MCP external transport compatibility correlation rejects before publication",
			"invalid Studio MCP external transport compatibility component result rejects before publication",
			"TransportAvailable Studio MCP external transport compatibility classification rejects in Phase 143",
			"duplicate Studio MCP external transport compatibility audit identity rejects before publication",
			"mutable Studio MCP external transport compatibility evaluation rejects before publication",
			"missing Studio MCP external transport implementation contract compatibility evaluation reports MissingCompatibilityEvaluation",
			"invalid Studio MCP external transport implementation contract schema rejects before publication",
			"invalid Studio MCP external transport implementation lifecycle, checkpoint, failure, or boundary contract rejects before publication",
			"future readiness or implementation validated classification rejects in Phase 144",
			"duplicate Studio MCP external transport implementation contract audit identity rejects before publication",
			"mutable Studio MCP external transport implementation contract rejects before publication",
			"missing Studio MCP external transport implementation contract reports MissingImplementationContract",
			"invalid Studio MCP external transport implementation readiness schema rejects before publication",
			"invalid Studio MCP external transport implementation readiness correlation rejects before publication",
			"invalid Studio MCP external transport implementation lifecycle, checkpoint, failure-contract, or boundary readiness rejects before publication",
			"transport availability or executable eligibility claims reject before Phase 145 readiness publication",
			"duplicate Studio MCP external transport implementation readiness audit identity rejects before publication",
			"mutable Studio MCP external transport implementation readiness evaluation rejects before publication",
			"missing Studio MCP external transport implementation readiness evaluation reports MissingReadinessEvaluation",
			"invalid Studio MCP external transport implementation validation definition schema rejects before publication",
			"invalid Studio MCP external transport implementation validation checkpoint, prerequisite, or boundary definition rejects before publication",
			"unsupported Studio MCP external transport implementation validation or future verification classification rejects before publication",
			"duplicate Studio MCP external transport implementation validation identifiers reject before publication",
			"duplicate Studio MCP external transport implementation validation audit identity rejects before publication",
			"mutable Studio MCP external transport implementation validation definition rejects before publication",
			"missing Studio MCP external transport implementation validation definition reports MissingValidationDefinition",
			"invalid Studio MCP external transport implementation verification definition schema rejects before publication",
			"invalid Studio MCP external transport implementation verification checkpoint, prerequisite, or boundary definition rejects before publication",
			"unsupported Studio MCP external transport implementation verification or future execution classification rejects before publication",
			"duplicate Studio MCP external transport implementation verification identifiers reject before publication",
			"duplicate Studio MCP external transport implementation verification audit identity rejects before publication",
			"mutable Studio MCP external transport implementation verification definition rejects before publication",
			"certification cleanup failure is classified separately",
			"workspace reset destroys only the owned Chapter0Home folder",
			"unowned duplicate Chapter0Home folders block reset instead of being overwritten",
		},
		documentation = {
			"CHAPTER_0_HOME_RUNTIME.md",
			"CHAPTER_0_HOME_VALIDATION.md",
			"CHAPTER_0_HOME_DIAGNOSTICS.md",
			"CHAPTER_0_HOME_SELF_CHECKS.md",
			"CHAPTER_0_HOME_PRODUCTION_REVIEW.md",
			"CHAPTER_0_HOME_CERTIFICATION.md",
			"CHAPTER_0_HOME_PHASE_121_STUDIO_EVIDENCE_CAPTURE.md",
			"CHAPTER_0_HOME_PHASE_122_STUDIO_AUTOMATION_BRIDGE.md",
			"CHAPTER_0_HOME_PHASE_123_STRUCTURED_RESULT_CAPTURE.md",
			"CHAPTER_0_HOME_PHASE_124_STUDIO_MCP_ACTIVATION.md",
			"CHAPTER_0_HOME_PHASE_125_STUDIO_MCP_RUNNER_BINDING.md",
			"CHAPTER_0_HOME_PHASE_126_CONNECTED_STUDIO_MCP_SESSION.md",
			"CHAPTER_0_HOME_PHASE_127_STUDIO_MCP_RUNNER_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_128_STUDIO_MCP_RUNNER_AUTHORITY_HARDENING.md",
			"CHAPTER_0_HOME_PHASE_129_STUDIO_MCP_INTEGRATION_CONTRACT.md",
			"CHAPTER_0_HOME_PHASE_130_STUDIO_CAPABILITY_NEGOTIATION_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_131_STUDIO_EXECUTION_READINESS_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_132_STUDIO_EXECUTION_PLANNING_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_133_STUDIO_EXECUTION_ORCHESTRATOR.md",
			"CHAPTER_0_HOME_PHASE_134_STUDIO_EXECUTION_REQUEST_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_135_STUDIO_EXECUTION_DISPATCH_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_136_STUDIO_EXTERNAL_EXECUTION_BOUNDARY.md",
			"CHAPTER_0_HOME_PHASE_137_STUDIO_EXTERNAL_CONSUMER_CONTRACT_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_138_STUDIO_EXTERNAL_CONSUMER_MANIFEST_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_139_STUDIO_CONSUMER_COMPATIBILITY_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_140_STUDIO_EXTERNAL_EXECUTION_ENVELOPE_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_141_STUDIO_EXTERNAL_ENVELOPE_TRANSPORT_CONTRACT_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_142_STUDIO_EXTERNAL_ENVELOPE_TRANSPORT_CAPABILITY_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_143_STUDIO_EXTERNAL_TRANSPORT_COMPATIBILITY_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_144_STUDIO_EXTERNAL_TRANSPORT_IMPLEMENTATION_CONTRACT_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_145_STUDIO_EXTERNAL_TRANSPORT_IMPLEMENTATION_READINESS_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_146_STUDIO_EXTERNAL_TRANSPORT_IMPLEMENTATION_VALIDATION_AUTHORITY.md",
			"CHAPTER_0_HOME_PHASE_147_STUDIO_EXTERNAL_TRANSPORT_IMPLEMENTATION_VERIFICATION_AUTHORITY.md",
		},
		tags = { "chapter-0", "home", "vertical-slice", "server", "content" },
	},
}

return contracts
