--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Player Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"player lifecycle state",
			"movement state hooks",
			"lock state",
			"room area chapter hooks",
			"player diagnostics",
		},
		doesNotOwn = {
			"client camera presentation",
			"interaction execution",
			"horror pacing",
			"save persistence",
			"Monster AI",
		},
		dependencies = { "Core Runtime", "Observation Engine" },
		observationsEmitted = {
			{ id = "Movement.Walk", when = "server accepts player walking state", required = true },
			{ id = "Movement.StartSprint", when = "server accepts sprint state", required = true },
			{ id = "Movement.StopSprint", when = "server detects sprint release", required = true },
			{ id = "Movement.Jump", when = "server accepts jump state", required = true },
			{ id = "Movement.Land", when = "server detects airborne release", required = true },
			{ id = "Movement.Crouch", when = "server accepts crouch state", required = true },
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Clients may request movement intent and render local movement presentation.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "PlayerService.inspect", "PlayerControllerService.inspect" },
		snapshotProviders = { "playerRuntime" },
		cleanupBehavior = {
			"disconnect player lifecycle signals",
			"clear per-player runtime state",
		},
		multiplayerGuarantees = {
			"server-owned lifecycle state",
			"per-player state cleanup on leave",
			"movement requests are validated before observations",
		},
		failureModes = {
			"safe default state for joining players",
			"movement profiles fall back to defaults",
		},
		documentation = { "PLAYER_EXPERIENCE.md", "PLAYER_RUNTIME.md" },
		tags = { "gameplay", "player", "runtime" },
	},
	{
		systemName = "Interaction Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"interaction validation",
			"interactable registration",
			"interaction state",
			"object execution handoff",
			"feedback routing",
		},
		doesNotOwn = {
			"client-owned interaction truth",
			"inventory persistence",
			"puzzle answers",
			"horror pacing",
			"final UI art",
		},
		dependencies = { "Core Runtime", "Observation Engine", "RemoteManager", "Player Runtime" },
		observationsEmitted = {
			{
				id = "Interaction.Begin",
				when = "server accepts interaction attempt",
				required = true,
			},
			{ id = "Interaction.Complete", when = "server completes interaction", required = true },
			{ id = "Interaction.Cancel", when = "interaction is cancelled", required = true },
			{ id = "Interaction.Fail", when = "server rejects interaction", required = true },
			{
				id = "Interaction.OpenDoor",
				when = "server applies door interaction",
				required = true,
			},
			{
				id = "Interaction.ReadNote",
				when = "server accepts note interaction",
				required = true,
			},
		},
		directorApprovalsRequired = {},
		executionPermissions = {
			{
				action = "apply reusable object interaction state after validation",
				requiresApproval = false,
				approval = nil,
			},
		},
		clientPresentation = {
			allowed = true,
			description = "Clients may render prompts and approved feedback instructions only.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "InteractionService.inspect" },
		snapshotProviders = { "playerExperience.interactions" },
		cleanupBehavior = {
			"disconnect CollectionService signals through PlayerExperienceService",
			"clear interaction state and feedback state on shutdown",
		},
		multiplayerGuarantees = {
			"server-authoritative range validation",
			"server-authoritative line-of-sight validation",
			"RemoteManager rate limits",
		},
		failureModes = {
			"reject malformed requests",
			"reject disabled or locked interactions",
			"fail closed when interactable config is invalid",
		},
		documentation = { "INTERACTION_RUNTIME.md", "INTERACTION_FRAMEWORK.md" },
		tags = { "gameplay", "interaction", "runtime" },
	},
	{
		systemName = "Lantern Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"server-owned lantern equipped state",
			"server-owned lantern on/off state",
			"battery and fuel hooks",
			"lantern overuse tracking",
			"lantern observations",
			"presentation-hook remotes",
		},
		doesNotOwn = {
			"final lighting effects",
			"final audio playback",
			"client-owned lantern truth",
			"Chapter 1 content",
			"Monster AI",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"RemoteManager",
			"Lighting Director",
			"Audio Director",
			"World Intelligence",
		},
		observationsEmitted = {
			{ id = "Lantern.Equipped", when = "server equips lantern", required = true },
			{ id = "Lantern.Unequipped", when = "server unequips lantern", required = true },
			{ id = "Lantern.TurnedOn", when = "server accepts lantern on", required = true },
			{ id = "Lantern.TurnedOff", when = "server accepts lantern off", required = true },
			{ id = "Lantern.LowBattery", when = "battery hook crosses threshold", required = true },
			{
				id = "Lantern.Overused",
				when = "lantern overuse crosses threshold",
				required = true,
			},
		},
		directorApprovalsRequired = {
			{
				director = "Lighting",
				reason = "Lantern presentation pressure must be approved before future execution.",
				requiredFor = { "future lantern lighting presentation" },
			},
			{
				director = "Audio",
				reason = "Lantern overuse audio pressure must be approved before future playback.",
				requiredFor = { "future lantern overuse audio presentation" },
			},
		},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Client may request toggle and render server-approved presentation hooks only.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "LanternService.inspect" },
		snapshotProviders = { "lanternService" },
		cleanupBehavior = {
			"disconnect lantern remotes",
			"clear per-player lantern state",
		},
		multiplayerGuarantees = {
			"server-owned lantern truth",
			"RemoteManager rate limits",
			"per-player cleanup on leave",
		},
		failureModes = {
			"malformed toggle requests are rejected",
			"unequipped lantern cannot toggle",
			"Director requests are approval-only",
		},
		documentation = { "LANTERN_SYSTEM.md", "LANTERN_DARKNESS_REVIEW.md" },
		tags = { "gameplay", "lantern", "server" },
	},
	{
		systemName = "Darkness Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"server-owned darkness exposure truth",
			"safe-room darkness protection",
			"puzzle-room readability protection",
			"darkness observations",
			"Director request hooks",
		},
		doesNotOwn = {
			"client-owned darkness truth",
			"final lighting effects",
			"final audio playback",
			"Chapter 1 content",
			"Monster AI",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"Lighting Director",
			"Audio Director",
			"Environment Director",
			"World Intelligence",
		},
		observationsEmitted = {
			{ id = "Darkness.Entered", when = "server detects darkness entry", required = true },
			{ id = "Darkness.Exited", when = "server detects darkness exit", required = true },
			{
				id = "Darkness.ExposureIncreased",
				when = "server exposure score increases",
				required = true,
			},
			{
				id = "Darkness.ProtectedZone",
				when = "unknown, safe, or puzzle zone suppresses darkness pressure",
				required = true,
			},
		},
		directorApprovalsRequired = {
			{
				director = "Lighting",
				reason = "Darkness sensory pressure requires Lighting Director approval.",
				requiredFor = { "future darkness visibility pressure" },
			},
			{
				director = "Audio",
				reason = "Darkness audio pressure requires Audio Director approval.",
				requiredFor = { "future darkness heartbeat or breathing pressure" },
			},
			{
				director = "Environment",
				reason = "Darkness environmental pressure requires Environment Director approval.",
				requiredFor = { "future darkness room pressure" },
			},
		},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may present server-approved darkness feedback only.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "DarknessService.inspect" },
		snapshotProviders = { "darknessService" },
		cleanupBehavior = {
			"cancel exposure update task",
			"clear per-player exposure state",
		},
		multiplayerGuarantees = {
			"server-owned exposure truth",
			"per-player cleanup on leave",
			"unknown zones fail protected",
		},
		failureModes = {
			"unknown zones suppress hostile pressure",
			"safe rooms suppress hostile pressure",
			"puzzle rooms protect readability",
		},
		documentation = { "DARKNESS_SYSTEM.md", "LANTERN_DARKNESS_REVIEW.md" },
		tags = { "gameplay", "darkness", "server" },
	},
	{
		systemName = "Gameplay Intelligence Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"coordinate reusable gameplay truth modules",
			"expose gameplay diagnostics and snapshots",
			"preserve data-driven gameplay architecture",
			"validate runtime self-checks",
		},
		doesNotOwn = {
			"Chapter 1 content",
			"Monster AI",
			"final UI or art",
			"horror pacing",
			"Workspace mutation",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"World Intelligence",
		},
		observationsEmitted = {
			{
				id = "Gameplay.ObjectInteracted",
				when = "object runtime accepts interaction",
				required = true,
			},
			{
				id = "Gameplay.ObjectStateChanged",
				when = "object runtime changes state",
				required = true,
			},
		},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Gameplay pressure hooks require Director approval before future execution.",
				requiredFor = { "future object or puzzle pressure presentation" },
			},
		},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may present server-approved gameplay state only.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "GameplayCoordinator.inspect" },
		snapshotProviders = { "gameplayIntelligence" },
		cleanupBehavior = { "clear all runtime registries, state, and gameplay memory on shutdown" },
		multiplayerGuarantees = {
			"server owns gameplay truth",
			"client cannot create inventory, key, door, objective, or puzzle truth",
			"runtime state is data-only and reusable",
		},
		failureModes = {
			"duplicate ids reject",
			"missing dependencies reject",
			"invalid state transitions reject",
		},
		documentation = { "GAMEPLAY_INTELLIGENCE.md", "GAMEPLAY_DIAGNOSTICS.md" },
		tags = { "gameplay", "intelligence", "server" },
	},
	{
		systemName = "Object Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"register reusable object definitions",
			"track object state truth",
			"validate allowed states",
			"expose object diagnostics",
		},
		doesNotOwn = {
			"physical objects",
			"animations",
			"Chapter 1 object scripts",
			"horror pacing",
		},
		dependencies = { "Gameplay Intelligence Runtime", "Observation Engine" },
		observationsEmitted = {
			{
				id = "Gameplay.ObjectInteracted",
				when = "server records interaction",
				required = true,
			},
			{
				id = "Gameplay.ObjectStateChanged",
				when = "server changes object state",
				required = true,
			},
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may display prompts from server object state.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ObjectRuntime.inspect" },
		snapshotProviders = { "gameplayIntelligence.objects" },
		cleanupBehavior = { "clear object registry and state on shutdown" },
		multiplayerGuarantees = { "server-owned object state", "duplicate object ids reject" },
		failureModes = { "unknown objects reject", "invalid states reject" },
		documentation = { "OBJECT_RUNTIME.md" },
		tags = { "gameplay", "objects", "server" },
	},
	{
		systemName = "Gameplay Execution Bridge",
		ownerLayer = "Execution",
		status = "Production",
		responsibilities = {
			"validate server-owned execution requests",
			"queue future physical and presentation execution safely",
			"route approved requests to opt-in adapters",
			"enforce dry-run or disabled default mode",
			"expose execution diagnostics and snapshots",
		},
		doesNotOwn = {
			"gameplay truth",
			"client remotes",
			"Chapter 1 content",
			"Monster AI",
			"final UI, art, sounds, or scares",
			"horror pacing decisions",
		},
		dependencies = {
			"Core Runtime",
			"Gameplay Intelligence Runtime",
			"Director Ecosystem Foundation",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Major future environmental execution requires Director approval metadata before routing.",
				requiredFor = {
					"environmental object response",
					"puzzle panel feedback",
					"objective marker presentation",
				},
			},
		},
		executionPermissions = {
			{
				action = "Route approved gameplay execution hooks to registered adapters only",
				requiresApproval = true,
				approval = "Environment",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Execution Bridge is server-only and creates no client remotes.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "GameplayExecutionService.inspect" },
		snapshotProviders = { "gameplayExecutionBridge" },
		cleanupBehavior = {
			"cancel cleanup task",
			"clear queue, locks, adapters, and execution records on shutdown",
		},
		multiplayerGuarantees = {
			"per-object lock foundation prevents overlapping execution leases",
			"duplicate execution ids reject",
			"failed or rejected execution does not alter gameplay truth",
		},
		failureModes = {
			"unknown execution kinds reject",
			"missing target objects reject",
			"expired requests reject or expire from queue",
			"missing adapter defers safely unless dry-run applies without mutation",
		},
		documentation = {
			"GAMEPLAY_EXECUTION_BRIDGE.md",
			"EXECUTION_SAFETY.md",
			"EXECUTION_CONTRACTS.md",
		},
		tags = { "gameplay", "execution", "server", "bridge" },
	},
	{
		systemName = "Save Journal Identity Runtime",
		ownerLayer = "Saving",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative profile foundation state",
			"own reusable checkpoint schemas without temporary pressure",
			"own journal unlock truth as schemas, not final UI or prose",
			"own memory fragment unlock truth as data schemas",
			"own bounded identity percentage truth",
			"record replay meaning schemas for future interpretation",
			"expose diagnostics, snapshots, validation, serialization, and self-checks",
		},
		doesNotOwn = {
			"client-owned progress",
			"final Journal UI",
			"final memories",
			"final story dialogue",
			"narrative canon writing",
			"Chapter 0 content",
			"Chapter 1 content",
			"cutscenes",
			"horror pacing",
			"Monster AI",
			"Workspace mutation",
			"client remotes",
			"DataStore production persistence",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Gameplay Intelligence Runtime",
			"Living Cognition Runtime",
			"Governance",
		},
		observationsEmitted = {
			{
				id = "Save.ProfileCreated",
				when = "server creates a save profile foundation record",
				required = true,
			},
			{
				id = "Save.CheckpointCreated",
				when = "server creates a safe checkpoint schema",
				required = true,
			},
			{
				id = "Journal.EntryUnlocked",
				when = "server unlocks a journal schema entry",
				required = true,
			},
			{
				id = "MemoryFragment.Unlocked",
				when = "server unlocks a memory fragment schema",
				required = true,
			},
			{
				id = "Identity.Changed",
				when = "server changes bounded identity percentage",
				required = true,
			},
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Save / Journal / Identity runtime owns server truth only; clients may present approved state in a later UI phase.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "SaveCoordinator.inspect" },
		snapshotProviders = { "saveJournalIdentity" },
		cleanupBehavior = {
			"clear profiles, checkpoints, journal entries, memory fragments, identity state, replay state, and validation failures on shutdown",
		},
		multiplayerGuarantees = {
			"server-authoritative save truth only",
			"no client-owned progress accepted",
			"duplicate profile, journal entry, and memory fragment ids reject",
			"identity percentage remains bounded 0 to 100",
		},
		failureModes = {
			"unknown profiles reject",
			"invalid checkpoints reject",
			"unsafe client-like payloads reject",
			"unsafe runtime values reject",
			"temporary horror pressure cannot be checkpointed",
		},
		documentation = {
			"SAVE_JOURNAL_IDENTITY_RUNTIME.md",
			"JOURNAL_RUNTIME.md",
			"MEMORY_FRAGMENT_RUNTIME.md",
			"IDENTITY_RUNTIME.md",
			"CHECKPOINT_RUNTIME.md",
			"SAVE_SERIALIZATION.md",
			"SAVE_VALIDATION.md",
			"SAVE_DIAGNOSTICS.md",
			"SAVE_AUDIT.md",
			"SAVE_RUNTIME_LIMITS.md",
			"SAVE_SELF_CHECKS.md",
			"SAVE_PRODUCTION_REVIEW.md",
		},
		tags = { "save", "journal", "identity", "server", "foundation" },
	},
	{
		systemName = "Gameplay Execution Bridge Foundation",
		ownerLayer = "GameplayExecution",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative execution request intake",
			"own execution validation and approval verification",
			"own dependency verification schemas",
			"own bounded execution queue records",
			"own dry-run execution planning records",
			"own execution audit records",
			"own execution diagnostics, snapshots, serialization, and self-checks",
			"act as the single future gateway between decision systems and physical/presentation runtimes",
		},
		doesNotOwn = {
			"gameplay execution",
			"Monster AI",
			"Living Cognition",
			"Narrative",
			"Save",
			"horror pacing",
			"Audio",
			"Lighting",
			"UI",
			"player inventory",
			"combat",
			"movement",
			"animation",
			"damage",
			"doors",
			"NPCs",
			"pathfinding",
			"physics",
			"Workspace mutation",
			"Chapter content",
			"story",
			"dialogue",
			"cutscenes",
			"presentation",
			"remotes",
			"client authority",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Living Cognition Runtime",
			"Monster Intelligence Foundation",
			"Narrative Runtime Foundation",
			"Save Journal Identity Runtime",
			"Horror Orchestration Framework",
			"Director Ecosystem",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			"future physical or presentation execution must arrive as approved evidence before this bridge records a dry-run plan",
		},
		executionPermissions = {
			"dry-run records only",
			"no Workspace, Lighting, Audio, UI, movement, combat, damage, animation, pathfinding, or door execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Gameplay Execution Bridge has no client remotes and exposes no client-owned truth.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "GameplayExecutionCoordinator.inspect" },
		snapshotProviders = { "gameplayExecutionBridge" },
		cleanupBehavior = {
			"shutdown clears requests, approvals, dependencies, queue, schedules, audit records, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative execution schemas only",
			"duplicate execution ids reject",
			"duplicate approval ids reject",
			"missing approvals and missing dependencies reject",
			"unsafe payloads reject before queue or dry-run records",
			"clients cannot create, approve, mutate, or execute gameplay through this bridge",
		},
		failureModes = {
			"malformed execution requests reject",
			"expired execution requests reject",
			"unsupported execution types reject",
			"Workspace, Instance, movement, damage, animation, UI, Audio, Lighting, remote, Chapter, story, dialogue, cutscene, Monster AI, and horror pacing fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"queue full requests reject without execution",
		},
		documentation = {
			"GAMEPLAY_EXECUTION_BRIDGE.md",
			"EXECUTION_REQUEST_RUNTIME.md",
			"EXECUTION_APPROVAL_RUNTIME.md",
			"EXECUTION_DEPENDENCY_RUNTIME.md",
			"EXECUTION_QUEUE_RUNTIME.md",
			"EXECUTION_VALIDATION.md",
			"EXECUTION_SERIALIZATION.md",
			"EXECUTION_DIAGNOSTICS.md",
			"EXECUTION_RUNTIME_LIMITS.md",
			"EXECUTION_SELF_CHECKS.md",
			"EXECUTION_AUDIT.md",
			"EXECUTION_PRODUCTION_REVIEW.md",
		},
		tags = {
			"gameplay-execution",
			"server",
			"foundation",
			"dry-run-only",
			"gateway",
		},
	},
	{
		systemName = "Physical Runtime Foundation",
		ownerLayer = "PhysicalRuntime",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative physical object registration",
			"own physical object schemas and identities",
			"own physical schemas only; physical execution remains outside this runtime",
			"own physical object ownership records",
			"own physical reservations and execution lock schemas",
			"own lifecycle state schemas",
			"own transform schemas",
			"own physical runtime diagnostics, snapshots, serialization, validation, and self-checks",
			"provide a single source of truth for future physical object schemas",
		},
		doesNotOwn = {
			"Gameplay",
			"Narrative",
			"Monster AI",
			"Living Cognition",
			"Save",
			"Journal",
			"Identity",
			"Replay",
			"Gameplay Execution",
			"horror pacing",
			"Director logic",
			"UI",
			"Audio",
			"Lighting",
			"Animation",
			"physics simulation",
			"Movement",
			"Navigation",
			"Pathfinding",
			"Combat",
			"Damage",
			"NPC behavior",
			"Doors",
			"Drawers",
			"Interactables",
			"Puzzles",
			"Inventory",
			"Chapter content",
			"Dialogue",
			"Story",
			"Cutscenes",
			"Workspace mutation",
			"client authority",
			"remotes",
			"presentation",
		},
		dependencies = {
			"Core Runtime",
			"Gameplay Execution Bridge Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema registration only",
			"no Workspace, physics, movement, pathfinding, animation, damage, UI, Audio, Lighting, or presentation execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Physical Runtime has no client remotes and accepts no client-owned physical truth.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "PhysicalRuntimeCoordinator.inspect" },
		snapshotProviders = { "physicalRuntime" },
		cleanupBehavior = {
			"shutdown clears physical objects, ownership records, reservations, transforms, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative physical object schema truth only",
			"duplicate physical object ids reject",
			"duplicate reservation ids reject",
			"invalid ownership records reject",
			"unsafe payloads reject before state changes",
			"clients cannot register, mutate, reserve, or execute physical objects through this runtime",
		},
		failureModes = {
			"malformed physical object schemas reject",
			"duplicate object ids reject",
			"invalid object types reject",
			"unknown object updates reject",
			"unknown reservation releases reject",
			"malformed state, lifecycle, and transform schemas reject",
			"duplicate reservations reject",
			"Workspace, Instance, movement, animation, physics, pathfinding, navigation, combat, damage, UI, Audio, Lighting, remote, Chapter, story, dialogue, cutscene, Monster AI, and horror pacing fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"registered objects are bounded",
			"reservations are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, and string length are bounded",
		},
		documentation = {
			"PHYSICAL_RUNTIME.md",
			"PHYSICAL_OBJECT_RUNTIME.md",
			"PHYSICAL_REGISTRATION_RUNTIME.md",
			"PHYSICAL_OWNERSHIP_RUNTIME.md",
			"PHYSICAL_RESERVATION_RUNTIME.md",
			"PHYSICAL_TRANSFORM_RUNTIME.md",
			"PHYSICAL_VALIDATION.md",
			"PHYSICAL_SERIALIZATION.md",
			"PHYSICAL_DIAGNOSTICS.md",
			"PHYSICAL_RUNTIME_LIMITS.md",
			"PHYSICAL_SELF_CHECKS.md",
			"PHYSICAL_PRODUCTION_REVIEW.md",
			"PHYSICAL_AUDIT.md",
		},
		tags = {
			"physical-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-workspace-mutation",
		},
	},
	{
		systemName = "Interaction Runtime Foundation",
		ownerLayer = "Interaction",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative interaction object schemas",
			"own interaction eligibility schemas",
			"own interaction intent records",
			"own interaction lock schemas",
			"own cooldown schemas",
			"own interaction diagnostics, snapshots, serialization, validation, and self-checks",
			"provide schema foundation for future doors, drawers, switches, locks, inspectables, pickups, hiding spots, and puzzle interactables",
		},
		doesNotOwn = {
			"actual door opening",
			"actual drawer movement",
			"item pickup execution",
			"inventory ownership",
			"animation",
			"audio",
			"UI prompts",
			"camera",
			"lighting",
			"Workspace mutation",
			"physics",
			"pathfinding",
			"Monster AI",
			"Narrative",
			"Save",
			"horror pacing",
			"Chapter content",
			"dialogue",
			"story",
			"client authority",
			"remotes",
		},
		dependencies = {
			"Core Runtime",
			"Physical Runtime Foundation",
			"Gameplay Execution Bridge Foundation",
			"Presentation Runtime Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema and intent records only",
			"no door, drawer, pickup, inventory, animation, audio, UI, lighting, Workspace, physics, pathfinding, remote, or client execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Interaction Runtime creates no prompts, remotes, or client-owned interaction truth.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "InteractionCoordinator.inspect" },
		snapshotProviders = { "interactionRuntime" },
		cleanupBehavior = {
			"shutdown clears interaction schemas, eligibility records, intents, locks, cooldowns, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative interaction schemas only",
			"duplicate interaction ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, lock, cool down, or execute interactions through this runtime",
		},
		failureModes = {
			"malformed interaction schemas reject",
			"unsupported interaction types reject",
			"missing physicalObjectId rejects",
			"unsafe eligibility, metadata, and context reject",
			"invalid cooldowns and locks reject",
			"client, remote, Workspace, Instance, animation, audio, UI, lighting, physics, movement, inventory execution, door execution, drawer execution, pickup execution, puzzle completion, Monster AI, Narrative, Save, Horror, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"interaction schemas are bounded",
			"intent records are bounded",
			"locks and cooldowns are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, and string length are bounded",
		},
		documentation = {
			"INTERACTION_RUNTIME.md",
			"INTERACTION_OBJECT_RUNTIME.md",
			"INTERACTION_REGISTRATION_RUNTIME.md",
			"INTERACTION_ELIGIBILITY_RUNTIME.md",
			"INTERACTION_INTENT_RUNTIME.md",
			"INTERACTION_LOCK_RUNTIME.md",
			"INTERACTION_COOLDOWN_RUNTIME.md",
			"INTERACTION_VALIDATION.md",
			"INTERACTION_SERIALIZATION.md",
			"INTERACTION_DIAGNOSTICS.md",
			"INTERACTION_RUNTIME_LIMITS.md",
			"INTERACTION_SELF_CHECKS.md",
			"INTERACTION_AUDIT.md",
			"INTERACTION_PRODUCTION_REVIEW.md",
		},
		tags = {
			"interaction-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-gameplay-execution",
		},
	},
	{
		systemName = "Puzzle Runtime Foundation",
		ownerLayer = "Puzzle",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative puzzle schemas",
			"own puzzle graph and node schemas",
			"own puzzle dependency and condition schemas",
			"own puzzle progress records",
			"own puzzle diagnostics, snapshots, serialization, validation, and self-checks",
			"provide structure for future puzzles without solving or executing them",
		},
		doesNotOwn = {
			"puzzle execution",
			"gameplay",
			"interactions",
			"inventory",
			"Monster AI",
			"Narrative ownership",
			"Save ownership",
			"horror pacing",
			"UI",
			"Audio",
			"Lighting",
			"Camera",
			"animation",
			"Workspace mutation",
			"remotes",
			"client authority",
			"chapter scripting",
			"dialogue",
			"story",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Physical Runtime Foundation",
			"Interaction Runtime Foundation",
			"Gameplay Execution Bridge Foundation",
			"Narrative Runtime Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema and progress records only",
			"no puzzle, gameplay, interaction, inventory, UI, Audio, Lighting, camera, Workspace, remote, or client execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Puzzle Runtime creates no UI, remotes, client truth, or puzzle execution.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "PuzzleCoordinator.inspect" },
		snapshotProviders = { "puzzleRuntime" },
		cleanupBehavior = {
			"shutdown clears puzzle schemas, progress records, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative puzzle schemas only",
			"duplicate puzzle ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, solve, or execute puzzles through this runtime",
		},
		failureModes = {
			"malformed puzzle schemas reject",
			"malformed graphs, duplicate and invalid nodes, duplicate and invalid edges, duplicate and invalid dependencies, and duplicate and invalid conditions reject",
			"malformed, unknown puzzle, and unsafe progress records reject",
			"unsupported puzzle types reject",
			"client, remote, Workspace, Instance, gameplay execution, interaction execution, inventory, door execution, drawer execution, Monster AI, Narrative, Save, Horror, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"puzzle schemas are bounded",
			"graph, node, dependency, and condition counts are bounded",
			"progress records are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, and string length are bounded",
		},
		documentation = {
			"PUZZLE_RUNTIME.md",
			"PUZZLE_DEFINITION_RUNTIME.md",
			"PUZZLE_GRAPH_RUNTIME.md",
			"PUZZLE_CONDITION_RUNTIME.md",
			"PUZZLE_PROGRESS_RUNTIME.md",
			"PUZZLE_DEPENDENCY_RUNTIME.md",
			"PUZZLE_VALIDATION.md",
			"PUZZLE_SERIALIZATION.md",
			"PUZZLE_DIAGNOSTICS.md",
			"PUZZLE_RUNTIME_LIMITS.md",
			"PUZZLE_SELF_CHECKS.md",
			"PUZZLE_AUDIT.md",
			"PUZZLE_PRODUCTION_REVIEW.md",
		},
		tags = {
			"puzzle-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-puzzle-execution",
		},
	},
	{
		systemName = "Inventory Runtime Foundation",
		ownerLayer = "Inventory",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative inventory profile schemas",
			"own inventory item schemas",
			"own slot, ownership, capacity, eligibility, and item state schemas",
			"own inventory diagnostics, snapshots, serialization, validation, and self-checks",
			"provide reusable inventory structure for future chapters without executing item gameplay",
			"reference future Save, Interaction, Puzzle, Physical, and Gameplay Execution schemas by id only",
		},
		doesNotOwn = {
			"item pickup execution",
			"item use execution",
			"door unlocking",
			"puzzle solving",
			"save persistence",
			"final inventory UI",
			"gameplay execution",
			"interaction execution",
			"physical execution",
			"Monster AI",
			"Narrative ownership",
			"Save ownership",
			"horror pacing",
			"UI",
			"Audio",
			"Lighting",
			"Camera",
			"animation",
			"Workspace mutation",
			"remotes",
			"client authority",
			"Chapter content",
			"story",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Physical Runtime Foundation",
			"Interaction Runtime Foundation",
			"Puzzle Runtime Foundation",
			"Gameplay Execution Bridge Foundation",
			"Save Journal Identity Runtime Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no pickup, use, door, puzzle, save persistence, UI, Audio, Lighting, camera, Workspace, remote, client, or Chapter execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Inventory Runtime creates no final inventory UI, remotes, client truth, or item execution.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "InventoryCoordinator.inspect" },
		snapshotProviders = { "inventoryRuntime" },
		cleanupBehavior = {
			"shutdown clears inventory profiles, items, slots, ownership records, capacity schemas, eligibility schemas, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative inventory schemas only",
			"duplicate inventory profile ids reject",
			"duplicate item ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, pick up, use, persist, present, or execute inventory through this runtime",
		},
		failureModes = {
			"malformed profile schemas reject",
			"duplicate profile ids reject",
			"unsupported profile types reject",
			"invalid capacity schemas reject",
			"malformed and duplicate slots reject",
			"malformed item schemas reject",
			"duplicate item ids reject",
			"unsupported item types reject",
			"invalid ownership, eligibility, and item state schemas reject",
			"unsafe metadata, context, and tags reject",
			"client, remote, Workspace, Instance, pickup execution, item use execution, door unlock, puzzle solve, gameplay execution, UI, Audio, Lighting, camera, animation, Monster AI, Narrative, Save, horror pacing, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"inventory profiles are bounded",
			"inventory items are bounded",
			"slot counts are bounded",
			"capacity values are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, tag count, and string length are bounded",
		},
		documentation = {
			"INVENTORY_RUNTIME.md",
			"INVENTORY_PROFILE_RUNTIME.md",
			"INVENTORY_ITEM_RUNTIME.md",
			"INVENTORY_SLOT_RUNTIME.md",
			"INVENTORY_OWNERSHIP_RUNTIME.md",
			"INVENTORY_CAPACITY_RUNTIME.md",
			"INVENTORY_ELIGIBILITY_RUNTIME.md",
			"INVENTORY_VALIDATION.md",
			"INVENTORY_SERIALIZATION.md",
			"INVENTORY_DIAGNOSTICS.md",
			"INVENTORY_RUNTIME_LIMITS.md",
			"INVENTORY_SELF_CHECKS.md",
			"INVENTORY_AUDIT.md",
			"INVENTORY_PRODUCTION_REVIEW.md",
		},
		tags = {
			"inventory-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-item-execution",
			"no-remotes",
		},
	},
	{
		systemName = "World Runtime Foundation",
		ownerLayer = "World",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative district schemas",
			"own region, building, floor, room, and zone schemas",
			"own traversal connection schemas without traversal execution",
			"own streaming region schemas without streaming execution",
			"own environmental classification schemas, world tags, and world metadata",
			"own world diagnostics, snapshots, serialization, validation, and self-checks",
			"describe world structure for future systems without building or mutating the world",
			"reject malformed references to registered world schemas before state changes",
			"enforce per-category runtime limits for all world schema categories",
		},
		doesNotOwn = {
			"Workspace mutation",
			"terrain",
			"map generation",
			"streaming execution",
			"room loading",
			"teleporting",
			"player movement",
			"door opening",
			"interaction execution",
			"puzzle execution",
			"inventory execution",
			"Monster AI",
			"Narrative ownership",
			"Save ownership",
			"horror pacing",
			"UI",
			"Audio",
			"Lighting",
			"Camera",
			"animation",
			"pathfinding",
			"physics",
			"remotes",
			"client authority",
			"Chapter content",
			"story",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Physical Runtime Foundation",
			"Interaction Runtime Foundation",
			"Puzzle Runtime Foundation",
			"Inventory Runtime Foundation",
			"Narrative Runtime Foundation",
			"Save Journal Identity Runtime Foundation",
			"Gameplay Execution Bridge Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no Workspace, terrain, map generation, streaming, room loading, teleport, movement, pathfinding, physics, interaction, puzzle, inventory, UI, Audio, Lighting, camera, remote, client, or Chapter execution",
		},
		clientPresentation = {
			allowed = false,
			description = "World Runtime creates no UI, remotes, client truth, streaming execution, or physical world mutation.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "WorldCoordinator.inspect" },
		snapshotProviders = { "worldRuntime" },
		cleanupBehavior = {
			"shutdown clears districts, regions, buildings, floors, rooms, zones, connections, streaming regions, classifications, tags, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative world schemas only",
			"duplicate world schema ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, stream, load, traverse, teleport, move, present, or execute world behavior through this runtime",
		},
		failureModes = {
			"malformed district, region, building, floor, room, zone, connection, streaming, classification, and tag schemas reject",
			"duplicate ids reject",
			"unknown district, building, floor, room, connection endpoint, and streaming world references reject",
			"invalid connection endpoints reject",
			"invalid streaming policies reject",
			"per-category runtime limits reject instead of evicting world schemas",
			"unsafe metadata, context, and tags reject",
			"Workspace, Terrain, CFrame execution, teleport, movement, pathfinding, physics, map generation, room loading, streaming execution, interaction execution, puzzle execution, inventory execution, Monster AI, Narrative, Save, horror pacing, UI, Audio, Lighting, Camera, remote, client, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"districts, regions, buildings, floors, rooms, zones, connections, streaming regions, classifications, and tags are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, reference count, tag count, and string length are bounded",
		},
		documentation = {
			"WORLD_RUNTIME.md",
			"WORLD_DISTRICT_RUNTIME.md",
			"WORLD_REGION_RUNTIME.md",
			"WORLD_BUILDING_RUNTIME.md",
			"WORLD_FLOOR_RUNTIME.md",
			"WORLD_ROOM_RUNTIME.md",
			"WORLD_ZONE_RUNTIME.md",
			"WORLD_CONNECTION_RUNTIME.md",
			"WORLD_STREAMING_RUNTIME.md",
			"WORLD_CLASSIFICATION_RUNTIME.md",
			"WORLD_TAG_RUNTIME.md",
			"WORLD_VALIDATION.md",
			"WORLD_SERIALIZATION.md",
			"WORLD_DIAGNOSTICS.md",
			"WORLD_RUNTIME_LIMITS.md",
			"WORLD_SELF_CHECKS.md",
			"WORLD_AUDIT.md",
			"WORLD_PRODUCTION_REVIEW.md",
		},
		tags = {
			"world-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-workspace-mutation",
			"no-remotes",
		},
	},
	{
		systemName = "Objective Runtime Foundation",
		ownerLayer = "Objective",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative objective schemas",
			"own task, requirement, dependency, and objective state schemas",
			"own objective progress records as schema data",
			"own objective diagnostics, snapshots, serialization, validation, and self-checks",
			"provide objective structure for future systems without completing or executing objectives",
			"reference World, Puzzle, Interaction, Inventory, Narrative, Save, and Gameplay Execution schemas by id only",
			"reject duplicate task, requirement, dependency, and progress ids before state changes",
			"enforce per-category runtime limits for objective schemas, tasks, requirements, dependencies, and progress records",
		},
		doesNotOwn = {
			"objective completion execution",
			"quest execution",
			"gameplay execution",
			"puzzle execution",
			"interaction execution",
			"inventory execution",
			"UI",
			"Audio",
			"Lighting",
			"Camera",
			"Workspace mutation",
			"remotes",
			"client authority",
			"Monster AI",
			"Narrative ownership",
			"Save persistence",
			"horror pacing",
			"Chapter content",
			"story",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"World Runtime Foundation",
			"Puzzle Runtime Foundation",
			"Interaction Runtime Foundation",
			"Inventory Runtime Foundation",
			"Narrative Runtime Foundation",
			"Save Journal Identity Runtime Foundation",
			"Gameplay Execution Bridge Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema and progress records only",
			"no objective completion, quest, gameplay, puzzle, interaction, inventory, UI, Audio, Lighting, camera, Workspace, remote, client, save persistence, Narrative, Horror, or Chapter execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Objective Runtime creates no final UI, remotes, client truth, quest execution, or objective completion execution.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ObjectiveCoordinator.inspect" },
		snapshotProviders = { "objectiveRuntime" },
		cleanupBehavior = {
			"shutdown clears objective schemas, task schemas, requirement schemas, dependency schemas, objective state schemas, progress records, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative objective schemas only",
			"duplicate objective ids reject",
			"unknown objective progress rejects",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, complete, present, persist, or execute objectives through this runtime",
		},
		failureModes = {
			"malformed objective, task, requirement, dependency, state, and progress schemas reject",
			"duplicate objective, task, requirement, dependency, and progress ids reject",
			"unknown objective progress records reject",
			"unsupported objective and progress schema types reject",
			"per-category runtime limits reject instead of evicting objective schemas",
			"unsafe metadata, context, and tags reject",
			"client, remote, Workspace, Instance, objective completion execution, quest execution, gameplay execution, puzzle execution, interaction execution, inventory execution, UI, Audio, Lighting, Camera, Monster AI, Narrative, Save persistence, horror pacing, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"objectives are bounded",
			"tasks, requirements, dependencies, states, and progress records are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, tag count, and string length are bounded",
		},
		documentation = {
			"OBJECTIVE_RUNTIME.md",
			"OBJECTIVE_DEFINITION_RUNTIME.md",
			"OBJECTIVE_TASK_RUNTIME.md",
			"OBJECTIVE_REQUIREMENT_RUNTIME.md",
			"OBJECTIVE_DEPENDENCY_RUNTIME.md",
			"OBJECTIVE_PROGRESS_RUNTIME.md",
			"OBJECTIVE_STATE_RUNTIME.md",
			"OBJECTIVE_VALIDATION.md",
			"OBJECTIVE_SERIALIZATION.md",
			"OBJECTIVE_DIAGNOSTICS.md",
			"OBJECTIVE_RUNTIME_LIMITS.md",
			"OBJECTIVE_SELF_CHECKS.md",
			"OBJECTIVE_AUDIT.md",
			"OBJECTIVE_PRODUCTION_REVIEW.md",
		},
		tags = {
			"objective-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-objective-execution",
			"no-remotes",
		},
	},
	{
		systemName = "Session Runtime Foundation",
		ownerLayer = "Session",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative session schemas",
			"own player session records",
			"own party session schemas without party gameplay",
			"own readiness schemas",
			"own lifecycle and join/leave records",
			"own session diagnostics, snapshots, serialization, validation, and self-checks",
			"provide session structure without matchmaking, teleporting, lobby UI, remotes, or client authority",
			"reject unknown session references before recording session-linked records",
			"reject duplicate readiness, lifecycle, and join/leave ids before state changes",
			"enforce per-category runtime limits for all session schema categories",
		},
		doesNotOwn = {
			"matchmaking execution",
			"teleport execution",
			"lobby UI",
			"party gameplay",
			"save persistence",
			"player spawning",
			"movement",
			"Workspace mutation",
			"remotes",
			"client authority",
			"UI",
			"Audio",
			"Lighting",
			"Camera",
			"Monster AI",
			"Narrative ownership",
			"horror pacing",
			"Chapter content",
			"story",
			"dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"World Runtime Foundation",
			"Objective Runtime Foundation",
			"Inventory Runtime Foundation",
			"Save Journal Identity Runtime Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no matchmaking, teleport, lobby UI, party gameplay, save persistence, Workspace, remote, client, presentation, or Chapter execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Session Runtime creates no lobby UI, remotes, client truth, matchmaking execution, or teleport execution.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "SessionCoordinator.inspect" },
		snapshotProviders = { "sessionRuntime" },
		cleanupBehavior = {
			"shutdown clears session schemas, player session records, party session schemas, readiness schemas, lifecycle records, join/leave records, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative session schemas only",
			"duplicate session, player session, and party ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, matchmake, teleport, present, persist, or execute sessions through this runtime",
		},
		failureModes = {
			"malformed session, player session, party, readiness, lifecycle, and join/leave schemas reject",
			"unsupported session, player session, party, readiness, lifecycle, and join/leave schema types reject",
			"duplicate session ids, player session ids, party ids, readiness ids, lifecycle ids, and join/leave ids reject",
			"unknown session references reject",
			"per-category runtime limits reject instead of evicting session schemas",
			"unsafe metadata, context, and tags reject",
			"client, remote, Workspace, teleport execution, matchmaking execution, save persistence, lobby UI, party gameplay, Monster AI, Narrative, horror pacing, Chapter, story, dialogue, and cutscene fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		runtimeLimits = {
			"sessions are bounded",
			"player session records are bounded",
			"party, readiness, lifecycle, and join/leave records are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, tag count, and string length are bounded",
		},
		documentation = {
			"SESSION_RUNTIME.md",
			"SESSION_DEFINITION_RUNTIME.md",
			"SESSION_PLAYER_RUNTIME.md",
			"SESSION_PARTY_RUNTIME.md",
			"SESSION_READINESS_RUNTIME.md",
			"SESSION_LIFECYCLE_RUNTIME.md",
			"SESSION_VALIDATION.md",
			"SESSION_SERIALIZATION.md",
			"SESSION_DIAGNOSTICS.md",
			"SESSION_RUNTIME_LIMITS.md",
			"SESSION_SELF_CHECKS.md",
			"SESSION_AUDIT.md",
			"SESSION_PRODUCTION_REVIEW.md",
		},
		tags = {
			"session-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-matchmaking-execution",
			"no-remotes",
		},
	},
	{
		systemName = "Door Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"register reusable door definitions",
			"validate door state transitions",
			"track failed open attempts",
			"expose door diagnostics",
		},
		doesNotOwn = {
			"door animation",
			"physical door movement",
			"Chapter 1 locks",
			"final audio",
		},
		dependencies = { "Gameplay Intelligence Runtime", "Object Runtime", "Observation Engine" },
		observationsEmitted = {
			{ id = "Door.Opened", when = "server opens door", required = true },
			{ id = "Door.Closed", when = "server closes door", required = true },
			{ id = "Door.Locked", when = "server locks door", required = true },
			{ id = "Door.Unlocked", when = "server unlocks door", required = true },
			{ id = "Door.FailedOpen", when = "server rejects open attempt", required = true },
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may show server-approved door feedback.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "DoorService.inspect" },
		snapshotProviders = { "gameplayIntelligence.doors" },
		cleanupBehavior = { "clear door definitions, state, and transitions on shutdown" },
		multiplayerGuarantees = {
			"server-authoritative door state machine",
			"invalid transitions fail closed",
		},
		failureModes = { "unknown doors reject", "locked unavailable doors fail open attempts" },
		documentation = { "DOOR_RUNTIME.md" },
		tags = { "gameplay", "doors", "server" },
	},
	{
		systemName = "Inventory Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"own personal inventory truth",
			"prepare party inventory hooks",
			"validate item additions and removals",
			"expose inventory diagnostics",
		},
		doesNotOwn = {
			"client inventory UI",
			"item spawning",
			"save persistence",
			"Chapter 1 rewards",
		},
		dependencies = { "Gameplay Intelligence Runtime", "Observation Engine" },
		observationsEmitted = {
			{ id = "Inventory.ItemAdded", when = "server adds item", required = true },
			{ id = "Inventory.ItemRemoved", when = "server removes item", required = true },
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may render server-owned inventory state.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "InventoryService.inspect" },
		snapshotProviders = { "gameplayIntelligence.inventory" },
		cleanupBehavior = { "clear inventory containers on shutdown" },
		multiplayerGuarantees = {
			"clients cannot create items",
			"server validates every inventory mutation",
		},
		failureModes = { "invalid item definitions reject", "missing items cannot be removed" },
		documentation = { "INVENTORY_RUNTIME.md" },
		tags = { "gameplay", "inventory", "server" },
	},
	{
		systemName = "Key Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"register key data definitions",
			"validate key collection and use",
			"support single-use, reusable, master, party-shared, and reward keys",
		},
		doesNotOwn = { "key models", "key UI", "door animation", "Chapter 1 key placement" },
		dependencies = {
			"Gameplay Intelligence Runtime",
			"Inventory Runtime",
			"Observation Engine",
		},
		observationsEmitted = {
			{ id = "Key.Collected", when = "server accepts key collection", required = true },
			{ id = "Key.Used", when = "server accepts key use", required = true },
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may present server-approved key feedback.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "KeyService.inspect" },
		snapshotProviders = { "gameplayIntelligence.keys" },
		cleanupBehavior = { "clear key registry on shutdown" },
		multiplayerGuarantees = { "server validates target unlocks", "clients cannot claim keys" },
		failureModes = {
			"unknown keys reject",
			"wrong target rejects",
			"single-use keys are consumed",
		},
		documentation = { "KEY_RUNTIME.md" },
		tags = { "gameplay", "keys", "server" },
	},
	{
		systemName = "Objective Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"register reusable objectives",
			"validate start, progress, completion, and failure",
			"support primary, secondary, hidden, personal, party, branching, and timed objective hooks",
		},
		doesNotOwn = {
			"Chapter 1 objective content",
			"story pacing",
			"final UI",
			"save persistence",
		},
		dependencies = {
			"Gameplay Intelligence Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
		},
		observationsEmitted = {
			{ id = "Objective.Started", when = "server starts objective", required = true },
			{ id = "Objective.Progressed", when = "server progresses objective", required = true },
			{ id = "Objective.Completed", when = "server completes objective", required = true },
			{ id = "Objective.Failed", when = "server fails objective", required = true },
		},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Objective progress pressure must be Director-approved before future execution.",
				requiredFor = { "future objective presentation pressure" },
			},
		},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may present server objective state.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ObjectiveService.inspect" },
		snapshotProviders = { "gameplayIntelligence.objectives" },
		cleanupBehavior = { "clear objective registry and state on shutdown" },
		multiplayerGuarantees = {
			"server-owned objective progress",
			"party objective hooks remain server-owned",
		},
		failureModes = {
			"unknown objectives reject",
			"completed or failed objectives cannot progress",
		},
		documentation = { "OBJECTIVE_RUNTIME.md" },
		tags = { "gameplay", "objectives", "server" },
	},
	{
		systemName = "Puzzle Runtime",
		ownerLayer = "Gameplay",
		status = "Production",
		responsibilities = {
			"register graph-based puzzles",
			"validate puzzle node dependencies",
			"track puzzle progress and wrong inputs",
			"provide progressive hint hooks",
			"protect puzzle fairness",
		},
		doesNotOwn = {
			"Chapter 1 puzzle answers",
			"copied puzzles",
			"final UI",
			"horror pacing",
			"physical Workspace mutation",
		},
		dependencies = {
			"Gameplay Intelligence Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"World Intelligence",
		},
		observationsEmitted = {
			{ id = "Puzzle.Started", when = "server starts puzzle", required = true },
			{ id = "Puzzle.NodeCompleted", when = "server completes node", required = true },
			{ id = "Puzzle.WrongInput", when = "server rejects puzzle input", required = true },
			{ id = "Puzzle.HintRequested", when = "hint is requested", required = true },
			{
				id = "Puzzle.HintShown",
				when = "hint is approved for presentation",
				required = true,
			},
			{ id = "Puzzle.Completed", when = "server completes puzzle", required = true },
			{ id = "Puzzle.Failed", when = "server fails puzzle", required = true },
		},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Puzzle pressure and hints must preserve fairness before future execution.",
				requiredFor = { "future puzzle pressure", "future hint presentation pressure" },
			},
		},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Future clients may present server-approved puzzle state and hints.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "PuzzleService.inspect" },
		snapshotProviders = { "gameplayIntelligence.puzzles" },
		cleanupBehavior = { "clear puzzle registry, state, and hint cooldowns on shutdown" },
		multiplayerGuarantees = {
			"graph progress is server-owned",
			"co-op puzzle hooks are data-driven",
		},
		failureModes = {
			"impossible graphs reject",
			"missing dependencies reject",
			"instant spoiler hints reject by cooldown",
		},
		documentation = { "PUZZLE_RUNTIME.md", "PUZZLE_HINTS.md", "GAMEPLAY_GRAPH.md" },
		tags = { "gameplay", "puzzles", "server" },
	},
}

return contracts
