--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Psychological Horror Director",
		ownerLayer = "Director",
		status = "Production",
		responsibilities = {
			"fear pacing",
			"tension",
			"silence",
			"scare opportunity selection",
			"cooldowns",
			"pressure rhythm",
		},
		doesNotOwn = {
			"monster movement",
			"chapter climax",
			"story canon",
			"final audio playback",
			"final lighting playback",
			"client presentation",
		},
		dependencies = { "Core Runtime", "Observation Engine" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			{ action = "publish scare opportunity", requiresApproval = false, approval = "Horror" },
		},
		clientPresentation = {
			allowed = false,
			description = "Director publishes decisions; presentation systems render later.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "HorrorDirector.inspect" },
		snapshotProviders = { "horrorDirector" },
		cleanupBehavior = {
			"cancel evaluation task",
			"disconnect EventBus",
			"clear profile memory",
		},
		multiplayerGuarantees = {
			"server-owned decisions",
			"round-robin evaluation",
			"cooldown fairness",
		},
		failureModes = {
			"silence instead of unsafe scare",
			"validation refusal on invalid registry",
		},
		documentation = { "HORROR_DIRECTOR.md", "HORROR_DIRECTOR_REVIEW.md" },
		tags = { "director", "horror", "pacing" },
	},
	{
		systemName = "Director Ecosystem Foundation",
		ownerLayer = "Director",
		status = "Production",
		responsibilities = {
			"director discovery",
			"director lifecycle",
			"request approval routing",
			"conflict resolution",
			"capability registry",
			"decision traces",
			"director diagnostics",
		},
		doesNotOwn = {
			"gameplay execution",
			"Monster AI movement",
			"final audio playback",
			"final lighting playback",
			"chapter content",
		},
		dependencies = { "Core Runtime", "Observation Engine" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			{
				action = "resolve Director approval requests",
				requiresApproval = false,
				approval = nil,
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Director Ecosystem is server-only interpretation and approval architecture.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "DirectorCoordinator.inspect" },
		snapshotProviders = { "directorCoordinator" },
		cleanupBehavior = {
			"shutdown directors in reverse order",
			"disconnect Observation Engine routing",
			"clear pending requests",
			"cancel expiration sweeps",
		},
		multiplayerGuarantees = {
			"server-only approvals",
			"observations are trusted server facts",
			"failed directors are isolated",
		},
		failureModes = {
			"defer gated requests",
			"reject missing target directors",
			"isolate failing director calls",
		},
		documentation = {
			"DIRECTOR_ECOSYSTEM.md",
			"DIRECTOR_COORDINATOR.md",
			"DIRECTOR_CONTRACTS.md",
			"DIRECTOR_REQUESTS.md",
			"DIRECTOR_APPROVALS.md",
			"DIRECTOR_CAPABILITIES.md",
			"DIRECTOR_FAILURES.md",
		},
		tags = { "director", "coordinator", "architecture" },
	},
	{
		systemName = "Environment Director",
		ownerLayer = "Director",
		status = "Production",
		responsibilities = {
			"environmental reaction approvals",
			"world pressure state",
			"zone pressure context",
			"environment memory",
			"reaction cooldowns",
			"execution bridge contracts",
			"environment diagnostics",
		},
		doesNotOwn = {
			"monster movement",
			"final audio playback",
			"final lighting playback",
			"puzzle truth",
			"story canon",
			"final art",
			"client-owned weather truth",
			"Chapter 1 content",
			"physical object movement without execution bridge approval",
		},
		dependencies = { "Core Runtime", "Observation Engine", "Director Ecosystem Foundation" },
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Narrative",
				reason = "Major building attention should respect future narrative beats.",
				requiredFor = {
					"major BuildingAttention reactions",
					"chapter-critical environment pressure",
				},
			},
		},
		executionPermissions = {
			{
				action = "publish server-side environment execution bridge requests",
				requiresApproval = true,
				approval = "Environment",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Clients may later present approved execution results only; they never own environment truth.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "EnvironmentDirector.inspect" },
		snapshotProviders = { "environmentDirector" },
		cleanupBehavior = {
			"cancel cooldown cleanup task",
			"disconnect EventBus subscriptions",
			"clear environment memory",
			"clear zone context",
			"clear execution bridge diagnostics",
		},
		multiplayerGuarantees = {
			"server-only approvals",
			"group size considered during selection",
			"safe room and puzzle fairness suppression",
			"bounded memory and cooldowns",
		},
		failureModes = {
			"malformed requests are rejected",
			"unfair reactions become silence or deferral",
			"execution bridge failures are recorded without world mutation",
		},
		documentation = {
			"ENVIRONMENT_DIRECTOR.md",
			"ENVIRONMENT_REACTIONS.md",
			"ENVIRONMENT_ZONES.md",
			"ENVIRONMENT_EXECUTION.md",
		},
		tags = { "director", "environment", "horror", "server" },
	},
	{
		systemName = "Lighting Director",
		ownerLayer = "Director",
		status = "Production",
		responsibilities = {
			"lighting pressure approvals",
			"World Intelligence lighting policy enforcement",
			"safe-room lighting protection",
			"puzzle-room lighting protection",
			"lighting diagnostics",
		},
		doesNotOwn = {
			"Roblox Lighting mutation",
			"Workspace mutation",
			"client presentation",
			"final lighting art",
			"monster movement",
			"Chapter 1 content",
		},
		dependencies = {
			"Core Runtime",
			"Director Ecosystem Foundation",
			"Observation Engine",
			"Environment Director",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Lighting pressure should respect world reaction pressure and environmental fairness.",
				requiredFor = {
					"future physical lighting execution",
					"major visibility pressure",
				},
			},
		},
		executionPermissions = {
			{
				action = "approve future lighting pressure only",
				requiresApproval = true,
				approval = "Lighting",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Lighting Director approves server-side decisions only; future clients may present approved execution results.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "LightingDirector.inspect" },
		snapshotProviders = { "lightingDirector" },
		cleanupBehavior = {
			"cancel cooldown cleanup task",
			"clear lighting pressure state",
			"clear recent decisions and suppressions",
		},
		multiplayerGuarantees = {
			"server-only approvals",
			"World Intelligence policy enforced",
			"safe-room and puzzle-room suppression",
			"bounded memory and cooldowns",
		},
		failureModes = {
			"malformed requests are rejected",
			"unknown zones deny major lighting pressure",
			"unsafe pressure is deferred with reason",
		},
		documentation = { "LIGHTING_DIRECTOR.md", "SENSORY_DIRECTORS.md" },
		tags = { "director", "lighting", "sensory", "server" },
	},
	{
		systemName = "Audio Director",
		ownerLayer = "Director",
		status = "Production",
		responsibilities = {
			"audio pressure approvals",
			"World Intelligence audio policy enforcement",
			"safe-room audio protection",
			"puzzle-room audio protection",
			"audio diagnostics",
		},
		doesNotOwn = {
			"sound playback",
			"final audio assets",
			"client presentation",
			"music score",
			"monster movement",
			"Chapter 1 content",
		},
		dependencies = {
			"Core Runtime",
			"Director Ecosystem Foundation",
			"Observation Engine",
			"Environment Director",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Environment",
				reason = "Audio pressure should respect environmental pressure and world fairness.",
				requiredFor = {
					"future physical audio execution",
					"major audio pressure",
				},
			},
		},
		executionPermissions = {
			{
				action = "approve future audio pressure only",
				requiresApproval = true,
				approval = "Audio",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Audio Director approves server-side decisions only; future clients may present approved execution results.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "AudioDirector.inspect" },
		snapshotProviders = { "audioDirector" },
		cleanupBehavior = {
			"cancel cooldown cleanup task",
			"clear audio pressure state",
			"clear recent decisions and suppressions",
		},
		multiplayerGuarantees = {
			"server-only approvals",
			"World Intelligence policy enforced",
			"safe-room and puzzle-room suppression",
			"bounded memory and cooldowns",
		},
		failureModes = {
			"malformed requests are rejected",
			"unknown zones deny major audio pressure",
			"unsafe pressure is deferred with reason",
		},
		documentation = { "AUDIO_DIRECTOR.md", "SENSORY_DIRECTORS.md" },
		tags = { "director", "audio", "sensory", "server" },
	},
	{
		systemName = "Monster Intelligence Foundation",
		ownerLayer = "AI",
		status = "Production",
		responsibilities = {
			"own server-authoritative monster knowledge and memory",
			"score interest, curiosity, threat, patience, territory, and search priority",
			"produce explainable monster intentions",
			"coordinate shared investigation claims and shared believed facts",
			"expose diagnostics, snapshots, and self-check evidence",
		},
		doesNotOwn = {
			"Monster AI movement",
			"pathfinding",
			"navigation",
			"NPC spawning",
			"animations",
			"attacks or damage",
			"Workspace mutation",
			"sound playback",
			"Lighting mutation",
			"client remotes",
			"Chapter 1 content",
			"horror pacing ownership",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"Gameplay Execution Bridge",
			"London Bible canon",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Monster",
				reason = "Future monster execution may only consume Director-approved intentions.",
				requiredFor = {
					"monster reveal",
					"stalk pressure",
					"investigation escalation",
					"chase permission",
				},
			},
			{
				director = "Horror",
				reason = "Monster pressure must not own global horror pacing.",
				requiredFor = {
					"major scare pressure",
					"high-tension monster attention",
				},
			},
		},
		executionPermissions = {
			{
				action = "Request intent-only future execution records",
				requiresApproval = true,
				approval = "Monster",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Monster Intelligence is server-only and creates no client remotes.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "MonsterIntelligenceCoordinator.inspect" },
		snapshotProviders = { "monsterIntelligence" },
		cleanupBehavior = {
			"cancel cleanup task",
			"clear monster registry, memory, knowledge, claims, and decision history on shutdown",
		},
		multiplayerGuarantees = {
			"server owns monster intent truth",
			"duplicate monster ids reject",
			"duplicate investigation claims reject",
			"future Monster AI cannot decide intent",
		},
		failureModes = {
			"unknown monsters reject intent requests",
			"unsafe execution fields reject",
			"invalid confidence and interest values reject",
			"invalid state transitions reject",
			"memory and diagnostics remain bounded",
		},
		documentation = {
			"MONSTER_INTELLIGENCE.md",
			"MONSTER_MEMORY.md",
			"MONSTER_BEHAVIOR.md",
			"MONSTER_GROUPS.md",
			"MONSTER_KNOWLEDGE.md",
			"MONSTER_INTEREST.md",
			"MONSTER_DIAGNOSTICS.md",
		},
		tags = { "ai", "monster-intelligence", "server", "intent-only" },
	},
	{
		systemName = "Horror Orchestration Framework",
		ownerLayer = "Horror",
		status = "Production",
		responsibilities = {
			"coordinate cross-system horror pressure",
			"own bounded pressure budget and release/silence decisions",
			"protect emotional beats, safe rooms, and puzzle readability",
			"bundle approval-only requests for sensory, environment, monster, gameplay, and narrative systems",
			"expose diagnostics, snapshots, and self-checks",
		},
		doesNotOwn = {
			"gameplay truth",
			"Monster AI",
			"monster movement",
			"pathfinding",
			"damage",
			"animations",
			"Lighting mutation",
			"audio playback",
			"Workspace mutation",
			"final UI",
			"final scares",
			"chapter content",
			"client authority",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem Foundation",
			"Psychological Horror Director",
			"Environment Director",
			"Lighting Director",
			"Audio Director",
			"Monster Intelligence Foundation",
			"Gameplay Intelligence Runtime",
			"Gameplay Execution Bridge",
			"London Bible canon",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			{
				director = "Horror",
				reason = "Major pressure changes must preserve psychological pacing.",
				requiredFor = {
					"scare eligibility",
					"pressure escalation",
					"release timing",
				},
			},
			{
				director = "Monster",
				reason = "Monster pressure and chase preparation require future Monster Director approval.",
				requiredFor = {
					"monster pressure request",
					"chase preparation",
				},
			},
		},
		executionPermissions = {
			{
				action = "Create approval-only coordination bundles",
				requiresApproval = true,
				approval = "Horror",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Horror Orchestration creates no client remotes and owns no presentation.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "HorrorOrchestrator.inspect" },
		snapshotProviders = { "horrorOrchestration" },
		cleanupBehavior = {
			"cancel cleanup task",
			"clear pressure queue, pressure state, request ids, decisions, suppressions, and bundles on shutdown",
		},
		multiplayerGuarantees = {
			"pressure budget accounts for multiplayer load",
			"duplicate request ids reject",
			"client authority is not accepted",
			"safe rooms and puzzle rooms suppress unfair pressure",
		},
		failureModes = {
			"malformed pressure requests reject",
			"expired requests reject or expire from queue",
			"duplicate request ids reject",
			"unsafe execution fields reject",
			"no action is valid when timing is wrong",
		},
		documentation = {
			"HORROR_ORCHESTRATION.md",
			"HORROR_PRESSURE_BUDGET.md",
			"HORROR_COORDINATION.md",
			"HORROR_SILENCE_AND_RELEASE.md",
			"HORROR_ORCHESTRATION_DIAGNOSTICS.md",
			"HORROR_ORCHESTRATION_AUDIT.md",
			"HORROR_ORCHESTRATION_PRODUCTION_REVIEW.md",
			"HORROR_COORDINATION_REVIEW.md",
			"HORROR_PRESSURE_MODEL_REVIEW.md",
		},
		tags = { "horror", "orchestration", "server", "approval-only" },
	},
	{
		systemName = "Monster AI Execution Foundation",
		ownerLayer = "AI",
		status = "Foundation",
		responsibilities = {
			"consume approved monster intent/context only",
			"turn approved intent into dry-run execution records",
			"prepare reusable foundations for future chase, stalk, watch, retreat, perception, and navigation execution",
			"emit server observations for future monster state records",
			"expose diagnostics, snapshots, bounded history, validation failures, and deterministic self-checks",
		},
		doesNotOwn = {
			"intent decisions",
			"horror pacing",
			"story reveals",
			"Monster Director approvals",
			"Horror Director approvals",
			"Living Cognition beliefs",
			"Monster Intelligence reasoning",
			"navigation/pathfinding execution",
			"movement",
			"attacks",
			"damage",
			"animations",
			"monster models",
			"NPC spawning",
			"Workspace mutation",
			"client remotes",
			"Lighting changes",
			"Audio playback",
			"UI/presentation",
			"Chapter content",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem",
			"Living Cognition Runtime",
			"Monster Intelligence Foundation",
			"Horror Orchestration Framework",
			"Gameplay Execution Bridge",
		},
		observationsEmitted = {
			{
				id = "Monster.Ignored",
				when = "approved Monster AI intent is recorded as a dry-run execution state",
				required = true,
			},
		},
		directorApprovalsRequired = {
			{
				director = "Monster Director / DirectorCoordinator",
				reason = "Monster AI cannot invent its own intent or pacing",
				requiredFor = { "Chase", "Stalk", "Watch", "Retreat", "Navigate", "Perceive" },
			},
		},
		executionPermissions = {
			{
				action = "dry-run execution record",
				requiresApproval = true,
				approval = "Director-approved intent/context only",
			},
		},
		clientPresentation = {
			allowed = false,
			description = "Monster AI Execution Foundation is server-only and creates no client remotes or presentation.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "MonsterAIService.inspect" },
		snapshotProviders = { "monsterAIExecution" },
		cleanupBehavior = {
			"clear monster registry, intent records, replay-protection ids, execution records, validation failures, and snapshot history on shutdown",
		},
		multiplayerGuarantees = {
			"server-authoritative approved intent intake only",
			"no client authority accepted",
			"duplicate monster and duplicate intent ids reject",
			"unsafe execution payloads reject before planning",
		},
		failureModes = {
			"missing Director approval rejects",
			"unknown monsters reject",
			"unsupported intents reject",
			"expired intents reject",
			"malformed monster definitions reject",
			"cyclic, oversized, Instance-like, unsafe runtime, and nested execution payloads reject",
			"all accepted execution remains dry-run only",
		},
		documentation = {
			"MONSTER_AI_EXECUTION.md",
			"MONSTER_AI_BOUNDARIES.md",
			"MONSTER_AI_DIAGNOSTICS.md",
			"MONSTER_AI_SELF_CHECKS.md",
			"MONSTER_AI_AUDIT.md",
			"MONSTER_AI_RUNTIME_LIMITS.md",
			"MONSTER_AI_SERIALIZATION.md",
			"MONSTER_AI_PRODUCTION_REVIEW.md",
		},
		tags = { "ai", "monster-ai", "server", "dry-run", "execution-foundation" },
	},
	{
		systemName = "Narrative Runtime Foundation",
		ownerLayer = "Narrative",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative narrative beat schema state",
			"own story gate eligibility schemas",
			"own reveal eligibility foundation state",
			"own emotional beat protection state",
			"own narrative schemas only; final writing and presentation remain outside this runtime",
			"connect narrative schemas to Journal, Memory Fragment, and Identity schemas",
			"inform future Directors without executing effects",
			"expose diagnostics, snapshots, validation, serialization, and self-checks",
		},
		doesNotOwn = {
			"final story prose",
			"final dialogue",
			"Chapter content",
			"cutscenes",
			"final UI",
			"presentation execution",
			"client-owned narrative truth",
			"Workspace mutation",
			"Audio execution",
			"Lighting execution",
			"Monster AI ownership",
			"horror pacing ownership",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Director Ecosystem",
			"Horror Orchestration Framework",
			"Living Cognition Runtime",
			"Save Journal Identity Runtime",
			"Gameplay Intelligence Runtime",
			"Governance",
		},
		observationsEmitted = {
			{
				id = "Narrative.BeatRegistered",
				when = "server registers a narrative beat schema",
				required = true,
			},
			{
				id = "Narrative.StoryGateRegistered",
				when = "server registers story gate schema",
				required = true,
			},
			{
				id = "Narrative.RevealEligible",
				when = "server grants reveal eligibility",
				required = true,
			},
			{
				id = "Narrative.EmotionalProtectionRegistered",
				when = "server registers emotional beat protection",
				required = true,
			},
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Narrative Runtime owns server schema and eligibility truth only; clients may present approved state later.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "NarrativeCoordinator.inspect" },
		snapshotProviders = { "narrativeRuntime" },
		cleanupBehavior = {
			"clear narrative beats, story gates, reveal eligibility, emotional protections, validation failures, and snapshot history on shutdown",
		},
		multiplayerGuarantees = {
			"server-authoritative narrative truth only",
			"no client-owned narrative truth accepted",
			"duplicate beat, story gate, reveal, and emotional protection ids reject",
			"unsafe payloads reject before state changes",
			"clients cannot create, mutate, approve, or execute narrative state",
		},
		failureModes = {
			"invalid beats reject",
			"invalid story gates reject",
			"duplicate reveal eligibility and emotional protection records reject",
			"unsafe reveal payloads reject",
			"invalid emotional beats reject",
			"final dialogue, story prose, Chapter content, cutscenes, UI, Workspace, Audio, Lighting, Monster AI, and horror pacing fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
		},
		documentation = {
			"NARRATIVE_AUDIT.md",
			"NARRATIVE_RUNTIME.md",
			"NARRATIVE_RUNTIME_LIMITS.md",
			"NARRATIVE_BEATS.md",
			"STORY_GATES.md",
			"REVEAL_ELIGIBILITY.md",
			"EMOTIONAL_BEAT_PROTECTION.md",
			"NARRATIVE_SERIALIZATION.md",
			"NARRATIVE_VALIDATION.md",
			"NARRATIVE_DIAGNOSTICS.md",
			"NARRATIVE_SELF_CHECKS.md",
			"NARRATIVE_PRODUCTION_REVIEW.md",
		},
		tags = { "narrative", "server", "foundation", "schema-only" },
	},
}

return contracts
