--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Observation Engine",
		ownerLayer = "Observation",
		status = "Production",
		responsibilities = {
			"trusted fact intake",
			"exact Observation.Submitted processing boundary",
			"validation and enrichment",
			"aggregation and memory",
			"timeline recording",
			"pattern recognition",
			"director forwarding",
			"Chapter0Home observation fact processing through existing Observation.Submitted intake",
			"read-only cooperation with Chapter0Home certification evidence review",
		},
		doesNotOwn = {
			"gameplay execution",
			"Chapter 0 Home source state",
			"Chapter 0 Home certification decision",
			"Phase 118 certification evidence schema",
			"horror interpretation",
			"monster movement",
			"client presentation",
			"analytics export",
		},
		dependencies = { "Core Runtime" },
		observationsEmitted = {
			{ id = "Observation.Accepted", when = "trusted server fact accepted", required = true },
		},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Observation Engine is server-only truth processing.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ObservationService.inspect", "ObservationProfiler.inspect" },
		snapshotProviders = { "observationEngine" },
		cleanupBehavior = {
			"clear memory",
			"clear timelines",
			"clear pattern state",
			"disconnect EventBus",
		},
		multiplayerGuarantees = {
			"active Player validation",
			"bounded metadata",
			"server-only intake",
			"read-only processing of Chapter0Home observation facts",
			"Observation Runtime never mutates Chapter0Home source state",
		},
		failureModes = {
			"reject malformed observations",
			"log validation failures",
			"reject unregistered Chapter0Home observation ids",
		},
		documentation = { "OBSERVATION_ENGINE.md", "ENGINE_CONSTITUTION.md" },
		tags = { "observation", "truth", "server" },
	},
	{
		systemName = "Living Cognition Runtime",
		ownerLayer = "AI",
		status = "Production",
		responsibilities = {
			"coordinate cognition lifecycle",
			"normalize trusted observations",
			"create evidence without treating it as truth",
			"generate and rank hypotheses",
			"promote hypotheses into thoughts",
			"update slow-changing beliefs",
			"preserve confidence, uncertainty, provenance, traces, diagnostics, snapshots, and serialization hooks",
		},
		doesNotOwn = {
			"gameplay truth",
			"Monster AI",
			"movement",
			"navigation",
			"pathfinding",
			"attacks",
			"animations",
			"NPC spawning",
			"Workspace mutation",
			"client remotes",
			"Roblox Lighting modification",
			"Audio playback",
			"Chapter content",
			"presentation",
			"client-owned truth",
		},
		dependencies = {
			"Core Runtime",
			"Observation Engine",
			"Monster Intelligence Foundation",
			"Horror Orchestration Framework",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Living Cognition is server-only and creates no client remotes or presentation.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "LivingCognitionCoordinator.inspect" },
		snapshotProviders = { "livingCognition" },
		cleanupBehavior = {
			"clear registry, observations, evidence, hypotheses, thoughts, beliefs, traces, and validation failures on shutdown",
		},
		multiplayerGuarantees = {
			"server-authoritative cognition only",
			"no client authority accepted",
			"duplicate cognitive entity ids reject",
			"payloads containing execution leakage reject",
		},
		failureModes = {
			"malformed observations reject",
			"unknown cognitive entities reject",
			"invalid confidence rejects",
			"invalid timestamps reject",
			"Workspace and execution leakage reject",
		},
		documentation = {
			"LIVING_COGNITION_RUNTIME.md",
			"COGNITIVE_PIPELINE.md",
			"EVIDENCE_RUNTIME.md",
			"HYPOTHESIS_RUNTIME.md",
			"THOUGHT_RUNTIME.md",
			"BELIEF_RUNTIME.md",
			"COGNITION_DIAGNOSTICS.md",
			"COGNITION_VALIDATION.md",
			"COGNITION_CERTIFICATION.md",
			"COGNITION_PRODUCTION_REVIEW.md",
			"LIVING_COGNITION_AUDIT.md",
			"LIVING_COGNITION_PRODUCTION_REVIEW.md",
			"COGNITION_SELF_CHECKS.md",
			"COGNITION_RUNTIME_LIMITS.md",
			"COGNITION_SERIALIZATION.md",
		},
		tags = { "ai", "living-cognition", "server", "cognition-only" },
	},
	{
		systemName = "World Intelligence",
		ownerLayer = "Documentation",
		status = "Production",
		responsibilities = {
			"world profile contracts",
			"zone context resolution",
			"safe unknown-zone defaults",
			"affordance policy data",
		},
		doesNotOwn = {
			"Workspace mutation",
			"Chapter 1 map content",
			"Monster AI",
			"final lighting effects",
			"final audio playback",
		},
		dependencies = { "Core Runtime" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "World Intelligence is server-side contract data.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "WorldDiagnostics.capture" },
		snapshotProviders = { "future owning service may include WorldDiagnostics" },
		cleanupBehavior = { "clear registered synthetic profiles when explicitly requested" },
		multiplayerGuarantees = {
			"unknown zones fail conservative",
			"affordances are permissions, not actions",
		},
		failureModes = {
			"invalid profiles fail validation",
			"unknown zones deny major hostile pressure",
		},
		documentation = { "WORLD_INTELLIGENCE.md", "WORLD_INTELLIGENCE_REVIEW.md" },
		tags = { "world", "policy", "server" },
	},
}

return contracts
