--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Presentation Runtime Foundation",
		ownerLayer = "Presentation",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative presentation request schemas",
			"own presentation schemas only; final presentation execution remains outside this runtime",
			"own presentation approval verification",
			"own presentation channel schemas",
			"own presentation routing records",
			"own presentation queue records",
			"own presentation diagnostics, snapshots, serialization, validation, and self-checks",
			"provide a future-safe schema gateway before client-side presentation adapters exist",
		},
		doesNotOwn = {
			"final UI",
			"final audio",
			"final lighting",
			"camera effects",
			"cutscenes",
			"animations",
			"particles",
			"VFX execution",
			"Workspace mutation",
			"client authority",
			"remotes",
			"gameplay execution",
			"Monster AI",
			"Narrative",
			"Save",
			"horror pacing",
			"Chapter content",
			"dialogue",
			"story",
		},
		dependencies = {
			"Core Runtime",
			"Director Ecosystem",
			"Gameplay Execution Bridge Foundation",
			"Physical Runtime Foundation",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {
			"future visible or audible presentation must arrive as approved schema evidence before this runtime records routing intent",
		},
		executionPermissions = {
			"schema routing records only",
			"no UI, Audio, Lighting, camera, cutscene, animation, particle, VFX, Workspace, remote, or client execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Presentation Runtime records server-owned presentation intent only and creates no remotes.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "PresentationCoordinator.inspect" },
		snapshotProviders = { "presentationRuntime" },
		cleanupBehavior = {
			"shutdown clears presentation requests, approvals, channels, queue records, routing records, validation failures, and snapshot history",
		},
		multiplayerGuarantees = {
			"server-authoritative presentation intent schemas only",
			"duplicate presentation ids reject",
			"duplicate approval ids reject",
			"missing approvals, malformed approvals, missing channels, duplicate channels, and invalid channels reject",
			"unsafe payloads reject before queue or routing records",
			"clients cannot create, mutate, approve, route, or execute presentation through this runtime",
		},
		failureModes = {
			"malformed presentation requests reject",
			"unsupported presentation types reject",
			"expired presentation requests reject",
			"invalid channels reject",
			"duplicate channels reject",
			"Workspace, Instance, final UI, audio execution, lighting execution, camera execution, cutscenes, animation, particles, VFX, gameplay execution, Monster AI, Narrative, Save, horror pacing, Chapter, story, dialogue, client, and remote fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"queue full requests reject without execution",
		},
		runtimeLimits = {
			"presentation requests are bounded",
			"queue records are bounded",
			"routing records are bounded",
			"validation failures are bounded",
			"snapshots are bounded",
			"payload depth, node count, and string length are bounded",
		},
		documentation = {
			"PRESENTATION_RUNTIME.md",
			"PRESENTATION_REQUEST_RUNTIME.md",
			"PRESENTATION_APPROVAL_RUNTIME.md",
			"PRESENTATION_CHANNEL_RUNTIME.md",
			"PRESENTATION_ROUTING_RUNTIME.md",
			"PRESENTATION_VALIDATION.md",
			"PRESENTATION_SERIALIZATION.md",
			"PRESENTATION_DIAGNOSTICS.md",
			"PRESENTATION_RUNTIME_LIMITS.md",
			"PRESENTATION_SELF_CHECKS.md",
			"PRESENTATION_AUDIT.md",
			"PRESENTATION_PRODUCTION_REVIEW.md",
		},
		tags = {
			"presentation-runtime",
			"server",
			"foundation",
			"schema-only",
			"no-client-authority",
		},
	},
	{
		systemName = "Client Player Presentation Runtime",
		ownerLayer = "ClientPresentation",
		status = "Production",
		responsibilities = {
			"input collection",
			"first-person camera presentation",
			"prompt presentation",
			"audio feedback hooks",
			"accessibility hooks",
		},
		doesNotOwn = {
			"gameplay truth",
			"interaction completion",
			"Observation Engine facts",
			"horror pacing",
			"final UI art",
		},
		dependencies = { "Core Runtime", "RemoteManager", "Player Runtime", "Interaction Runtime" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = true,
			description = "Client owns presentation only and sends requests to server remotes.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "client debug prints and future presentation diagnostics" },
		snapshotProviders = { "server-visible presentation contract only" },
		cleanupBehavior = {
			"disconnect input and camera connections on shutdown",
			"clear temporary prompt state",
		},
		multiplayerGuarantees = {
			"client cannot create trusted observations",
			"client cannot complete interactions",
			"server validates all remote requests",
		},
		failureModes = {
			"disable client controller when remotes are unavailable",
			"hide prompt when focus validation fails",
		},
		documentation = { "PLAYER_EXPERIENCE.md", "PLAYER_RUNTIME.md", "INTERACTION_RUNTIME.md" },
		tags = { "client", "presentation", "player" },
	},
}

return contracts
