--!strict
-- Governance contract group extracted from EngineContractRegistry.

local Types = require(script.Parent.Parent.EngineContractTypes)

type EngineContract = Types.EngineContract

local contracts: { EngineContract } = {
	{
		systemName = "Event Graph Runtime Foundation",
		ownerLayer = "EventGraph",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative event node, channel, edge, source, sink, subscription, propagation, priority, filter, payload contract, ordering, and audit schemas",
			"enforce one global Event Graph schema namespace across every category",
			"validate schema type, domain, kind, references, relationship safety, limits, unsafe payloads, serialization safety, and forbidden fields before state mutation",
			"certify duplicate rejection before mutation through one global Rule Engine namespace and sanitized diagnostics only",
			"reject EventBus references, dispatch handles, payload handles, subscription handles, listener references, live listener markers, live ordering markers, enforcement, remediation, and execution adapter fields anywhere in schema payloads",
			"enforce node integrity: event nodes are records, not live events",
			"enforce channel integrity: channels are schema channels, not EventBus channels",
			"enforce edge integrity: edges are relationships, not propagation",
			"enforce source integrity: sources are origin schemas, not publishers",
			"enforce sink integrity: sinks are recipient schemas, not listeners",
			"enforce subscription integrity: subscriptions are relationship schemas, not live subscriptions",
			"enforce propagation integrity: propagation records are policies, not propagation execution",
			"enforce priority integrity: priorities are policy values, not dispatch order",
			"enforce filter integrity: filters are schema constraints, not live filtering",
			"enforce payload contract integrity: payload contracts describe shape, not payload delivery",
			"enforce ordering integrity: ordering records are metadata, not event sequencing execution",
			"enforce audit integrity: audits are review summaries, not enforcement",
			"own Event Graph diagnostics, snapshots, serialization, validation, deterministic self-checks, and shutdown cleanup",
		},
		doesNotOwn = {
			"live event dispatch",
			"EventBus execution",
			"signal firing",
			"RemoteEvent creation",
			"RemoteFunction creation",
			"remote communication",
			"event subscription execution",
			"listener execution",
			"callback execution",
			"payload delivery",
			"event routing execution",
			"event propagation execution",
			"event queue processing",
			"event filter execution",
			"payload inspection execution",
			"event priority execution",
			"live ordering execution",
			"gameplay event execution",
			"puzzle event execution",
			"interaction event execution",
			"inventory event execution",
			"objective event execution",
			"narrative event execution",
			"Monster AI event execution",
			"Presentation event execution",
			"Save event execution",
			"scheduler execution",
			"lifecycle execution",
			"runtime orchestration",
			"Workspace mutation",
			"remotes",
			"client authority",
			"DataStore reads/writes",
			"HttpService",
			"MessagingService",
			"analytics collection",
			"telemetry sending",
			"Chapter content",
			"final story",
			"final dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no EventBus execution, event dispatch, signal firing, RemoteEvent or RemoteFunction creation, remote communication, subscription execution, listener execution, callback execution, payload delivery, routing execution, propagation execution, queue processing, filter execution, priority execution, gameplay event execution, scheduler execution, lifecycle execution, orchestration, Workspace mutation, remotes, client authority, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, or cutscene execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Event Graph creates no remotes, client presentation, client authority, event UI, or live event controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "EventGraphCoordinator.inspect" },
		snapshotProviders = { "eventGraph" },
		cleanupBehavior = {
			"shutdown clears event nodes, channels, edges, sources, sinks, subscriptions, propagations, priorities, filters, payload contracts, orderings, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Event Graph schemas only",
			"duplicate Event Graph ids reject within one global namespace",
			"unsafe Event Graph payloads reject before state changes",
			"duplicate rejection happens before state mutation and appears only through sanitized diagnostics",
			"event graph references validate registered schemas before state changes",
			"clients cannot define event graph schemas, dispatch events, subscribe listeners, process queues, route events, or own event truth through this runtime",
		},
		failureModes = {
			"malformed event node, channel, edge, source, sink, subscription, propagation, priority, filter, payload contract, ordering, and audit records reject",
			"unsupported schema types, event domains, channel kinds, edge kinds, propagation kinds, priority kinds, filter kinds, and ordering kinds reject",
			"duplicate Event Graph ids reject globally across every category",
			"invalid event node, channel, source, sink, filter, priority, payload contract, edge, subscription, propagation, ordering, and audit references reject",
			"self-edge, self-subscription, self-ordering, direct edge cycles, and direct ordering contradictions reject",
			"forbidden EventBus, dispatch, publish, subscribe, listener, live listener, callback, signal, remote, payload delivery, payload handle, dispatch handle, subscription handle, listener reference, routing, propagation, queue, filter, payload inspection, priority, live ordering, sequencing, gameplay, puzzle, interaction, inventory, objective, narrative, Monster AI, Presentation, Save, scheduler, lifecycle, orchestration, Workspace, client, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, cutscene, service reference, adapter reference, handler reference, module reference, Framework reference, runtime object, enforcement, remediation, and execute fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"diagnostic copies sanitize unsafe values, live event markers, service markers, remote markers, module markers, Framework markers, listener markers, callback markers, subscription markers, dispatch markers, payload markers, queue markers, and execution markers",
		},
		runtimeLimits = {
			"event nodes are bounded",
			"channels are bounded",
			"edges are bounded",
			"sources are bounded",
			"sinks are bounded",
			"subscriptions are bounded",
			"propagations are bounded",
			"priorities are bounded",
			"filters are bounded",
			"payload contracts are bounded",
			"orderings are bounded",
			"audits are bounded",
			"validation failures and snapshots are bounded",
			"payload depth, node count, string length, tags, reference lists, payload field lists, and audit findings are bounded",
		},
		documentation = {
			"EVENT_GRAPH_RUNTIME.md",
			"EVENT_NODE_RUNTIME.md",
			"EVENT_CHANNEL_RUNTIME.md",
			"EVENT_EDGE_RUNTIME.md",
			"EVENT_SOURCE_RUNTIME.md",
			"EVENT_SINK_RUNTIME.md",
			"EVENT_SUBSCRIPTION_RUNTIME.md",
			"EVENT_PROPAGATION_RUNTIME.md",
			"EVENT_PRIORITY_RUNTIME.md",
			"EVENT_FILTER_RUNTIME.md",
			"EVENT_PAYLOAD_CONTRACT_RUNTIME.md",
			"EVENT_ORDERING_RUNTIME.md",
			"EVENT_AUDIT_RUNTIME.md",
			"EVENT_GRAPH_VALIDATION.md",
			"EVENT_GRAPH_SERIALIZATION.md",
			"EVENT_GRAPH_DIAGNOSTICS.md",
			"EVENT_GRAPH_RUNTIME_LIMITS.md",
			"EVENT_GRAPH_SELF_CHECKS.md",
			"EVENT_GRAPH_AUDIT.md",
			"EVENT_GRAPH_PRODUCTION_REVIEW.md",
		},
		tags = {
			"event-graph",
			"server",
			"foundation",
			"schema-only",
			"no-event-dispatch",
			"no-remotes",
			"no-client-authority",
		},
	},
	{
		systemName = "Rule Engine Runtime Foundation",
		ownerLayer = "RuleEngine",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative rule definition, category, predicate, constraint, permission, policy, group, dependency, outcome, and audit schemas",
			"enforce one global Rule Engine schema namespace across every category",
			"validate schema type, domain, kind, references, relationship safety, limits, unsafe payloads, serialization safety, and forbidden fields before state mutation",
			"enforce rule integrity: rule definitions are records, not executable rules",
			"enforce category integrity: categories are classifications, not enforcement domains",
			"enforce predicate integrity: predicates are schemas, not evaluated conditions",
			"enforce constraint integrity: constraints are schemas, not active limits",
			"enforce permission integrity: permissions are declarations, not grants or denials",
			"enforce policy integrity: policies are schemas, not policy execution",
			"enforce group integrity: groups are collections, not execution batches",
			"enforce dependency integrity: dependencies are metadata, not blockers",
			"enforce outcome integrity: outcomes are possible result schemas, not computed results",
			"enforce audit integrity: audits are review summaries, not enforcement",
			"own Rule Engine diagnostics, snapshots, serialization, validation, deterministic self-checks, and shutdown cleanup",
		},
		doesNotOwn = {
			"live rule evaluation",
			"rule enforcement",
			"gameplay rule execution",
			"predicate execution",
			"condition evaluation",
			"trigger execution",
			"permission granting",
			"permission denial",
			"policy execution",
			"moderation",
			"punishment",
			"anti-cheat enforcement",
			"security enforcement",
			"EventBus execution",
			"scheduler execution",
			"lifecycle execution",
			"runtime orchestration",
			"gameplay execution",
			"puzzle execution",
			"interaction execution",
			"inventory execution",
			"objective execution",
			"narrative execution",
			"Monster AI execution",
			"Presentation execution",
			"Save persistence",
			"content loading",
			"asset loading",
			"map loading",
			"room loading",
			"Workspace mutation",
			"remotes",
			"client authority",
			"DataStore reads/writes",
			"HttpService",
			"MessagingService",
			"analytics collection",
			"telemetry sending",
			"Chapter content",
			"final story",
			"final dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no live rule evaluation, rule enforcement, predicate execution, condition evaluation, trigger execution, permission granting, permission denial, policy execution, moderation, punishment, anti-cheat enforcement, security enforcement, EventBus execution, scheduler execution, lifecycle execution, runtime orchestration, gameplay execution, Save persistence, loading, Workspace mutation, remotes, client authority, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, or cutscene execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Rule Engine creates no remotes, client presentation, client authority, rule UI, permission UI, or live rule controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "RuleEngineCoordinator.inspect" },
		snapshotProviders = { "ruleEngine" },
		cleanupBehavior = {
			"shutdown clears rules, categories, predicates, constraints, permissions, policies, groups, dependencies, outcomes, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Rule Engine schemas only",
			"duplicate Rule Engine ids reject within one global namespace",
			"unsafe Rule Engine payloads reject before state changes",
			"duplicate rejection is deterministic and never mutates existing source-of-truth schemas",
			"rule references validate registered schemas before state changes",
			"clients cannot define rules, evaluate rules, enforce policies, grant permissions, deny permissions, trigger gameplay, or own rule truth through this runtime",
		},
		failureModes = {
			"malformed rule, category, predicate, constraint, permission, policy, group, dependency, outcome, and audit records reject",
			"unsupported schema types, rule domains, rule kinds, predicate kinds, constraint kinds, permission kinds, policy kinds, and outcome kinds reject",
			"duplicate Rule Engine ids reject globally across every category",
			"invalid rule, category, predicate, constraint, permission, policy, dependency, outcome, and audit references reject",
			"self-dependencies and direct dependency cycles reject",
			"forbidden rule evaluation, live rule evaluation, rule enforcement, predicate execution, condition evaluation, trigger execution, permission grant, permission deny, permission execution, permission enforcement, policy execution, policy enforcement, moderation, punishment, anti-cheat, security enforcement, EventBus, scheduler, lifecycle, orchestration, gameplay, puzzle, interaction, inventory, objective, narrative, Monster AI, Presentation, Save, loading, Workspace, remote, client, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, cutscene, service reference, adapter reference, handler reference, callback, module reference, Framework reference, runtime object, enforcement, remediation, and execute fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"diagnostic copies sanitize unsafe values, evaluation markers, permission markers, policy markers, enforcement markers, service markers, remote markers, module markers, Framework markers, callback markers, and execution markers",
		},
		runtimeLimits = {
			"rules are bounded",
			"categories are bounded",
			"predicates are bounded",
			"constraints are bounded",
			"permissions are bounded",
			"policies are bounded",
			"groups are bounded",
			"dependencies are bounded",
			"outcomes are bounded",
			"audits are bounded",
			"validation failures and snapshots are bounded",
			"payload depth, node count, string length, tags, rule reference lists, group rule lists, and audit findings are bounded",
		},
		documentation = {
			"RULE_ENGINE_RUNTIME.md",
			"RULE_DEFINITION_RUNTIME.md",
			"RULE_CATEGORY_RUNTIME.md",
			"RULE_PREDICATE_RUNTIME.md",
			"RULE_CONSTRAINT_RUNTIME.md",
			"RULE_PERMISSION_RUNTIME.md",
			"RULE_POLICY_RUNTIME.md",
			"RULE_GROUP_RUNTIME.md",
			"RULE_DEPENDENCY_RUNTIME.md",
			"RULE_OUTCOME_RUNTIME.md",
			"RULE_AUDIT_RUNTIME.md",
			"RULE_ENGINE_VALIDATION.md",
			"RULE_ENGINE_SERIALIZATION.md",
			"RULE_ENGINE_DIAGNOSTICS.md",
			"RULE_ENGINE_RUNTIME_LIMITS.md",
			"RULE_ENGINE_SELF_CHECKS.md",
			"RULE_ENGINE_AUDIT.md",
			"RULE_ENGINE_PRODUCTION_REVIEW.md",
		},
		tags = {
			"rule-engine",
			"server",
			"foundation",
			"schema-only",
			"no-rule-evaluation",
			"no-rule-enforcement",
			"no-remotes",
		},
	},
	{
		systemName = "Condition Runtime Foundation",
		ownerLayer = "Condition",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative condition definition, category, expression, operand, operator, group, dependency, state, outcome, and audit schemas",
			"enforce one global Condition schema namespace across every category",
			"validate schema type, domain, operator kind, group type, outcome kind, references, relationship safety, limits, unsafe payloads, serialization safety, and forbidden fields before state mutation",
			"enforce condition integrity: condition definitions are records, not decisions",
			"enforce expression integrity: expressions are descriptions, not computations",
			"enforce operator integrity: operators are metadata, not functions",
			"enforce operand integrity: operands are schema values, not live inputs",
			"enforce group integrity: groups are logical structure only",
			"enforce dependency integrity: dependencies are metadata, not blockers",
			"enforce state integrity: states are schema descriptions, not live mutable state",
			"enforce outcome integrity: outcomes are possible future results, not computed facts",
			"enforce audit integrity: audits are review summaries only",
			"reject forbidden condition, expression, boolean, logic, branching, scripting, rule, trigger, gameplay, Director, Monster AI, Narrative, Presentation, Save, Scheduler, Lifecycle, Event Graph, Runtime Graph, Rule Engine, orchestration, state mutation, Workspace, remote, client, service, analytics, telemetry, Chapter, story, dialogue, cutscene, callback, adapter, module, Framework, runtime object, enforcement, remediation, and execution markers in metadata, context, tags, nested keys, and string values",
			"certify category limits, reference list limits, serialization limits, bounded validation failures, bounded snapshots, snapshot isolation, diagnostics isolation, and shutdown cleanup through deterministic self-checks",
			"own Condition diagnostics, snapshots, serialization, validation, deterministic self-checks, and shutdown cleanup",
		},
		doesNotOwn = {
			"condition evaluation",
			"expression evaluation",
			"boolean execution",
			"logic execution",
			"branching logic execution",
			"scripting",
			"rule execution",
			"trigger execution",
			"gameplay execution",
			"puzzle execution",
			"interaction execution",
			"inventory execution",
			"objective execution",
			"Director execution",
			"Monster AI execution",
			"Narrative execution",
			"Presentation execution",
			"Save execution",
			"Rule Engine ownership",
			"Scheduler ownership",
			"Lifecycle ownership",
			"Event Graph ownership",
			"Runtime Graph ownership",
			"Rule Engine execution",
			"Event Graph execution",
			"Runtime Graph execution",
			"runtime orchestration",
			"state mutation",
			"Save persistence",
			"content loading",
			"asset loading",
			"Workspace mutation",
			"remotes",
			"client authority",
			"DataStore reads/writes",
			"HttpService",
			"MessagingService",
			"analytics collection",
			"telemetry sending",
			"Chapter content",
			"final story",
			"final dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no condition evaluation, expression evaluation, boolean execution, rule execution, trigger execution, gameplay execution, puzzle execution, interaction execution, inventory execution, objective execution, Monster AI execution, Narrative execution, Presentation execution, scheduler execution, lifecycle execution, runtime orchestration, Workspace mutation, remote communication, client authority, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, or cutscene execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Condition Runtime creates no remotes, client presentation, client authority, condition UI, branching UI, or live condition controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ConditionCoordinator.inspect" },
		snapshotProviders = { "conditionRuntime" },
		cleanupBehavior = {
			"shutdown clears definitions, categories, expressions, operands, operators, groups, dependencies, states, outcomes, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Condition schemas only",
			"duplicate Condition ids reject within one global namespace",
			"unsafe Condition payloads reject before state changes",
			"duplicate rejection is deterministic and never mutates existing source-of-truth schemas",
			"condition references validate registered schemas before state changes",
			"clients cannot define conditions, evaluate conditions, branch gameplay, execute triggers, or own condition truth through this runtime",
		},
		failureModes = {
			"malformed condition, category, expression, operand, operator, group, dependency, state, outcome, and audit records reject",
			"unsupported schema types, domains, operators, group types, outcome kinds, and dependency kinds reject",
			"duplicate Condition ids reject globally across every category",
			"invalid condition, category, expression, operand, operator, dependency, state, outcome, and audit references reject",
			"self-dependencies and direct dependency cycles reject",
			"forbidden condition evaluation, expression evaluation, boolean execution, logic execution, branching logic, scripting, rule execution, trigger execution, gameplay, puzzle, interaction, inventory, objective, Director, Monster AI, Narrative, Presentation, Save, Scheduler, Lifecycle, Event Graph, Runtime Graph, Rule Engine, orchestration, state mutation, live state, live value, player state, computed result, gameplay result, blocking, short-circuit, comparison, executable function, Workspace, remote, client, DataStore, HTTP, messaging, analytics, telemetry, Chapter, final story, story, final dialogue, dialogue, cutscene, service reference, adapter reference, handler reference, callback, executable callback, execution adapter, module reference, Framework reference, runtime object, Instance reference, enforcement, remediation, execute, run, fire, dispatch, publish, and subscribe fields reject in keys and string values",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"diagnostic copies sanitize unsafe values, evaluation markers, execution markers, service markers, remote markers, module markers, Framework markers, callback markers, and runtime object markers",
		},
		runtimeLimits = {
			"conditions are bounded",
			"categories are bounded",
			"expressions are bounded",
			"operands are bounded",
			"operators are bounded",
			"groups are bounded",
			"dependencies are bounded",
			"states are bounded",
			"outcomes are bounded",
			"audits are bounded",
			"validation failures and snapshots are bounded",
			"payload depth, node count, string length, tags, condition reference lists, group condition lists, expression operands, and audit findings are bounded",
		},
		documentation = {
			"CONDITION_RUNTIME.md",
			"CONDITION_DEFINITION_RUNTIME.md",
			"CONDITION_CATEGORY_RUNTIME.md",
			"CONDITION_EXPRESSION_RUNTIME.md",
			"CONDITION_OPERAND_RUNTIME.md",
			"CONDITION_OPERATOR_RUNTIME.md",
			"CONDITION_GROUP_RUNTIME.md",
			"CONDITION_DEPENDENCY_RUNTIME.md",
			"CONDITION_STATE_RUNTIME.md",
			"CONDITION_OUTCOME_RUNTIME.md",
			"CONDITION_AUDIT_RUNTIME.md",
			"CONDITION_VALIDATION.md",
			"CONDITION_SERIALIZATION.md",
			"CONDITION_DIAGNOSTICS.md",
			"CONDITION_RUNTIME_LIMITS.md",
			"CONDITION_SELF_CHECKS.md",
			"CONDITION_AUDIT.md",
			"CONDITION_PRODUCTION_REVIEW.md",
		},
		tags = {
			"condition",
			"server",
			"foundation",
			"schema-only",
			"no-condition-evaluation",
			"no-rule-execution",
			"no-remotes",
		},
	},
	{
		systemName = "Trigger Runtime Foundation",
		ownerLayer = "Trigger",
		status = "Foundation",
		responsibilities = {
			"own server-authoritative trigger definition, category, source, target, event, filter, condition, dependency, group, outcome, and audit schemas",
			"enforce one global Trigger schema namespace across every category",
			"validate schema type, domain, event kind, group type, outcome kind, references, relationship safety, limits, unsafe payloads, serialization safety, and forbidden fields before state mutation",
			"enforce trigger integrity: trigger definitions are records, not executable triggers",
			"enforce source integrity: sources are metadata, not emitters",
			"enforce target integrity: targets are metadata, not receivers",
			"enforce event integrity: events are descriptions, not dispatched events",
			"enforce filter integrity: filters are descriptions, not executed filters",
			"enforce condition integrity: trigger conditions are references, not evaluated conditions",
			"enforce dependency integrity: dependencies are metadata, not blockers",
			"enforce group integrity: groups are structure only",
			"enforce outcome integrity: outcomes are possible future results, not computed facts",
			"enforce audit integrity: audits are review summaries only",
			"reject forbidden trigger, event, publisher, receiver, listener, callback, condition, rule, scheduler, lifecycle, Event Graph, Runtime Graph, Condition Runtime, runtime orchestration, scripting, state mutation, gameplay, Monster AI, Narrative, Presentation, Save, Workspace, remote, client, service, analytics, telemetry, Chapter, story, dialogue, cutscene, adapter, module, Framework, runtime object, execution adapter, blocking, filtering, computed result, gameplay result, batch, enforcement, remediation, execute, run, fire, dispatch, publish, and subscribe markers in metadata, context, tags, nested keys, and string values",
			"certify category limits, reference list limits, serialization limits, bounded validation failures, bounded snapshots, snapshot isolation, diagnostics isolation, and shutdown cleanup through deterministic self-checks",
			"own Trigger diagnostics, snapshots, serialization, validation, deterministic self-checks, and shutdown cleanup",
		},
		doesNotOwn = {
			"trigger execution",
			"event dispatch",
			"callback execution",
			"listener execution",
			"condition evaluation",
			"rule evaluation",
			"rule execution",
			"gameplay execution",
			"puzzle execution",
			"interaction execution",
			"inventory execution",
			"objective execution",
			"Monster AI execution",
			"Narrative execution",
			"Presentation execution",
			"Scheduler execution",
			"Lifecycle execution",
			"runtime orchestration",
			"scripting",
			"state mutation",
			"Event Graph execution",
			"Runtime Graph execution",
			"Rule Engine execution",
			"Condition Runtime execution",
			"Workspace mutation",
			"remotes",
			"client authority",
			"DataStore reads/writes",
			"HttpService",
			"MessagingService",
			"analytics collection",
			"telemetry sending",
			"Chapter content",
			"final story",
			"final dialogue",
			"cutscenes",
		},
		dependencies = {
			"Core Runtime",
			"Governance",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"schema records only",
			"no trigger execution, event dispatch, callback execution, listener execution, condition evaluation, rule evaluation, rule execution, gameplay execution, Workspace mutation, remote communication, client authority, DataStore, HTTP, messaging, analytics, telemetry, Chapter, story, dialogue, or cutscene execution",
		},
		clientPresentation = {
			allowed = false,
			description = "Trigger Runtime creates no remotes, client presentation, client authority, trigger UI, event UI, or live trigger controls.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "TriggerCoordinator.inspect" },
		snapshotProviders = { "triggerRuntime" },
		cleanupBehavior = {
			"shutdown clears definitions, categories, sources, targets, events, filters, conditions, dependencies, groups, outcomes, audits, validation failures, snapshot history, and the global schema namespace",
		},
		multiplayerGuarantees = {
			"server-authoritative Trigger schemas only",
			"duplicate Trigger ids reject within one global namespace",
			"unsafe Trigger payloads reject before state changes",
			"duplicate rejection is deterministic and never mutates existing source-of-truth schemas",
			"trigger references validate registered schemas before state changes",
			"clients cannot define triggers, execute triggers, dispatch events, invoke callbacks, or own trigger truth through this runtime",
		},
		failureModes = {
			"malformed trigger, category, source, target, event, filter, condition, dependency, group, outcome, and audit records reject",
			"unsupported schema types, domains, event kinds, group types, outcome kinds, and dependency kinds reject",
			"duplicate Trigger ids reject globally across every category",
			"invalid trigger, category, source, target, event, filter, condition, dependency, group, outcome, and audit references reject",
			"self-dependencies and direct dependency cycles reject",
			"forbidden trigger execution, trigger run, trigger fire, trigger dispatch, event dispatch, event fire, event emit, publisher, receiver execution, listener, live listener, callback, condition evaluation, rule evaluation, rule execution, Scheduler, Lifecycle, Event Graph, Runtime Graph, Condition Runtime, runtime orchestration, scripting, state mutation, gameplay, Monster AI, Narrative, Presentation, puzzle, interaction, inventory, objective, Save, Workspace, remote, client, DataStore, HTTP, messaging, analytics, telemetry, Chapter, final story, story, final dialogue, dialogue, cutscene, service reference, adapter reference, handler reference, module reference, Framework reference, runtime object, Instance reference, execution adapter, blocking, payload inspection, live filtering, computed result, gameplay result, execution batch, enforcement, remediation, execute, run, fire, dispatch, publish, and subscribe fields reject",
			"serialization rejects Roblox Instances, cycles, functions, threads, userdata, oversized strings, deep payloads, and oversized node counts",
			"diagnostic copies sanitize unsafe values, execution markers, dispatch markers, service markers, remote markers, module markers, Framework markers, callback markers, listener markers, and runtime object markers",
		},
		runtimeLimits = {
			"triggers are bounded",
			"categories are bounded",
			"sources are bounded",
			"targets are bounded",
			"events are bounded",
			"filters are bounded",
			"conditions are bounded",
			"dependencies are bounded",
			"groups are bounded",
			"outcomes are bounded",
			"audits are bounded",
			"validation failures and snapshots are bounded",
			"payload depth, node count, string length, tags, trigger reference lists, group members, and audit findings are bounded",
		},
		documentation = {
			"TRIGGER_RUNTIME.md",
			"TRIGGER_DEFINITION_RUNTIME.md",
			"TRIGGER_CATEGORY_RUNTIME.md",
			"TRIGGER_SOURCE_RUNTIME.md",
			"TRIGGER_TARGET_RUNTIME.md",
			"TRIGGER_EVENT_RUNTIME.md",
			"TRIGGER_FILTER_RUNTIME.md",
			"TRIGGER_CONDITION_RUNTIME.md",
			"TRIGGER_DEPENDENCY_RUNTIME.md",
			"TRIGGER_GROUP_RUNTIME.md",
			"TRIGGER_OUTCOME_RUNTIME.md",
			"TRIGGER_AUDIT_RUNTIME.md",
			"TRIGGER_VALIDATION.md",
			"TRIGGER_SERIALIZATION.md",
			"TRIGGER_DIAGNOSTICS.md",
			"TRIGGER_RUNTIME_LIMITS.md",
			"TRIGGER_SELF_CHECKS.md",
			"TRIGGER_AUDIT.md",
			"TRIGGER_PRODUCTION_REVIEW.md",
		},
		tags = {
			"trigger",
			"server",
			"foundation",
			"schema-only",
			"no-trigger-execution",
			"no-event-dispatch",
			"no-remotes",
		},
	},
	{
		systemName = "Execution Planning Runtime",
		ownerLayer = "ExecutionPlanning",
		status = "Foundation",
		responsibilities = {
			"Phase 148 deterministic execution graph construction",
			"planning node validation and deterministic ordering",
			"planning dependency validation for missing, duplicate, cyclic, cross-authority, version, and unknown authority failures",
			"planning constraint validation separate from dependency validation",
			"planning eligibility analysis for future legal execution consideration only",
			"immutable planning publication records with deterministic planning hash",
			"planning diagnostics, snapshots, audit, validation, serialization, self-checks, and shutdown cleanup",
			"blocked runtime truth preservation for Studio MCP external transport planning",
		},
		doesNotOwn = {
			"execution authorization",
			"execution scheduling",
			"Studio execution",
			"Runner invocation",
			"transport creation",
			"envelope transmission",
			"acknowledgement reception",
			"MCP communication",
			"runtime evidence generation",
			"certification decisions",
			"gameplay mutation",
			"Workspace mutation",
			"client authority",
			"DataStore writes",
			"analytics",
			"telemetry",
			"Chapter content",
		},
		dependencies = { "Core Runtime" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Execution Planning Runtime is server-only planning metadata.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ExecutionPlanningCoordinator.inspect" },
		snapshotProviders = { "executionPlanningRuntime" },
		cleanupBehavior = {
			"clear planning graph",
			"clear planning publication",
			"clear planning audit",
			"clear validation failures",
		},
		multiplayerGuarantees = {
			"server-only planning metadata",
			"no client-owned planning truth",
			"deterministic rebuild for identical valid input",
			"published planning does not execute for any player",
		},
		failureModes = {
			"invalid planning node schema rejects before publication",
			"duplicate planning node rejects before publication",
			"missing planning dependency rejects before publication",
			"cyclic planning dependency rejects before publication",
			"illegal cross-authority planning ownership rejects before publication",
			"planning dependency version mismatch rejects before publication",
			"planning constraint schema drift rejects before publication",
			"unsafe planning payload rejects before publication",
			"publication remains immutable planning metadata only",
		},
		documentation = {
			"EXECUTION_PLANNING_RUNTIME.md",
			"EXECUTION_PLANNING_VALIDATION.md",
			"EXECUTION_PLANNING_DIAGNOSTICS.md",
			"EXECUTION_PLANNING_SELF_CHECKS.md",
			"EXECUTION_PLANNING_PRODUCTION_REVIEW.md",
		},
		tags = { "execution-planning", "server", "foundation", "metadata-only" },
	},
	{
		systemName = "Execution Authorization Runtime",
		ownerLayer = "ExecutionAuthorization",
		status = "Foundation",
		responsibilities = {
			"Phase 149 deterministic authorization policy metadata",
			"authorization rule-set validation",
			"read-only evaluation of Phase 148 planning publications",
			"authorization decision construction",
			"immutable authorization decision publication",
			"authorization diagnostics, snapshots, audit, validation, serialization, self-checks, and shutdown cleanup",
			"blocked runtime truth preservation for Studio MCP authorization metadata",
		},
		doesNotOwn = {
			"execution planning",
			"execution scheduling",
			"Studio execution",
			"Runner invocation",
			"transport creation",
			"envelope transmission",
			"acknowledgement reception",
			"MCP communication",
			"runtime evidence generation",
			"certification decisions",
			"gameplay mutation",
			"Workspace mutation",
			"client authority",
			"DataStore writes",
			"analytics",
			"telemetry",
			"Chapter content",
		},
		dependencies = { "Core Runtime", "Execution Planning Runtime" },
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {},
		clientPresentation = {
			allowed = false,
			description = "Execution Authorization Runtime is server-only authorization metadata.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = { "ExecutionAuthorizationCoordinator.inspect" },
		snapshotProviders = { "executionAuthorizationRuntime" },
		cleanupBehavior = {
			"clear authorization policies",
			"clear authorization rules",
			"clear authorization decision",
			"clear authorization audit",
			"clear validation failures",
		},
		multiplayerGuarantees = {
			"server-only authorization metadata",
			"no client-owned authorization truth",
			"deterministic authorization for identical planning publication input",
			"authorization decisions do not execute for any player",
		},
		failureModes = {
			"unknown authorization policy rejects before publication",
			"duplicate authorization policy rejects before publication",
			"duplicate authorization rule rejects before publication",
			"missing planning publication rejects before publication",
			"planning version drift rejects before publication",
			"unsupported planning authority rejects before publication",
			"invalid authorization decision rejects before publication",
			"invalid authorization classification rejects before publication",
			"authorization publication remains immutable metadata only",
		},
		documentation = {
			"EXECUTION_AUTHORIZATION_RUNTIME.md",
			"EXECUTION_AUTHORIZATION_VALIDATION.md",
			"EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
			"EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
			"EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		},
		tags = { "execution-authorization", "server", "foundation", "metadata-only" },
	},
	{
		systemName = "Runtime Execution Bridge",
		ownerLayer = "RuntimeExecutionBridge",
		status = "Foundation",
		responsibilities = {
			"Phase 155 Studio-side runtime evidence producer boundary",
			"Studio-gated server observation of runtime services and coordinator visibility",
			"session, manifest, phase, runner, framework version, and source commit binding validation",
			"importer-compatible runtime evidence payload preparation",
			"assertion, diagnostics, snapshot, cleanup, and writer-boundary reporting",
			"truthful blocked writer classification when Roblox runtime cannot write the local evidence file",
		},
		doesNotOwn = {
			"Runtime Execution Framework ownership",
			"backend selection",
			"Node evidence import validation",
			"certification decisions",
			"gameplay mutation",
			"Observation fact ownership",
			"Interaction execution",
			"Presentation execution",
			"Chapter content",
			"Workspace mutation",
			"remotes",
			"client authority",
			"DataStore writes",
			"HTTP calls",
			"MessagingService",
			"analytics",
			"telemetry",
		},
		dependencies = {
			"Core Runtime",
			"Execution Planning Runtime",
			"Execution Authorization Runtime",
		},
		observationsEmitted = {},
		directorApprovalsRequired = {},
		executionPermissions = {
			"Studio-only runtime observation when explicitly enabled by LondonRuntimeExecutionBridgeEnabled",
			"no production automatic execution",
			"no gameplay mutation, networking, persistence, analytics, telemetry, or certification authority",
		},
		clientPresentation = {
			allowed = false,
			description = "Runtime Execution Bridge has no client presentation or client authority.",
			mustBeServerApproved = true,
		},
		diagnosticsExposed = {
			"RuntimeExecutionBridgeCoordinator.inspect",
		},
		snapshotProviders = {
			"runtimeExecutionBridge",
		},
		cleanupBehavior = {
			"shutdown clears session metadata, runtime events, assertions, diagnostics, snapshots, prepared evidence, writer result, and cleanup state",
		},
		multiplayerGuarantees = {
			"server-only Studio runtime observation",
			"no client-owned runtime evidence",
			"no remote command surface",
			"client startup can only be reported when an authorized client bridge exists in a future phase",
		},
		failureModes = {
			"missing or malformed session metadata rejects before capture",
			"wrong phase rejects before capture",
			"certification-enabled policies reject before capture",
			"unsupported writer path blocks evidence export truthfully",
			"prepared evidence cannot claim production certification",
		},
		documentation = {
			"docs/phases/phase-155/01_BRIDGE_ARCHITECTURE.md",
			"docs/phases/phase-155/07_RUNTIME_RESULT_SCHEMA.md",
			"docs/phases/phase-155/08_WRITER.md",
			"docs/phases/phase-155/12_PRODUCTION_REVIEW.md",
		},
		tags = {
			"runtime-execution-bridge",
			"studio",
			"server",
			"evidence-producer",
			"production-candidate",
		},
	},
}

return contracts
