--!strict

local AudioDirectorConfig = {}

AudioDirectorConfig.RecentDecisionLimit = 80
AudioDirectorConfig.RecentSuppressionLimit = 80
AudioDirectorConfig.CooldownLimit = 120
AudioDirectorConfig.DefaultCooldownSeconds = 10
AudioDirectorConfig.MinCooldownSeconds = 3
AudioDirectorConfig.MaxCooldownSeconds = 120
AudioDirectorConfig.MaxObservationPressureDelta = 0.12
AudioDirectorConfig.SelfCheckZoneId = "audio-self-check"

AudioDirectorConfig.PressureThresholds = {
	Release = -0.2,
	Watchful = 0.2,
	Uneasy = 0.45,
	Oppressive = 0.75,
}

AudioDirectorConfig.Requests = {
	{
		id = "audio.whisper.subtle",
		requestKind = "Whisper",
		displayName = "Subtle Whisper",
		intensity = 0.4,
		requiresKnownZone = true,
		majorPressure = false,
		requiresWhisperPolicy = true,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		cooldownSeconds = 12,
		tags = { "whisper", "subtle" },
		description = "Approves future whispers only where audio policy allows them.",
	},
	{
		id = "audio.fake_footstep.distant",
		requestKind = "FakeFootstep",
		displayName = "Distant Fake Footstep",
		intensity = 0.45,
		requiresKnownZone = true,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = true,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		cooldownSeconds = 14,
		tags = { "fake", "footstep" },
		description = "Approves future fake footsteps without playing audio.",
	},
	{
		id = "audio.knock.distant",
		requestKind = "DistantKnock",
		displayName = "Distant Knock",
		intensity = 0.35,
		requiresKnownZone = false,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = true,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = true,
		cooldownSeconds = 10,
		tags = { "knock", "distant" },
		description = "Approves future distant knocks when fake sounds are allowed.",
	},
	{
		id = "audio.breathing.pressure",
		requestKind = "BreathingPressure",
		displayName = "Breathing Pressure",
		intensity = 0.5,
		requiresKnownZone = true,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = true,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = true,
		cooldownSeconds = 12,
		tags = { "breathing", "pressure" },
		description = "Approves future breathing pressure without playback.",
	},
	{
		id = "audio.heartbeat.pressure",
		requestKind = "HeartbeatPressure",
		displayName = "Heartbeat Pressure",
		intensity = 0.55,
		requiresKnownZone = true,
		majorPressure = true,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = true,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = true,
		cooldownSeconds = 20,
		tags = { "heartbeat", "major" },
		description = "Approves future heartbeat pressure where fair.",
	},
	{
		id = "audio.silence.drop",
		requestKind = "SilenceDrop",
		displayName = "Silence Drop",
		intensity = 0.65,
		requiresKnownZone = true,
		majorPressure = true,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = true,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = false,
		supportsPuzzleRoom = false,
		cooldownSeconds = 28,
		tags = { "silence", "major" },
		description = "Approves future silence drops only in fair spaces.",
	},
	{
		id = "audio.rain.muffle",
		requestKind = "RainMuffle",
		displayName = "Rain Muffle",
		intensity = 0.25,
		requiresKnownZone = false,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = true,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		cooldownSeconds = 8,
		tags = { "rain", "muffle" },
		description = "Approves future rain muffling where atmosphere allows it.",
	},
	{
		id = "audio.room.ambience",
		requestKind = "RoomAmbience",
		displayName = "Room Ambience",
		intensity = 0.2,
		requiresKnownZone = false,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		cooldownSeconds = 6,
		tags = { "ambience", "room" },
		description = "Approves future neutral room ambience.",
	},
	{
		id = "audio.safe.protection",
		requestKind = "SafeRoomProtection",
		displayName = "Safe-Room Audio Protection",
		intensity = 0.1,
		requiresKnownZone = false,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		cooldownSeconds = 4,
		tags = { "safe", "protection" },
		description = "Approves future protective safe-room audio behavior.",
	},
	{
		id = "audio.puzzle.protection",
		requestKind = "PuzzleRoomProtection",
		displayName = "Puzzle Audio Protection",
		intensity = 0.1,
		requiresKnownZone = false,
		majorPressure = false,
		requiresWhisperPolicy = false,
		requiresFakeSoundPolicy = false,
		requiresHeartbeatPolicy = false,
		requiresBreathingPolicy = false,
		requiresSilencePolicy = false,
		requiresRainMufflePolicy = false,
		supportsSafeRoom = true,
		supportsPuzzleRoom = true,
		cooldownSeconds = 4,
		tags = { "puzzle", "protection" },
		description = "Approves future readable puzzle-room audio behavior.",
	},
}

return AudioDirectorConfig
