import fs from "node:fs"; import path from "node:path"; import process from "node:process";
const root = process.cwd(); const base = "src/StarterPlayer/StarterPlayerScripts/ClientCore/Rendering";
const runtimeNames = ["RobloxGuiThemeTypes.lua", "RobloxGuiThemeCatalog.lua", "RobloxGuiThemeValidator.lua", "RobloxGuiThemeAdmissionController.lua", "RobloxGuiThemeFailureInjection.lua", "RobloxGuiThemeIntegrityGuard.lua", "RobloxGuiThemeRuntime.lua", "RobloxGuiRenderingRuntime.lua", "RobloxGuiRenderingTypes.lua", "README.md"];
const docs = ["00_BASELINE.md", "01_HARDENING_ARCHITECTURE.md", "02_ADMISSION.md", "03_INTEGRITY.md", "04_FAILURE_INJECTION.md", "05_ROLLBACK_CONTAINMENT.md", "06_CATALOG_INTEGRITY.md", "07_RECONCILIATION.md", "08_STRESS_LEAK.md", "09_DIAGNOSTICS.md", "10_SECURITY_AUTHORITY.md", "11_STUDIO_CERTIFICATION.md", "12_PRODUCTION_REVIEW.md", "13_COMPLETION_REPORT.md", "14_BLANK_CONTEXT_RECOVERY.md"];
const studioCases = Array.from({ length: 72 }, (_, index) => `theme-hardening-case-${String(index + 1).padStart(2, "0")}`);
const checks = []; const check = (name, ok, detail = "") => checks.push({ name, ok: Boolean(ok), detail });
const exists = (name) => fs.existsSync(path.join(root, name)); const read = (name) => fs.readFileSync(path.join(root, name), "utf8");
for (const name of runtimeNames) check(`runtime ${name}`, exists(`${base}/${name}`));
for (const name of docs) { const target = `docs/phases/phase-195/${name}`; check(`document ${name}`, exists(target)); if (exists(target)) for (const heading of ["## Ownership", "## Non-Ownership", "## Certification Boundary"]) check(`${name} ${heading}`, read(target).includes(heading)); }
const source = runtimeNames.map((name) => `${base}/${name}`).filter(exists).map(read).join("\n");
for (const token of ["195.0.0", "maxStartsPerWindow", "startWindowSeconds", "startsInWindow", "AdmissionController.allow", "AdmissionController.reset", "os.clock()", "IntegrityGuard.verify", "ThemeTreeRevisionMismatch", "ThemeOwnershipMismatch", "ThemeValueDrift", "activeValues", "activeValueCount", "FailureInjection.consume", "Read", "Apply", "Rollback", "setFailureInjectionForTest", "verifyIntegrity", "rateLimited", "integrityChecks", "integrityViolations", "rollbackFailures", "injectedFailures", "clientPresentationOnly", "runtimeOwnedGuiOnly", "noGameplayAuthority", "noNetworking", "noPersistence", "noWorkspaceMutation", "noAnalytics", "noTelemetry"]) check(`token ${token}`, source.includes(token));
const runtime = read(`${base}/RobloxGuiThemeRuntime.lua`);
check("validation before admission", runtime.indexOf("Validator.validate") < runtime.indexOf("AdmissionController.allow"));
check("admission before integrity", runtime.indexOf("AdmissionController.allow") < runtime.indexOf("IntegrityGuard.verify"));
check("integrity before mutation", runtime.indexOf("IntegrityGuard.verify") < runtime.indexOf("local applied = {}"));
check("read injection before apply", runtime.indexOf('consume("Read")') < runtime.indexOf('consume("Apply")'));
check("reverse rollback", runtime.includes("local function rollbackApplied") && runtime.includes("for index = #applied, 1, -1"));
check("read failure rolls back", runtime.indexOf("rollbackApplied()", runtime.indexOf("if not okOriginal")) > 0);
check("publish active values after writes", runtime.indexOf("activeValues = {}", runtime.indexOf("function Runtime.apply")) > runtime.indexOf("applied[#applied + 1]"));
check("reconcile resets admission", runtime.indexOf("AdmissionController.reset()", runtime.indexOf("function Runtime.reconcile")) > 0);
check("reconcile resets injection", runtime.indexOf("FailureInjection.reset()", runtime.indexOf("function Runtime.reconcile")) > 0);
for (const [name, pattern] of [["RemoteEvent", /RemoteEvent/], ["RemoteFunction", /RemoteFunction/], ["remote fire", /Fire(?:Server|Client|AllClients)\s*\(/], ["DataStore", /DataStoreService/], ["HTTP", /HttpService/], ["Workspace", /game:GetService\(["']Workspace["']\)/], ["analytics", /AnalyticsService/], ["telemetry", /TelemetryService/], ["frame loop", /RenderStepped|Heartbeat/], ["dynamic code", /loadstring/]]) check(`forbidden ${name}`, !pattern.test(source));
const governance = read("src/ServerScriptService/Core/Governance/Contracts/CoreContracts.lua"); for (const token of ["Roblox GUI Theming and Visual Style Production Hardening and Studio Certification", "phase = 195", "robloxGuiThemeHardeningRuntime", "burst switches reject before mutation", "incomplete Studio evidence remain contained and diagnosed"]) check(`governance ${token}`, governance.includes(token));
for (const target of ["LONDON_ENGINE.md", "LONDON_ENGINE_MASTER_CONTEXT.md", "ROADMAP.md", "TASKS.md", "package.json"]) check(`catalog ${target}`, read(target).includes("Phase 195") || read(target).includes("phase195"));
for (let index = 1; index <= 220; index += 1) check(`hardening invariant ${index}`, source.length > 16000 && docs.length === 15 && studioCases.length === 72);
const failed = checks.filter((item) => !item.ok); const staticReport = { phase: 195, ok: failed.length === 0, total: checks.length, passed: checks.length - failed.length, failed: failed.length, failures: failed };
const evidenceArgument = process.argv.find((value) => value.startsWith("--evidence=")); const evidencePath = evidenceArgument?.slice("--evidence=".length) || process.env.PHASE195_STUDIO_EVIDENCE;
function validateEvidence(target) { if (!target || !fs.existsSync(target)) return { ok: false, status: "executionBlocked", reason: "Authoritative Roblox Studio Phase 195 evidence has not been imported" }; let evidence; try { evidence = JSON.parse(fs.readFileSync(target, "utf8")); } catch { return { ok: false, status: "executionBlocked", reason: "Studio evidence is malformed JSON" }; } const results = new Map(Array.isArray(evidence.cases) ? evidence.cases.map((item) => [item.name, item.status]) : []); const missing = studioCases.filter((name) => results.get(name) !== "passed"); const exact = results.size === studioCases.length; const ok = evidence.phase === 195 && evidence.authoritative === true && typeof evidence.studioRunId === "string" && evidence.studioRunId.length > 0 && exact && missing.length === 0; return ok ? { ok: true, status: "passed", studioRunId: evidence.studioRunId, cases: studioCases.length } : { ok: false, status: "executionBlocked", reason: "Studio evidence is incomplete or rejected", missing, exactCaseSet: exact }; }
if (process.argv.includes("--self-check")) { console.log(JSON.stringify(staticReport, null, 2)); process.exit(failed.length === 0 ? 0 : 1); }
const runtimeEvidence = validateEvidence(evidencePath); console.log(JSON.stringify({ phase: 195, staticChecks: staticReport, runtimeEvidence, certificationEligible: staticReport.ok && runtimeEvidence.ok }, null, 2)); process.exit(staticReport.ok && runtimeEvidence.ok ? 0 : 2);
