--!strict

local Types = {}

Types.Mode = "ServerAuthoritativeAssetExecutionAuthorizationMetadataRuntime"
Types.RuntimeProviderName = "assetExecutionAuthorizationRuntime"
Types.SnapshotKind = "assetExecutionAuthorizationRuntimeSnapshot"
Types.RuntimeName = "AssetExecutionAuthorization"
Types.CoordinatorName = "AssetExecutionAuthorizationCoordinator"

Types.SchemaType = {
	ExecutionAuthorization = "ExecutionAuthorization",
	ExecutionAuthorizationRequirement = "ExecutionAuthorizationRequirement",
	ExecutionAuthorizationEvaluation = "ExecutionAuthorizationEvaluation",
	ExecutionAuthorizationBoundary = "ExecutionAuthorizationBoundary",
	ExecutionAuthorizationAudit = "ExecutionAuthorizationAudit",
}

Types.SchemaFields = {
	ExecutionAuthorization = {
		"authorizationId",
		"governanceId",
		"readinessId",
		"authorizationKind",
		"authorizationStatus",
		"runtimeName",
		"providerName",
		"snapshotProviderName",
		"requirementIds",
		"evaluationIds",
		"boundaryIds",
		"auditIds",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationRequirement = {
		"requirementId",
		"authorizationId",
		"requirementKind",
		"requirementStatus",
		"required",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationEvaluation = {
		"evaluationId",
		"authorizationId",
		"requirementId",
		"evaluationKind",
		"evaluationStatus",
		"evaluator",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationBoundary = {
		"boundaryId",
		"authorizationId",
		"boundaryKind",
		"boundaryStatus",
		"summary",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationAudit = {
		"auditId",
		"authorizationId",
		"evaluationIds",
		"boundaryIds",
		"auditKind",
		"auditStatus",
		"reviewer",
		"evidence",
		"tags",
		"metadata",
	},
}

Types.SchemaFieldCount = {}
for schemaName, fields in pairs(Types.SchemaFields) do
	Types.SchemaFieldCount[schemaName] = #fields
end

Types.AuthorizationKind = {
	GovernanceAuthorization = true,
	ReadinessAuthorization = true,
	BoundaryAuthorization = true,
	RuntimeAuthorization = true,
	ProviderAuthorization = true,
	SnapshotAuthorization = true,
	DocumentationAuthorization = true,
	FutureAuthorization = true,
}

Types.AuthorizationStatus = {
	Declared = true,
	UnderReview = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.RequirementKind = {
	GovernanceRequirement = true,
	ReadinessRequirement = true,
	BoundaryRequirement = true,
	RuntimeRequirement = true,
	ProviderRequirement = true,
	SnapshotRequirement = true,
	DocumentationRequirement = true,
	FutureRequirement = true,
}

Types.RequirementStatus = {
	Required = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.EvaluationKind = {
	GovernanceEvaluation = true,
	ReadinessEvaluation = true,
	BoundaryEvaluation = true,
	RuntimeEvaluation = true,
	ProviderEvaluation = true,
	SnapshotEvaluation = true,
	DocumentationEvaluation = true,
	FutureEvaluation = true,
}

Types.EvaluationStatus = {
	Passed = true,
	Failed = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.BoundaryKind = {
	NoAssetOperation = true,
	NoRuntimeBridge = true,
	NoWorkRouting = true,
	NoWorkDispatch = true,
	NoWorkScheduling = true,
	NoSystemOrchestration = true,
	NoGameplayMutation = true,
	NoPresentationMutation = true,
	NoSaveMutation = true,
	FutureExecutionSeparate = true,
}

Types.BoundaryStatus = {
	Declared = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AuditKind = {
	AuthorizationAudit = true,
	RequirementAudit = true,
	EvaluationAudit = true,
	BoundaryAudit = true,
	ProductionAudit = true,
	FutureAudit = true,
}

Types.AuditStatus = {
	Passed = true,
	Failed = true,
	Warning = true,
	Deferred = true,
	Blocked = true,
}

Types.PostureKeys = {
	"authorizationRuntimePosture",
	"authorizationIsolationPosture",
	"authorizationBoundaryPosture",
	"authorizationEvaluationPosture",
	"authorizationAuditPosture",
	"authorizationRequirementPosture",
	"authorizationIntegrationReadinessPosture",
	"authorizationIntegrationCompatibilityPosture",
	"authorizationIntegrationHardeningPosture",
	"authorizationIntegrationOrderPosture",
	"authorizationExecutionSeparationPosture",
	"authorizationGameplaySeparationPosture",
	"assetExecutionReadinessPosture",
	"assetExecutionReadinessCompatibilityPosture",
	"assetExecutionReadinessBoundaryPosture",
	"assetExecutionReadinessSeparationPosture",
	"assetExecutionReadinessOrderPosture",
	"assetExecutionReadinessIsolationPosture",
	"noExecution",
	"noRouting",
	"noDispatch",
	"noScheduler",
	"noOrchestration",
	"noGameplay",
	"noPresentation",
	"noSave",
	"noAuthorityEscalation",
}

Types.DocumentationFiles = {
	"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
	"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
	"ASSET_EXECUTION_AUTHORIZATION_SERIALIZATION.md",
	"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
	"ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
	"ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
	"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
	"ASSET_EXECUTION_AUTHORIZATION_AUDIT.md",
	"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
	"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
	"AUTHORIZATION_RUNTIME.md",
	"AUTHORIZATION_REQUIREMENT_RUNTIME.md",
	"AUTHORIZATION_EVALUATION_RUNTIME.md",
	"AUTHORIZATION_BOUNDARY_RUNTIME.md",
	"AUTHORIZATION_AUDIT_RUNTIME.md",
}

Types.BootstrapDependencyOrder = {
	"AssetExecutionGovernanceCoordinator",
}

Types.GovernanceSnapshotProviders = {
	"assetExecutionAuthorizationRuntime",
}

Types.IdentityOrder = {
	"AssetExecutionGovernanceCoordinator",
	"AssetExecutionAuthorizationCoordinator",
	"assetExecutionAuthorizationRuntime",
	"assetExecutionAuthorizationRuntimeSnapshot",
}

Types.IntegrationReadinessDeclarationFields = {
	"integrationId",
	"compatibilityId",
	"integrationDeclarationId",
	"integrationKind",
	"integrationStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"engineGovernanceSnapshotProviderName",
	"documentationReference",
	"governanceRuntimeName",
	"governanceProviderName",
	"governanceSnapshotProviderName",
	"authorizationReadinessEvidenceKind",
	"authorizationRuntimeName",
	"authorizationProviderName",
	"authorizationSnapshotProviderName",
	"executionBoundaryKind",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.ExecutionReadinessDeclarationFields = {
	"readinessId",
	"compatibilityId",
	"readinessDeclarationId",
	"readinessKind",
	"readinessStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"engineGovernanceSnapshotProviderName",
	"documentationReference",
	"governanceRuntimeName",
	"governanceProviderName",
	"governanceSnapshotProviderName",
	"authorizationRuntimeName",
	"authorizationProviderName",
	"authorizationSnapshotProviderName",
	"authorizationCoordinatorName",
	"authorizationIntegrationEvidenceKind",
	"futureExecutionRuntimeName",
	"futureExecutionProviderName",
	"futureExecutionSnapshotProviderName",
	"futureExecutionCoordinatorName",
	"executionBoundaryKind",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.IntegrationKind = {
	ExecutionGovernanceCompatibility = true,
	AuthorizationReadinessCompatibility = true,
	AuthorizationRuntimeCompatibility = true,
	ProviderCompatibility = true,
	SnapshotCompatibility = true,
	CoordinatorCompatibility = true,
	BootstrapCompatibility = true,
	EngineGovernanceCompatibility = true,
	DocumentationCompatibility = true,
	SchemaCompatibility = true,
	BoundaryCompatibility = true,
	IsolationCompatibility = true,
	LifecycleCompatibility = true,
	FutureExecutionSeparation = true,
	FutureGameplaySeparation = true,
}

Types.IntegrationStatus = {
	Declared = true,
	Compatible = true,
	IntegrationReady = true,
	BoundaryReady = true,
	ObservationOnly = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.ExecutionBoundaryKind = {
	NoAssetExecutionRuntime = true,
	NoExecutionPermission = true,
	NoExecutionTokens = true,
	NoExecutionCommands = true,
	NoRoutingOrDispatch = true,
	NoQueuesOrScheduler = true,
	NoOrchestration = true,
	NoAssetOperations = true,
	NoGameplayExecution = true,
	FutureExecutionSeparate = true,
	FutureGameplaySeparate = true,
}

Types.ExecutionReadinessKind = {
	GovernanceIdentityReadiness = true,
	GovernanceProviderReadiness = true,
	GovernanceSnapshotReadiness = true,
	AuthorizationIdentityReadiness = true,
	AuthorizationProviderReadiness = true,
	AuthorizationSnapshotReadiness = true,
	AuthorizationCoordinatorReadiness = true,
	AuthorizationIntegrationReadiness = true,
	AuthorizationBoundaryReadiness = true,
	FutureExecutionRuntimeSeparation = true,
	FutureExecutionProviderSeparation = true,
	FutureExecutionSnapshotSeparation = true,
	FutureExecutionCoordinatorSeparation = true,
	BootstrapReadiness = true,
	EngineGovernanceReadiness = true,
	DocumentationReadiness = true,
	SchemaReadiness = true,
	SerializationReadiness = true,
	DiagnosticsReadiness = true,
	SnapshotReadiness = true,
	LifecycleReadiness = true,
	IsolationReadiness = true,
	RuntimeLimitReadiness = true,
	FutureAssetOperationSeparation = true,
	FutureGameplaySeparation = true,
}

Types.ExecutionReadinessStatus = {
	Declared = true,
	Compatible = true,
	ReadinessConfirmed = true,
	BoundaryConfirmed = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.IntegrationReadinessDeclarationOrder = {
	IntegrationIdOrder = {
		"authorization.integration.01.governance.runtime",
		"authorization.integration.02.governance.provider",
		"authorization.integration.03.governance.snapshot",
		"authorization.integration.04.readiness.evidence",
		"authorization.integration.05.authorization.runtime",
		"authorization.integration.06.authorization.provider",
		"authorization.integration.07.authorization.snapshot",
		"authorization.integration.08.authorization.coordinator",
		"authorization.integration.09.authorization.diagnostics",
		"authorization.integration.10.bootstrap.dependency",
		"authorization.integration.11.engine.governance",
		"authorization.integration.12.documentation",
		"authorization.integration.13.schema",
		"authorization.integration.14.enums",
		"authorization.integration.15.references",
		"authorization.integration.16.boundaries",
		"authorization.integration.17.diagnostics.isolation",
		"authorization.integration.18.snapshot.isolation",
		"authorization.integration.19.runtime.limits",
		"authorization.integration.20.lifecycle.cleanup",
		"authorization.integration.21.future.execution",
		"authorization.integration.22.future.gameplay",
	},
	CompatibilityIdOrder = {
		"authorization.compatibility.01.governance.runtime",
		"authorization.compatibility.02.governance.provider",
		"authorization.compatibility.03.governance.snapshot",
		"authorization.compatibility.04.readiness.evidence",
		"authorization.compatibility.05.authorization.runtime",
		"authorization.compatibility.06.authorization.provider",
		"authorization.compatibility.07.authorization.snapshot",
		"authorization.compatibility.08.authorization.coordinator",
		"authorization.compatibility.09.authorization.diagnostics",
		"authorization.compatibility.10.bootstrap.dependency",
		"authorization.compatibility.11.engine.governance",
		"authorization.compatibility.12.documentation",
		"authorization.compatibility.13.schema",
		"authorization.compatibility.14.enums",
		"authorization.compatibility.15.references",
		"authorization.compatibility.16.boundaries",
		"authorization.compatibility.17.diagnostics.isolation",
		"authorization.compatibility.18.snapshot.isolation",
		"authorization.compatibility.19.runtime.limits",
		"authorization.compatibility.20.lifecycle.cleanup",
		"authorization.compatibility.21.future.execution",
		"authorization.compatibility.22.future.gameplay",
	},
	IntegrationDeclarationIdOrder = {
		"authorization.declaration.01.governance.runtime",
		"authorization.declaration.02.governance.provider",
		"authorization.declaration.03.governance.snapshot",
		"authorization.declaration.04.readiness.evidence",
		"authorization.declaration.05.authorization.runtime",
		"authorization.declaration.06.authorization.provider",
		"authorization.declaration.07.authorization.snapshot",
		"authorization.declaration.08.authorization.coordinator",
		"authorization.declaration.09.authorization.diagnostics",
		"authorization.declaration.10.bootstrap.dependency",
		"authorization.declaration.11.engine.governance",
		"authorization.declaration.12.documentation",
		"authorization.declaration.13.schema",
		"authorization.declaration.14.enums",
		"authorization.declaration.15.references",
		"authorization.declaration.16.boundaries",
		"authorization.declaration.17.diagnostics.isolation",
		"authorization.declaration.18.snapshot.isolation",
		"authorization.declaration.19.runtime.limits",
		"authorization.declaration.20.lifecycle.cleanup",
		"authorization.declaration.21.future.execution",
		"authorization.declaration.22.future.gameplay",
	},
	IntegrationKindOrder = {
		"ExecutionGovernanceCompatibility",
		"ExecutionGovernanceCompatibility",
		"ExecutionGovernanceCompatibility",
		"AuthorizationReadinessCompatibility",
		"AuthorizationRuntimeCompatibility",
		"ProviderCompatibility",
		"SnapshotCompatibility",
		"CoordinatorCompatibility",
		"AuthorizationRuntimeCompatibility",
		"BootstrapCompatibility",
		"EngineGovernanceCompatibility",
		"DocumentationCompatibility",
		"SchemaCompatibility",
		"SchemaCompatibility",
		"SchemaCompatibility",
		"BoundaryCompatibility",
		"IsolationCompatibility",
		"IsolationCompatibility",
		"IsolationCompatibility",
		"LifecycleCompatibility",
		"FutureExecutionSeparation",
		"FutureGameplaySeparation",
	},
	IntegrationStatusOrder = {
		"Compatible",
		"Compatible",
		"Compatible",
		"Compatible",
		"IntegrationReady",
		"IntegrationReady",
		"IntegrationReady",
		"IntegrationReady",
		"ObservationOnly",
		"Compatible",
		"Compatible",
		"Compatible",
		"Compatible",
		"Compatible",
		"Compatible",
		"BoundaryReady",
		"ObservationOnly",
		"ObservationOnly",
		"ObservationOnly",
		"ObservationOnly",
		"BoundaryReady",
		"BoundaryReady",
	},
	RuntimeNameOrder = {
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
	},
	ProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	SnapshotProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	CoordinatorNameOrder = {
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
		"AssetExecutionAuthorizationCoordinator",
	},
	DiagnosticsProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	BootstrapDependencyNameOrder = {
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
		"AssetExecutionGovernanceCoordinator",
	},
	EngineGovernanceSnapshotProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	DocumentationReferenceOrder = {
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		"AUTHORIZATION_BOUNDARY_RUNTIME.md",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
		"ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
	},
	GovernanceRuntimeNameOrder = {
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
		"AssetExecutionGovernance",
	},
	GovernanceProviderNameOrder = {
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
	},
	GovernanceSnapshotProviderNameOrder = {
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
		"assetExecutionGovernanceRuntime",
	},
	AuthorizationReadinessEvidenceKindOrder = {
		"GovernanceCompatibility",
		"GovernanceProviderCompatibility",
		"GovernanceSnapshotCompatibility",
		"AuthorizationReadinessCompatibility",
		"AuthorizationRuntimeIdentity",
		"AuthorizationProviderIdentity",
		"AuthorizationSnapshotIdentity",
		"AuthorizationCoordinatorIdentity",
		"AuthorizationDiagnosticsIdentity",
		"BootstrapCompatibility",
		"EngineGovernanceCompatibility",
		"DocumentationCompatibility",
		"SchemaCompatibility",
		"EnumCompatibility",
		"ReferenceCompatibility",
		"BoundaryCompatibility",
		"DiagnosticsIsolation",
		"SnapshotIsolation",
		"RuntimeLimitIsolation",
		"LifecycleCleanup",
		"FutureExecutionSeparation",
		"FutureGameplaySeparation",
	},
	AuthorizationRuntimeNameOrder = {
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
		"AssetExecutionAuthorization",
	},
	AuthorizationProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	AuthorizationSnapshotProviderNameOrder = {
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
		"assetExecutionAuthorizationRuntime",
	},
	ExecutionBoundaryKindOrder = {
		"NoAssetExecutionRuntime",
		"NoExecutionPermission",
		"NoExecutionTokens",
		"NoExecutionCommands",
		"NoRoutingOrDispatch",
		"NoQueuesOrScheduler",
		"NoOrchestration",
		"NoAssetOperations",
		"NoGameplayExecution",
		"FutureExecutionSeparate",
		"FutureGameplaySeparate",
		"NoAssetExecutionRuntime",
		"NoExecutionPermission",
		"NoExecutionTokens",
		"NoExecutionCommands",
		"NoRoutingOrDispatch",
		"NoQueuesOrScheduler",
		"NoOrchestration",
		"NoAssetOperations",
		"NoGameplayExecution",
		"FutureExecutionSeparate",
		"FutureGameplaySeparate",
	},
	RequiredOrder = {
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		true,
	},
}

Types.AuthorizationIntegrationReadinessDeclarations = {
	{
		integrationId = "authorization.integration.01.governance.runtime",
		compatibilityId = "authorization.compatibility.01.governance.runtime",
		integrationDeclarationId = "authorization.declaration.01.governance.runtime",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetExecutionRuntime",
		required = true,
		evidence = { "authorization.integration.governance.runtime.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "01", compatibility = "governance.runtime" },
	},
	{
		integrationId = "authorization.integration.02.governance.provider",
		compatibilityId = "authorization.compatibility.02.governance.provider",
		integrationDeclarationId = "authorization.declaration.02.governance.provider",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceProviderCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionPermission",
		required = true,
		evidence = { "authorization.integration.governance.provider.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "02", compatibility = "governance.provider" },
	},
	{
		integrationId = "authorization.integration.03.governance.snapshot",
		compatibilityId = "authorization.compatibility.03.governance.snapshot",
		integrationDeclarationId = "authorization.declaration.03.governance.snapshot",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceSnapshotCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionTokens",
		required = true,
		evidence = { "authorization.integration.governance.snapshot.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "03", compatibility = "governance.snapshot" },
	},
	{
		integrationId = "authorization.integration.04.readiness.evidence",
		compatibilityId = "authorization.compatibility.04.readiness.evidence",
		integrationDeclarationId = "authorization.declaration.04.readiness.evidence",
		integrationKind = "AuthorizationReadinessCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationReadinessCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionCommands",
		required = true,
		evidence = { "authorization.integration.readiness.evidence.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "04", compatibility = "readiness.evidence" },
	},
	{
		integrationId = "authorization.integration.05.authorization.runtime",
		compatibilityId = "authorization.compatibility.05.authorization.runtime",
		integrationDeclarationId = "authorization.declaration.05.authorization.runtime",
		integrationKind = "AuthorizationRuntimeCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationRuntimeIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoRoutingOrDispatch",
		required = true,
		evidence = { "authorization.integration.authorization.runtime.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "05", compatibility = "authorization.runtime" },
	},
	{
		integrationId = "authorization.integration.06.authorization.provider",
		compatibilityId = "authorization.compatibility.06.authorization.provider",
		integrationDeclarationId = "authorization.declaration.06.authorization.provider",
		integrationKind = "ProviderCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationProviderIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoQueuesOrScheduler",
		required = true,
		evidence = { "authorization.integration.authorization.provider.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "06", compatibility = "authorization.provider" },
	},
	{
		integrationId = "authorization.integration.07.authorization.snapshot",
		compatibilityId = "authorization.compatibility.07.authorization.snapshot",
		integrationDeclarationId = "authorization.declaration.07.authorization.snapshot",
		integrationKind = "SnapshotCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationSnapshotIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoOrchestration",
		required = true,
		evidence = { "authorization.integration.authorization.snapshot.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "07", compatibility = "authorization.snapshot" },
	},
	{
		integrationId = "authorization.integration.08.authorization.coordinator",
		compatibilityId = "authorization.compatibility.08.authorization.coordinator",
		integrationDeclarationId = "authorization.declaration.08.authorization.coordinator",
		integrationKind = "CoordinatorCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationCoordinatorIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetOperations",
		required = true,
		evidence = { "authorization.integration.authorization.coordinator.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "08", compatibility = "authorization.coordinator" },
	},
	{
		integrationId = "authorization.integration.09.authorization.diagnostics",
		compatibilityId = "authorization.compatibility.09.authorization.diagnostics",
		integrationDeclarationId = "authorization.declaration.09.authorization.diagnostics",
		integrationKind = "AuthorizationRuntimeCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationDiagnosticsIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoGameplayExecution",
		required = true,
		evidence = { "authorization.integration.authorization.diagnostics.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "09", compatibility = "authorization.diagnostics" },
	},
	{
		integrationId = "authorization.integration.10.bootstrap.dependency",
		compatibilityId = "authorization.compatibility.10.bootstrap.dependency",
		integrationDeclarationId = "authorization.declaration.10.bootstrap.dependency",
		integrationKind = "BootstrapCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "BootstrapCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureExecutionSeparate",
		required = true,
		evidence = { "authorization.integration.bootstrap.dependency.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "10", compatibility = "bootstrap.dependency" },
	},
	{
		integrationId = "authorization.integration.11.engine.governance",
		compatibilityId = "authorization.compatibility.11.engine.governance",
		integrationDeclarationId = "authorization.declaration.11.engine.governance",
		integrationKind = "EngineGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "EngineGovernanceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureGameplaySeparate",
		required = true,
		evidence = { "authorization.integration.engine.governance.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "11", compatibility = "engine.governance" },
	},
	{
		integrationId = "authorization.integration.12.documentation",
		compatibilityId = "authorization.compatibility.12.documentation",
		integrationDeclarationId = "authorization.declaration.12.documentation",
		integrationKind = "DocumentationCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "DocumentationCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetExecutionRuntime",
		required = true,
		evidence = { "authorization.integration.documentation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "12", compatibility = "documentation" },
	},
	{
		integrationId = "authorization.integration.13.schema",
		compatibilityId = "authorization.compatibility.13.schema",
		integrationDeclarationId = "authorization.declaration.13.schema",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "SchemaCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionPermission",
		required = true,
		evidence = { "authorization.integration.schema.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "13", compatibility = "schema" },
	},
	{
		integrationId = "authorization.integration.14.enums",
		compatibilityId = "authorization.compatibility.14.enums",
		integrationDeclarationId = "authorization.declaration.14.enums",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "EnumCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionTokens",
		required = true,
		evidence = { "authorization.integration.enums.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "14", compatibility = "enums" },
	},
	{
		integrationId = "authorization.integration.15.references",
		compatibilityId = "authorization.compatibility.15.references",
		integrationDeclarationId = "authorization.declaration.15.references",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "ReferenceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionCommands",
		required = true,
		evidence = { "authorization.integration.references.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "15", compatibility = "references" },
	},
	{
		integrationId = "authorization.integration.16.boundaries",
		compatibilityId = "authorization.compatibility.16.boundaries",
		integrationDeclarationId = "authorization.declaration.16.boundaries",
		integrationKind = "BoundaryCompatibility",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "AUTHORIZATION_BOUNDARY_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "BoundaryCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoRoutingOrDispatch",
		required = true,
		evidence = { "authorization.integration.boundaries.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "16", compatibility = "boundaries" },
	},
	{
		integrationId = "authorization.integration.17.diagnostics.isolation",
		compatibilityId = "authorization.compatibility.17.diagnostics.isolation",
		integrationDeclarationId = "authorization.declaration.17.diagnostics.isolation",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "DiagnosticsIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoQueuesOrScheduler",
		required = true,
		evidence = { "authorization.integration.diagnostics.isolation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "17", compatibility = "diagnostics.isolation" },
	},
	{
		integrationId = "authorization.integration.18.snapshot.isolation",
		compatibilityId = "authorization.compatibility.18.snapshot.isolation",
		integrationDeclarationId = "authorization.declaration.18.snapshot.isolation",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "SnapshotIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoOrchestration",
		required = true,
		evidence = { "authorization.integration.snapshot.isolation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "18", compatibility = "snapshot.isolation" },
	},
	{
		integrationId = "authorization.integration.19.runtime.limits",
		compatibilityId = "authorization.compatibility.19.runtime.limits",
		integrationDeclarationId = "authorization.declaration.19.runtime.limits",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "RuntimeLimitIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetOperations",
		required = true,
		evidence = { "authorization.integration.runtime.limits.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "19", compatibility = "runtime.limits" },
	},
	{
		integrationId = "authorization.integration.20.lifecycle.cleanup",
		compatibilityId = "authorization.compatibility.20.lifecycle.cleanup",
		integrationDeclarationId = "authorization.declaration.20.lifecycle.cleanup",
		integrationKind = "LifecycleCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "LifecycleCleanup",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoGameplayExecution",
		required = true,
		evidence = { "authorization.integration.lifecycle.cleanup.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "20", compatibility = "lifecycle.cleanup" },
	},
	{
		integrationId = "authorization.integration.21.future.execution",
		compatibilityId = "authorization.compatibility.21.future.execution",
		integrationDeclarationId = "authorization.declaration.21.future.execution",
		integrationKind = "FutureExecutionSeparation",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "FutureExecutionSeparation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureExecutionSeparate",
		required = true,
		evidence = { "authorization.integration.future.execution.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "21", compatibility = "future.execution" },
	},
	{
		integrationId = "authorization.integration.22.future.gameplay",
		compatibilityId = "authorization.compatibility.22.future.gameplay",
		integrationDeclarationId = "authorization.declaration.22.future.gameplay",
		integrationKind = "FutureGameplaySeparation",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "FutureGameplaySeparation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureGameplaySeparate",
		required = true,
		evidence = { "authorization.integration.future.gameplay.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "22", compatibility = "future.gameplay" },
	},
}

local function orderNameForField(fieldName: string): string
	return string.upper(string.sub(fieldName, 1, 1)) .. string.sub(fieldName, 2) .. "Order"
end

local EXECUTION_READINESS_ROWS = {
	{
		"01",
		"governance.identity",
		"GovernanceIdentityReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
		"GovernanceCompatibility",
		"NoAssetExecutionRuntime",
	},
	{
		"02",
		"governance.provider",
		"GovernanceProviderReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
		"GovernanceProviderCompatibility",
		"NoExecutionPermission",
	},
	{
		"03",
		"governance.snapshot",
		"GovernanceSnapshotReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
		"GovernanceSnapshotCompatibility",
		"NoExecutionTokens",
	},
	{
		"04",
		"authorization.identity",
		"AuthorizationIdentityReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationRuntimeIdentity",
		"NoExecutionCommands",
	},
	{
		"05",
		"authorization.provider",
		"AuthorizationProviderReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationProviderIdentity",
		"NoRoutingOrDispatch",
	},
	{
		"06",
		"authorization.snapshot",
		"AuthorizationSnapshotReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationSnapshotIdentity",
		"NoQueuesOrScheduler",
	},
	{
		"07",
		"authorization.coordinator",
		"AuthorizationCoordinatorReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"AuthorizationCoordinatorIdentity",
		"NoOrchestration",
	},
	{
		"08",
		"authorization.integration",
		"AuthorizationIntegrationReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		"AuthorizationReadinessCompatibility",
		"NoAssetOperations",
	},
	{
		"09",
		"authorization.boundary",
		"AuthorizationBoundaryReadiness",
		"BoundaryConfirmed",
		"AUTHORIZATION_BOUNDARY_RUNTIME.md",
		"BoundaryCompatibility",
		"NoGameplayExecution",
	},
	{
		"10",
		"future.runtime",
		"FutureExecutionRuntimeSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureExecutionSeparation",
		"FutureExecutionSeparate",
	},
	{
		"11",
		"future.provider",
		"FutureExecutionProviderSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureExecutionSeparation",
		"NoAssetExecutionRuntime",
	},
	{
		"12",
		"future.snapshot",
		"FutureExecutionSnapshotSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureExecutionSeparation",
		"NoExecutionPermission",
	},
	{
		"13",
		"future.coordinator",
		"FutureExecutionCoordinatorSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureExecutionSeparation",
		"NoExecutionTokens",
	},
	{
		"14",
		"bootstrap",
		"BootstrapReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		"BootstrapCompatibility",
		"NoExecutionCommands",
	},
	{
		"15",
		"engine.governance",
		"EngineGovernanceReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"EngineGovernanceCompatibility",
		"NoRoutingOrDispatch",
	},
	{
		"16",
		"documentation",
		"DocumentationReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_EXECUTION_READINESS.md",
		"DocumentationCompatibility",
		"NoQueuesOrScheduler",
	},
	{
		"17",
		"schema",
		"SchemaReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		"SchemaCompatibility",
		"NoOrchestration",
	},
	{
		"18",
		"serialization",
		"SerializationReadiness",
		"Compatible",
		"ASSET_EXECUTION_AUTHORIZATION_SERIALIZATION.md",
		"SchemaCompatibility",
		"NoAssetOperations",
	},
	{
		"19",
		"diagnostics",
		"DiagnosticsReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"DiagnosticsIsolation",
		"NoGameplayExecution",
	},
	{
		"20",
		"snapshot",
		"SnapshotReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"SnapshotIsolation",
		"FutureExecutionSeparate",
	},
	{
		"21",
		"lifecycle",
		"LifecycleReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
		"LifecycleCleanup",
		"FutureGameplaySeparate",
	},
	{
		"22",
		"isolation",
		"IsolationReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		"DiagnosticsIsolation",
		"NoAssetExecutionRuntime",
	},
	{
		"23",
		"runtime.limits",
		"RuntimeLimitReadiness",
		"ReadinessConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
		"RuntimeLimitIsolation",
		"NoExecutionPermission",
	},
	{
		"24",
		"future.asset.operation",
		"FutureAssetOperationSeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureExecutionSeparation",
		"NoAssetOperations",
	},
	{
		"25",
		"future.gameplay",
		"FutureGameplaySeparation",
		"BoundaryConfirmed",
		"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		"FutureGameplaySeparation",
		"FutureGameplaySeparate",
	},
}

Types.AssetExecutionReadinessDeclarations = {}
Types.ExecutionReadinessDeclarationOrder = {}
for _, fieldName in ipairs(Types.ExecutionReadinessDeclarationFields) do
	if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
		Types.ExecutionReadinessDeclarationOrder[orderNameForField(fieldName)] = {}
	end
end

for _, row in ipairs(EXECUTION_READINESS_ROWS) do
	local order = row[1]
	local compatibility = row[2]
	local declaration = {
		readinessId = "asset.execution.readiness." .. order .. "." .. compatibility,
		compatibilityId = "asset.execution.compatibility." .. order .. "." .. compatibility,
		readinessDeclarationId = "asset.execution.declaration." .. order .. "." .. compatibility,
		readinessKind = row[3],
		readinessStatus = row[4],
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = row[5],
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		authorizationCoordinatorName = "AssetExecutionAuthorizationCoordinator",
		authorizationIntegrationEvidenceKind = row[6],
		futureExecutionRuntimeName = "AssetExecutionRuntime",
		futureExecutionProviderName = "assetExecutionRuntime",
		futureExecutionSnapshotProviderName = "assetExecutionRuntime",
		futureExecutionCoordinatorName = "AssetExecutionCoordinator",
		executionBoundaryKind = row[7],
		required = true,
		evidence = { "asset.execution.readiness." .. compatibility .. ".copied" },
		tags = { "asset.execution.readiness", "metadata.only" },
		metadata = { copied = "true", order = order, compatibility = compatibility },
	}
	table.insert(Types.AssetExecutionReadinessDeclarations, declaration)
	for _, fieldName in ipairs(Types.ExecutionReadinessDeclarationFields) do
		if fieldName ~= "evidence" and fieldName ~= "tags" and fieldName ~= "metadata" then
			table.insert(
				Types.ExecutionReadinessDeclarationOrder[orderNameForField(fieldName)],
				declaration[fieldName]
			)
		end
	end
end

Types.Limits = {
	MaxAuthorizations = 180,
	MaxRequirements = 540,
	MaxEvaluations = 540,
	MaxBoundaries = 360,
	MaxAudits = 260,
	MaxValidationFailures = 220,
	MaxSnapshotHistory = 60,
	MaxPayloadDepth = 8,
	MaxPayloadNodes = 520,
	MaxStringLength = 280,
	MaxTags = 32,
	MaxEvidence = 56,
	MaxChildReferences = 220,
	MaxSummaryLength = 180,
}

return Types
