--!strict

local Types = {}

Types.Mode = "ServerAuthoritativeAssetExecutionAuthorizationMetadataRuntime"
Types.RuntimeProviderName = "assetExecutionAuthorizationRuntime"
Types.SnapshotKind = "assetExecutionAuthorizationRuntimeSnapshot"
Types.RuntimeName = "AssetExecutionAuthorization"
Types.CoordinatorName = "AssetExecutionAuthorizationCoordinator"

Types.SchemaType = {
	ExecutionAuthorization = "ExecutionAuthorization",
	ExecutionAuthorizationRequirement = "ExecutionAuthorizationRequirement",
	ExecutionAuthorizationEvaluation = "ExecutionAuthorizationEvaluation",
	ExecutionAuthorizationBoundary = "ExecutionAuthorizationBoundary",
	ExecutionAuthorizationAudit = "ExecutionAuthorizationAudit",
}

Types.SchemaFields = {
	ExecutionAuthorization = {
		"authorizationId",
		"governanceId",
		"readinessId",
		"authorizationKind",
		"authorizationStatus",
		"runtimeName",
		"providerName",
		"snapshotProviderName",
		"requirementIds",
		"evaluationIds",
		"boundaryIds",
		"auditIds",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationRequirement = {
		"requirementId",
		"authorizationId",
		"requirementKind",
		"requirementStatus",
		"required",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationEvaluation = {
		"evaluationId",
		"authorizationId",
		"requirementId",
		"evaluationKind",
		"evaluationStatus",
		"evaluator",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationBoundary = {
		"boundaryId",
		"authorizationId",
		"boundaryKind",
		"boundaryStatus",
		"summary",
		"evidence",
		"tags",
		"metadata",
	},
	ExecutionAuthorizationAudit = {
		"auditId",
		"authorizationId",
		"evaluationIds",
		"boundaryIds",
		"auditKind",
		"auditStatus",
		"reviewer",
		"evidence",
		"tags",
		"metadata",
	},
}

Types.SchemaFieldCount = {}
for schemaName, fields in pairs(Types.SchemaFields) do
	Types.SchemaFieldCount[schemaName] = #fields
end

Types.AuthorizationKind = {
	GovernanceAuthorization = true,
	ReadinessAuthorization = true,
	BoundaryAuthorization = true,
	RuntimeAuthorization = true,
	ProviderAuthorization = true,
	SnapshotAuthorization = true,
	DocumentationAuthorization = true,
	FutureAuthorization = true,
}

Types.AuthorizationStatus = {
	Declared = true,
	UnderReview = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.RequirementKind = {
	GovernanceRequirement = true,
	ReadinessRequirement = true,
	BoundaryRequirement = true,
	RuntimeRequirement = true,
	ProviderRequirement = true,
	SnapshotRequirement = true,
	DocumentationRequirement = true,
	FutureRequirement = true,
}

Types.RequirementStatus = {
	Required = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.EvaluationKind = {
	GovernanceEvaluation = true,
	ReadinessEvaluation = true,
	BoundaryEvaluation = true,
	RuntimeEvaluation = true,
	ProviderEvaluation = true,
	SnapshotEvaluation = true,
	DocumentationEvaluation = true,
	FutureEvaluation = true,
}

Types.EvaluationStatus = {
	Passed = true,
	Failed = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.BoundaryKind = {
	NoAssetOperation = true,
	NoRuntimeBridge = true,
	NoWorkRouting = true,
	NoWorkDispatch = true,
	NoWorkScheduling = true,
	NoSystemOrchestration = true,
	NoGameplayMutation = true,
	NoPresentationMutation = true,
	NoSaveMutation = true,
	FutureExecutionSeparate = true,
}

Types.BoundaryStatus = {
	Declared = true,
	Satisfied = true,
	Unsatisfied = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.AuditKind = {
	AuthorizationAudit = true,
	RequirementAudit = true,
	EvaluationAudit = true,
	BoundaryAudit = true,
	ProductionAudit = true,
	FutureAudit = true,
}

Types.AuditStatus = {
	Passed = true,
	Failed = true,
	Warning = true,
	Deferred = true,
	Blocked = true,
}

Types.PostureKeys = {
	"authorizationRuntimePosture",
	"authorizationIsolationPosture",
	"authorizationBoundaryPosture",
	"authorizationEvaluationPosture",
	"authorizationAuditPosture",
	"authorizationRequirementPosture",
	"authorizationIntegrationReadinessPosture",
	"authorizationIntegrationCompatibilityPosture",
	"authorizationExecutionSeparationPosture",
	"authorizationGameplaySeparationPosture",
	"noExecution",
	"noRouting",
	"noDispatch",
	"noScheduler",
	"noOrchestration",
	"noGameplay",
	"noPresentation",
	"noSave",
	"noAuthorityEscalation",
}

Types.DocumentationFiles = {
	"ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
	"ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
	"ASSET_EXECUTION_AUTHORIZATION_SERIALIZATION.md",
	"ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
	"ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
	"ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
	"ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
	"ASSET_EXECUTION_AUTHORIZATION_AUDIT.md",
	"ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
	"AUTHORIZATION_RUNTIME.md",
	"AUTHORIZATION_REQUIREMENT_RUNTIME.md",
	"AUTHORIZATION_EVALUATION_RUNTIME.md",
	"AUTHORIZATION_BOUNDARY_RUNTIME.md",
	"AUTHORIZATION_AUDIT_RUNTIME.md",
}

Types.BootstrapDependencyOrder = {
	"AssetExecutionGovernanceCoordinator",
}

Types.GovernanceSnapshotProviders = {
	"assetExecutionAuthorizationRuntime",
}

Types.IdentityOrder = {
	"AssetExecutionGovernanceCoordinator",
	"AssetExecutionAuthorizationCoordinator",
	"assetExecutionAuthorizationRuntime",
	"assetExecutionAuthorizationRuntimeSnapshot",
}

Types.IntegrationReadinessDeclarationFields = {
	"integrationId",
	"compatibilityId",
	"integrationDeclarationId",
	"integrationKind",
	"integrationStatus",
	"runtimeName",
	"providerName",
	"snapshotProviderName",
	"coordinatorName",
	"diagnosticsProviderName",
	"bootstrapDependencyName",
	"engineGovernanceSnapshotProviderName",
	"documentationReference",
	"governanceRuntimeName",
	"governanceProviderName",
	"governanceSnapshotProviderName",
	"authorizationReadinessEvidenceKind",
	"authorizationRuntimeName",
	"authorizationProviderName",
	"authorizationSnapshotProviderName",
	"executionBoundaryKind",
	"required",
	"evidence",
	"tags",
	"metadata",
}

Types.IntegrationKind = {
	ExecutionGovernanceCompatibility = true,
	AuthorizationReadinessCompatibility = true,
	AuthorizationRuntimeCompatibility = true,
	ProviderCompatibility = true,
	SnapshotCompatibility = true,
	CoordinatorCompatibility = true,
	BootstrapCompatibility = true,
	EngineGovernanceCompatibility = true,
	DocumentationCompatibility = true,
	SchemaCompatibility = true,
	BoundaryCompatibility = true,
	IsolationCompatibility = true,
	LifecycleCompatibility = true,
	FutureExecutionSeparation = true,
	FutureGameplaySeparation = true,
}

Types.IntegrationStatus = {
	Declared = true,
	Compatible = true,
	IntegrationReady = true,
	BoundaryReady = true,
	ObservationOnly = true,
	Deferred = true,
	Warning = true,
	Blocked = true,
}

Types.ExecutionBoundaryKind = {
	NoAssetExecutionRuntime = true,
	NoExecutionPermission = true,
	NoExecutionTokens = true,
	NoExecutionCommands = true,
	NoRoutingOrDispatch = true,
	NoQueuesOrScheduler = true,
	NoOrchestration = true,
	NoAssetOperations = true,
	NoGameplayExecution = true,
	FutureExecutionSeparate = true,
	FutureGameplaySeparate = true,
}

Types.AuthorizationIntegrationReadinessDeclarations = {
	{
		integrationId = "authorization.integration.01.governance.runtime",
		compatibilityId = "authorization.compatibility.01.governance.runtime",
		integrationDeclarationId = "authorization.declaration.01.governance.runtime",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetExecutionRuntime",
		required = true,
		evidence = { "authorization.integration.governance.runtime.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "01", compatibility = "governance.runtime" },
	},
	{
		integrationId = "authorization.integration.02.governance.provider",
		compatibilityId = "authorization.compatibility.02.governance.provider",
		integrationDeclarationId = "authorization.declaration.02.governance.provider",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceProviderCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionPermission",
		required = true,
		evidence = { "authorization.integration.governance.provider.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "02", compatibility = "governance.provider" },
	},
	{
		integrationId = "authorization.integration.03.governance.snapshot",
		compatibilityId = "authorization.compatibility.03.governance.snapshot",
		integrationDeclarationId = "authorization.declaration.03.governance.snapshot",
		integrationKind = "ExecutionGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "GovernanceSnapshotCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionTokens",
		required = true,
		evidence = { "authorization.integration.governance.snapshot.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "03", compatibility = "governance.snapshot" },
	},
	{
		integrationId = "authorization.integration.04.readiness.evidence",
		compatibilityId = "authorization.compatibility.04.readiness.evidence",
		integrationDeclarationId = "authorization.declaration.04.readiness.evidence",
		integrationKind = "AuthorizationReadinessCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationReadinessCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionCommands",
		required = true,
		evidence = { "authorization.integration.readiness.evidence.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "04", compatibility = "readiness.evidence" },
	},
	{
		integrationId = "authorization.integration.05.authorization.runtime",
		compatibilityId = "authorization.compatibility.05.authorization.runtime",
		integrationDeclarationId = "authorization.declaration.05.authorization.runtime",
		integrationKind = "AuthorizationRuntimeCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationRuntimeIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoRoutingOrDispatch",
		required = true,
		evidence = { "authorization.integration.authorization.runtime.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "05", compatibility = "authorization.runtime" },
	},
	{
		integrationId = "authorization.integration.06.authorization.provider",
		compatibilityId = "authorization.compatibility.06.authorization.provider",
		integrationDeclarationId = "authorization.declaration.06.authorization.provider",
		integrationKind = "ProviderCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationProviderIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoQueuesOrScheduler",
		required = true,
		evidence = { "authorization.integration.authorization.provider.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "06", compatibility = "authorization.provider" },
	},
	{
		integrationId = "authorization.integration.07.authorization.snapshot",
		compatibilityId = "authorization.compatibility.07.authorization.snapshot",
		integrationDeclarationId = "authorization.declaration.07.authorization.snapshot",
		integrationKind = "SnapshotCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationSnapshotIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoOrchestration",
		required = true,
		evidence = { "authorization.integration.authorization.snapshot.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "07", compatibility = "authorization.snapshot" },
	},
	{
		integrationId = "authorization.integration.08.authorization.coordinator",
		compatibilityId = "authorization.compatibility.08.authorization.coordinator",
		integrationDeclarationId = "authorization.declaration.08.authorization.coordinator",
		integrationKind = "CoordinatorCompatibility",
		integrationStatus = "IntegrationReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationCoordinatorIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetOperations",
		required = true,
		evidence = { "authorization.integration.authorization.coordinator.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "08", compatibility = "authorization.coordinator" },
	},
	{
		integrationId = "authorization.integration.09.authorization.diagnostics",
		compatibilityId = "authorization.compatibility.09.authorization.diagnostics",
		integrationDeclarationId = "authorization.declaration.09.authorization.diagnostics",
		integrationKind = "AuthorizationRuntimeCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "AuthorizationDiagnosticsIdentity",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoGameplayExecution",
		required = true,
		evidence = { "authorization.integration.authorization.diagnostics.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "09", compatibility = "authorization.diagnostics" },
	},
	{
		integrationId = "authorization.integration.10.bootstrap.dependency",
		compatibilityId = "authorization.compatibility.10.bootstrap.dependency",
		integrationDeclarationId = "authorization.declaration.10.bootstrap.dependency",
		integrationKind = "BootstrapCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "BootstrapCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureExecutionSeparate",
		required = true,
		evidence = { "authorization.integration.bootstrap.dependency.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "10", compatibility = "bootstrap.dependency" },
	},
	{
		integrationId = "authorization.integration.11.engine.governance",
		compatibilityId = "authorization.compatibility.11.engine.governance",
		integrationDeclarationId = "authorization.declaration.11.engine.governance",
		integrationKind = "EngineGovernanceCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "EngineGovernanceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureGameplaySeparate",
		required = true,
		evidence = { "authorization.integration.engine.governance.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "11", compatibility = "engine.governance" },
	},
	{
		integrationId = "authorization.integration.12.documentation",
		compatibilityId = "authorization.compatibility.12.documentation",
		integrationDeclarationId = "authorization.declaration.12.documentation",
		integrationKind = "DocumentationCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_INTEGRATION_READINESS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "DocumentationCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetExecutionRuntime",
		required = true,
		evidence = { "authorization.integration.documentation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "12", compatibility = "documentation" },
	},
	{
		integrationId = "authorization.integration.13.schema",
		compatibilityId = "authorization.compatibility.13.schema",
		integrationDeclarationId = "authorization.declaration.13.schema",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "SchemaCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionPermission",
		required = true,
		evidence = { "authorization.integration.schema.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "13", compatibility = "schema" },
	},
	{
		integrationId = "authorization.integration.14.enums",
		compatibilityId = "authorization.compatibility.14.enums",
		integrationDeclarationId = "authorization.declaration.14.enums",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "EnumCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionTokens",
		required = true,
		evidence = { "authorization.integration.enums.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "14", compatibility = "enums" },
	},
	{
		integrationId = "authorization.integration.15.references",
		compatibilityId = "authorization.compatibility.15.references",
		integrationDeclarationId = "authorization.declaration.15.references",
		integrationKind = "SchemaCompatibility",
		integrationStatus = "Compatible",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_VALIDATION.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "ReferenceCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoExecutionCommands",
		required = true,
		evidence = { "authorization.integration.references.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "15", compatibility = "references" },
	},
	{
		integrationId = "authorization.integration.16.boundaries",
		compatibilityId = "authorization.compatibility.16.boundaries",
		integrationDeclarationId = "authorization.declaration.16.boundaries",
		integrationKind = "BoundaryCompatibility",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "AUTHORIZATION_BOUNDARY_RUNTIME.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "BoundaryCompatibility",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoRoutingOrDispatch",
		required = true,
		evidence = { "authorization.integration.boundaries.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "16", compatibility = "boundaries" },
	},
	{
		integrationId = "authorization.integration.17.diagnostics.isolation",
		compatibilityId = "authorization.compatibility.17.diagnostics.isolation",
		integrationDeclarationId = "authorization.declaration.17.diagnostics.isolation",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "DiagnosticsIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoQueuesOrScheduler",
		required = true,
		evidence = { "authorization.integration.diagnostics.isolation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "17", compatibility = "diagnostics.isolation" },
	},
	{
		integrationId = "authorization.integration.18.snapshot.isolation",
		compatibilityId = "authorization.compatibility.18.snapshot.isolation",
		integrationDeclarationId = "authorization.declaration.18.snapshot.isolation",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_DIAGNOSTICS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "SnapshotIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoOrchestration",
		required = true,
		evidence = { "authorization.integration.snapshot.isolation.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "18", compatibility = "snapshot.isolation" },
	},
	{
		integrationId = "authorization.integration.19.runtime.limits",
		compatibilityId = "authorization.compatibility.19.runtime.limits",
		integrationDeclarationId = "authorization.declaration.19.runtime.limits",
		integrationKind = "IsolationCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_RUNTIME_LIMITS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "RuntimeLimitIsolation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoAssetOperations",
		required = true,
		evidence = { "authorization.integration.runtime.limits.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "19", compatibility = "runtime.limits" },
	},
	{
		integrationId = "authorization.integration.20.lifecycle.cleanup",
		compatibilityId = "authorization.compatibility.20.lifecycle.cleanup",
		integrationDeclarationId = "authorization.declaration.20.lifecycle.cleanup",
		integrationKind = "LifecycleCompatibility",
		integrationStatus = "ObservationOnly",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_SELF_CHECKS.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "LifecycleCleanup",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "NoGameplayExecution",
		required = true,
		evidence = { "authorization.integration.lifecycle.cleanup.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "20", compatibility = "lifecycle.cleanup" },
	},
	{
		integrationId = "authorization.integration.21.future.execution",
		compatibilityId = "authorization.compatibility.21.future.execution",
		integrationDeclarationId = "authorization.declaration.21.future.execution",
		integrationKind = "FutureExecutionSeparation",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "FutureExecutionSeparation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureExecutionSeparate",
		required = true,
		evidence = { "authorization.integration.future.execution.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "21", compatibility = "future.execution" },
	},
	{
		integrationId = "authorization.integration.22.future.gameplay",
		compatibilityId = "authorization.compatibility.22.future.gameplay",
		integrationDeclarationId = "authorization.declaration.22.future.gameplay",
		integrationKind = "FutureGameplaySeparation",
		integrationStatus = "BoundaryReady",
		runtimeName = "AssetExecutionAuthorization",
		providerName = "assetExecutionAuthorizationRuntime",
		snapshotProviderName = "assetExecutionAuthorizationRuntime",
		coordinatorName = "AssetExecutionAuthorizationCoordinator",
		diagnosticsProviderName = "assetExecutionAuthorizationRuntime",
		bootstrapDependencyName = "AssetExecutionGovernanceCoordinator",
		engineGovernanceSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		documentationReference = "ASSET_EXECUTION_AUTHORIZATION_PRODUCTION_REVIEW.md",
		governanceRuntimeName = "AssetExecutionGovernance",
		governanceProviderName = "assetExecutionGovernanceRuntime",
		governanceSnapshotProviderName = "assetExecutionGovernanceRuntime",
		authorizationReadinessEvidenceKind = "FutureGameplaySeparation",
		authorizationRuntimeName = "AssetExecutionAuthorization",
		authorizationProviderName = "assetExecutionAuthorizationRuntime",
		authorizationSnapshotProviderName = "assetExecutionAuthorizationRuntime",
		executionBoundaryKind = "FutureGameplaySeparate",
		required = true,
		evidence = { "authorization.integration.future.gameplay.copied" },
		tags = { "authorization.integration", "metadata.only" },
		metadata = { copied = "true", order = "22", compatibility = "future.gameplay" },
	},
}

Types.Limits = {
	MaxAuthorizations = 180,
	MaxRequirements = 540,
	MaxEvaluations = 540,
	MaxBoundaries = 360,
	MaxAudits = 260,
	MaxValidationFailures = 220,
	MaxSnapshotHistory = 60,
	MaxPayloadDepth = 8,
	MaxPayloadNodes = 520,
	MaxStringLength = 280,
	MaxTags = 32,
	MaxEvidence = 56,
	MaxChildReferences = 220,
	MaxSummaryLength = 180,
}

return Types
